# Advent of Code 2021

This notebook is solutions to [2021 Advent of Code](https://adventofcode.com/2021/) challenges.

---
## https://adventofcode.com/2021/day/1 &mdash; Sonar Sweep

## Part 1

This part asks to find how many numbers represent increasese from the previous number.

### Strategy
- `zip` the `data` w/ `data[1:]` into sequential tuples.
- create a list of all cases where the first entry is less than the second.
- report the length of that list.

## Part 2

This part asks to find how many of the sliding-window sums (with a window of size 3) represent increasese from the previous sliding-window sum.

### Strategy
- create a list of the the sliding-window sums by `zip`ping `data`, `data[1:]`, and `data[2:]`.
- follow the same strategy as *Part 1* with this new list.

In [1]:
#!/usr/bin/env python3
#
# https://adventofcode.com/2021/
#
# AOC 2021 01
#
# aoc202101.py
#

print('# AOC 2021 01')

data = [ int(x) for x in """
127
147
148
147
146
153
154
167
184
181
194
183
188
195
193
207
208
220
222
234
226
247
248
253
257
250
251
285
293
294
314
311
305
312
318
321
322
344
353
354
383
391
393
394
369
373
377
378
385
388
400
402
414
422
435
414
422
436
446
455
463
478
483
482
499
495
501
506
507
509
529
522
526
527
530
529
535
536
520
525
516
518
524
525
519
520
525
531
539
551
555
579
583
594
593
594
611
610
613
616
630
637
645
641
644
646
659
671
672
676
678
682
686
688
694
720
725
735
741
742
748
745
747
752
775
776
778
777
791
797
799
800
801
806
802
804
808
817
815
817
825
830
838
839
848
849
856
861
868
875
881
875
877
858
867
861
865
855
856
857
858
859
863
866
860
871
884
882
893
904
905
917
938
951
957
958
963
967
979
980
979
980
995
994
992
994
996
998
1007
992
1026
1027
1019
1024
1023
1039
1026
1038
1045
1050
1059
1056
1059
1060
1057
1058
1060
1072
1092
1101
1110
1116
1155
1166
1187
1189
1190
1202
1207
1208
1224
1239
1237
1243
1242
1261
1284
1283
1284
1283
1298
1287
1283
1280
1277
1280
1309
1314
1315
1321
1323
1324
1332
1356
1358
1360
1363
1364
1365
1367
1366
1382
1398
1400
1407
1421
1444
1449
1461
1464
1465
1471
1475
1466
1475
1476
1479
1494
1500
1519
1521
1531
1539
1533
1544
1547
1561
1562
1561
1574
1580
1581
1588
1589
1591
1604
1600
1601
1606
1607
1614
1599
1604
1606
1605
1611
1612
1615
1616
1618
1619
1621
1624
1639
1643
1637
1644
1645
1644
1639
1652
1665
1677
1683
1687
1694
1700
1706
1696
1691
1727
1728
1732
1739
1751
1749
1762
1774
1773
1769
1770
1774
1766
1767
1775
1759
1760
1759
1770
1776
1777
1781
1782
1783
1784
1785
1796
1805
1807
1808
1809
1810
1806
1803
1805
1806
1808
1807
1794
1796
1818
1824
1827
1830
1818
1831
1834
1844
1846
1857
1865
1866
1888
1890
1891
1895
1904
1912
1910
1911
1931
1929
1933
1944
1946
1958
1968
1982
1983
1980
1957
1961
1968
1966
1968
1970
1975
1978
1983
1991
1995
1997
2017
2018
2022
2025
2038
2039
2042
2068
2065
2068
2070
2071
2079
2081
2084
2085
2086
2100
2104
2106
2107
2116
2125
2129
2131
2132
2133
2141
2128
2121
2113
2103
2120
2117
2119
2120
2135
2136
2148
2151
2133
2134
2140
2150
2166
2167
2169
2172
2175
2178
2187
2188
2189
2186
2187
2206
2239
2238
2244
2238
2239
2207
2208
2209
2210
2211
2210
2217
2219
2220
2222
2224
2229
2234
2237
2234
2240
2237
2239
2245
2244
2245
2239
2238
2263
2266
2269
2278
2291
2292
2295
2296
2298
2299
2306
2310
2321
2326
2335
2338
2339
2340
2345
2350
2354
2355
2374
2373
2379
2381
2396
2394
2400
2405
2411
2412
2423
2426
2431
2432
2428
2429
2444
2459
2470
2454
2458
2460
2464
2468
2482
2483
2487
2509
2505
2507
2487
2504
2499
2508
2540
2550
2551
2554
2555
2537
2541
2529
2525
2533
2534
2535
2536
2511
2518
2537
2536
2549
2550
2563
2594
2597
2602
2608
2619
2638
2642
2645
2649
2654
2667
2672
2689
2710
2713
2730
2726
2731
2739
2733
2722
2720
2722
2723
2724
2733
2743
2759
2743
2741
2742
2751
2757
2759
2761
2771
2810
2805
2815
2820
2822
2825
2822
2836
2838
2839
2837
2845
2850
2853
2879
2881
2886
2888
2907
2908
2909
2911
2924
2925
2928
2929
2930
2946
2947
2949
2954
2936
2944
2947
2953
2954
2956
2971
2976
2977
2968
2967
2972
2973
2977
2970
2975
2987
2997
2996
2998
2993
2996
2997
2999
3031
3028
3039
3043
3045
3026
3028
3036
3044
3046
3019
3023
3020
3021
3023
3025
3037
3038
3039
3062
3063
3081
3086
3081
3082
3083
3098
3105
3106
3108
3110
3107
3116
3125
3139
3137
3143
3144
3145
3159
3162
3172
3173
3172
3173
3174
3182
3183
3177
3185
3175
3178
3179
3195
3210
3201
3205
3202
3203
3191
3188
3197
3198
3206
3215
3233
3240
3243
3253
3254
3264
3267
3289
3267
3271
3280
3290
3308
3307
3308
3316
3320
3311
3318
3331
3343
3357
3358
3360
3389
3402
3403
3405
3407
3420
3380
3372
3374
3380
3357
3356
3361
3356
3364
3365
3366
3367
3386
3387
3388
3389
3406
3407
3409
3413
3416
3441
3443
3441
3442
3446
3448
3454
3453
3457
3461
3467
3459
3469
3482
3497
3490
3497
3495
3494
3495
3496
3498
3494
3510
3515
3535
3536
3535
3544
3562
3557
3546
3553
3557
3558
3555
3562
3571
3573
3575
3591
3590
3591
3592
3598
3600
3608
3609
3648
3653
3654
3657
3655
3657
3660
3669
3670
3671
3667
3669
3674
3676
3683
3687
3688
3699
3720
3719
3720
3726
3729
3734
3737
3757
3767
3773
3774
3778
3780
3779
3777
3781
3782
3801
3800
3798
3802
3803
3806
3817
3819
3834
3837
3838
3839
3837
3846
3850
3851
3868
3865
3890
3893
3895
3889
3884
3886
3887
3884
3886
3903
3905
3906
3909
3911
3922
3927
3943
3953
3959
3961
3960
3954
3933
3932
3939
3941
3942
3941
3950
3951
3971
3947
3953
3962
3996
4017
4032
4036
4040
4067
4068
4073
4096
4098
4097
4093
4115
4118
4119
4144
4148
4149
4161
4173
4177
4182
4185
4186
4196
4184
4196
4198
4210
4214
4210
4217
4195
4206
4192
4193
4205
4208
4184
4203
4204
4205
4211
4205
4206
4182
4193
4195
4196
4212
4213
4216
4215
4222
4232
4230
4251
4255
4256
4271
4281
4279
4292
4295
4301
4302
4303
4285
4288
4292
4294
4296
4299
4282
4285
4290
4318
4331
4340
4335
4329
4335
4347
4379
4388
4375
4384
4411
4415
4416
4418
4416
4428
4430
4431
4432
4420
4436
4439
4446
4458
4459
4472
4468
4493
4495
4468
4469
4474
4475
4502
4505
4516
4522
4518
4519
4532
4535
4540
4534
4530
4534
4535
4538
4544
4543
4546
4543
4545
4548
4550
4557
4559
4560
4555
4569
4576
4579
4597
4596
4603
4597
4596
4620
4619
4617
4602
4605
4606
4612
4625
4626
4651
4647
4650
4649
4668
4674
4686
4687
4695
4723
4726
4739
4752
4754
4765
4781
4809
4797
4799
4797
4796
4799
4802
4804
4807
4808
4809
4810
4811
4820
4828
4829
4830
4833
4825
4829
4830
4839
4844
4848
4849
4858
4882
4877
4878
4882
4883
4869
4871
4872
4876
4879
4880
4878
4880
4899
4921
4922
4919
4920
4915
4916
4917
4938
4939
4940
4938
4941
4943
4944
4947
4967
4968
4981
4982
4983
4993
4994
4995
5000
5001
5007
5008
5007
5000
5017
5026
5040
5048
5050
5046
5084
5083
5089
5097
5101
5061
5060
5078
5079
5095
5096
5102
5129
5126
5127
5125
5127
5128
5123
5129
5132
5146
5156
5157
5182
5198
5201
5208
5211
5212
5215
5217
5200
5204
5205
5207
5212
5218
5206
5207
5214
5220
5230
5236
5241
5240
5245
5246
5242
5240
5239
5242
5232
5230
5225
5232
5226
5221
5224
5234
5240
5263
5268
5301
5303
5310
5311
5332
5337
5338
5339
5324
5341
5346
5323
5324
5325
5329
5330
5331
5338
5360
5361
5371
5373
5362
5375
5387
5393
5387
5396
5417
5418
5421
5422
5404
5405
5412
5414
5413
5444
5445
5446
5447
5453
5463
5473
5478
5480
5484
5479
5489
5494
5484
5506
5500
5510
5512
5519
5520
5518
5523
5524
5529
5533
5520
5521
5522
5521
5530
5535
5550
5551
5544
5551
5552
5549
5550
5551
5547
5589
5603
5612
5614
5623
5622
5624
5617
5639
5641
5627
5630
5634
5641
5646
5648
5655
5679
5665
5666
5669
5687
5688
5692
5690
5688
5691
5695
5696
5697
5699
5698
5715
5716
5717
5744
5741
5750
5743
5712
5716
5717
5743
5746
5749
5751
5752
5761
5767
5769
5784
5785
5786
5784
5786
5787
5790
5799
5807
5808
5826
5828
5826
5837
5856
5876
5877
5879
5887
5890
5892
5894
5911
5922
5935
5936
5942
5950
5966
5985
5986
5976
5979
5976
5984
5950
5951
5955
5964
5965
5969
5974
5990
6008
6038
6045
6051
6060
6066
6070
6105
6120
6121
6127
6149
6150
6157
6162
6163
6165
6185
6186
6190
6191
6218
6235
6250
6231
6239
6229
6237
6240
6241
6243
6249
6264
6251
6257
6276
6279
6271
6290
6292
6290
6293
6294
6287
6289
6290
6291
6293
6294
6300
6295
6296
6303
6332
6334
6333
6340
6341
6344
6345
6346
6352
6356
6355
6368
6370
6361
6362
6359
6361
6362
6368
6364
6373
6374
6383
6384
6385
6384
6389
6388
6389
6404
6410
6415
6407
6406
6405
6402
6407
6413
6412
6398
6384
6386
6407
6408
6409
6408
6418
6415
6416
6418
6427
6434
6458
6455
6456
6457
6458
6468
6463
6454
6455
6459
6460
6464
6471
6463
6480
6467
6468
6470
6462
6463
6464
6462
6461
6463
6471
6482
6459
6460
6462
6469
6484
6479
6481
6492
6502
6477
6483
6486
6488
6466
6467
6463
6444
6464
6466
6482
6497
6498
6511
6512
6517
6522
6521
6524
6547
6549
6553
6557
6562
6563
6567
6596
6597
6602
6588
6620
6621
6613
6608
6616
6632
6648
6683
6688
6693
6694
6697
6707
6705
6710
6722
6721
6717
6731
6725
6733
6749
6750
6751
6752
6769
6770
6777
6800
6825
6834
6838
6839
6854
6862
6863
6867
6858
6854
6887
6890
6891
6890
6900
6899
6900
6918
6922
6940
6941
6946
6948
6927
6928
6924
6907
6910
6917
6920
6931
6943
6971
6973
6974
6978
7001
7000
7001
7017
7018
7019
7020
7021
7023
7027
6998
6980
6979
6975
6974
6984
6992
6994
7003
7011
7012
7029
7041
7044
7063
7065
7067
7069
7076
7074
7076
7080
7083
7086
7108
7137
7141
7142
7159
7160
7158
7157
7165
7167
7189
7193
7194
7192
7196
7200
7203
7209
7214
7219
7209
7169
7168
7169
7171
7168
7170
7165
7166
7176
7178
7168
7165
7169
7170
7171
7172
7176
7177
7178
7179
7174
7178
7182
7158
7172
7193
7199
7192
7191
7194
7192
7195
7199
7202
7201
7216
7213
7237
7256
7245
7246
7249
7263
7265
7262
7272
7273
7294
7298
7296
7300
7301
7313
7314
7316
7318
7326
7327
7328
7330
7349
7350
7366
7381
7382
7383
7390
7399
7382
7384
7380
7381
7385
7388
7402
7403
7404
7405
7409
7420
7424
7420
7421
7426
7429
7435
7425
7426
7429
7452
7455
7474
7469
7472
7473
7466
7461
7462
7470
7472
7474
7480
7474
7475
7473
7472
7475
7484
7472
7473
7489
7491
7514
7516
7509
7510
7513
7514
7539
7549
7571
7582
7570
7573
7574
7575
7576
7581
7589
7587
7590
7592
7598
7625
7627
7626
7627
7633
7638
7640
7641
7645
7657
7669
7670
7654
7681
7682
7679
7689
7690
7696
7709
7718
7723
7721
7722
7728
7751
7764
7756
7747
7748
7757
7766
7779
7784
7785
7804
7805
7808
7809
7808
7834
7836
7837
7853
7854
7855
7866
7901
7920
7930
7931
7928
7931
7916
7917
7947
7948
7952
7948
7985
7984
7988
7998
8004
8017
8016
8033
8035
8039
8053
8062
8063
8064
8068
8085
8104
8103
8104
8107
8113
8116
8127
8129
8119
8117
8139
8140
8142
8151
8153
8168
8169
8172
8161
8162
8165
8168
8176
8180
8182
8188
8196
8197
8209
8211
8212
8219
8222
8187
8191
8192
8207
8208
8211
8213
8196
8207
8215
8214
8217
8207
8208
8209
8228
8233
8241
8245
8257
8258
8257
8258
8259
8263
8269
8273
8276
8274
8269
8276
8279
8280
8267
8263
8266
8264
8266
8267
8270
8272
8271
8280
8286
8296
8312
8314
8320
8322
8335
8339
8340
8338
8367
8401
8415
8416
8419
8420
8426
8427
8425
8440
8438
8447
8446
8453
8486
8492
8488
8503
8512
8525
8523
8508
8520
8522
8547
8552
8542
8541
8561
8562
8583
8584
8585
8586
8594
8593
""".split() ]
print(data)

def part1(data):
    """Answer part 1 of https://adventofcode.com/2021/day/1"""
    # print([ x1 < x2 for x1, x2 in zip(data, data[1:]) ])
    return len([ x1 < x2 for x1, x2 in zip(data, data[1: ]) if x1 < x2 ])
print(part1(data))

def part2(data):
    """Answer part 2 of https://adventofcode.com/2021/day/1"""
    # print([ sum(t) for t in zip(data, data[1: ], data[2: ]) ])
    windows = [ sum(t) for t in zip(data, data[1: ], data[2: ]) ]
    return len([ x1 < x2 for x1, x2 in zip(windows, windows[1: ]) if x1 < x2 ])
print(part2(data))


# AOC 2021 01
[127, 147, 148, 147, 146, 153, 154, 167, 184, 181, 194, 183, 188, 195, 193, 207, 208, 220, 222, 234, 226, 247, 248, 253, 257, 250, 251, 285, 293, 294, 314, 311, 305, 312, 318, 321, 322, 344, 353, 354, 383, 391, 393, 394, 369, 373, 377, 378, 385, 388, 400, 402, 414, 422, 435, 414, 422, 436, 446, 455, 463, 478, 483, 482, 499, 495, 501, 506, 507, 509, 529, 522, 526, 527, 530, 529, 535, 536, 520, 525, 516, 518, 524, 525, 519, 520, 525, 531, 539, 551, 555, 579, 583, 594, 593, 594, 611, 610, 613, 616, 630, 637, 645, 641, 644, 646, 659, 671, 672, 676, 678, 682, 686, 688, 694, 720, 725, 735, 741, 742, 748, 745, 747, 752, 775, 776, 778, 777, 791, 797, 799, 800, 801, 806, 802, 804, 808, 817, 815, 817, 825, 830, 838, 839, 848, 849, 856, 861, 868, 875, 881, 875, 877, 858, 867, 861, 865, 855, 856, 857, 858, 859, 863, 866, 860, 871, 884, 882, 893, 904, 905, 917, 938, 951, 957, 958, 963, 967, 979, 980, 979, 980, 995, 994, 992, 994, 996, 998, 1007, 992, 1026, 1027, 1019, 1024, 1023, 1039

---
## https://adventofcode.com/2021/day/2 &mdash; Drive!

## Part 1

This part asks to find the product of two things:

- the sum of forward distances;
- the sum of down (+) and up (-) distances.

### Strategy

- parse the data into three distinct types: no sign ('forward'), plus sign ('down'), and minus sign ('up').
- report the product of the no-sign numbers' sum (for forward distance) and the signed numbers' sum (for up-and-down distance).

## Part 2

This part asks to find the product of two *other* things

- the sum of forward distances (as from *Part 1*);
- the `depth` as calculated from a running `aim` (the integral of 'down' and 'up') and a running accumulator of the product of the running `aim` and the instantaneous 'forward' distance.

### Strategy

- parse the data into three distinct types: no sign ('forward'), plus sign ('down'), and minus sign ('up').
- accumulate a running `aim` (for up-and-down distance) and a running `depth` (for the product of the running `aim` and the instantaneous forward distance) &mdash; this cannot be a one-liner, as the acumulated `depth` depends on the integrated `aim`.
- report the product of the no-sign numbers' sum (for forward distance) and the acumulated `depth`.

In [2]:
#!/usr/bin/env python3
#
# https://adventofcode.com/2021/
#
# AOC 2021 02
#
# aoc202102.py
#

print('# AOC 2021 2')

process = lambda t: ('' if t[0][0] is 'f' else '+' if t[0][0] is 'd' else '-') + t[1]

data = [ process(t) for t in [ l.split() for l in """
forward 8
down 9
up 4
down 8
down 3
down 3
down 2
forward 1
forward 4
down 5
up 7
forward 1
down 1
down 6
down 9
down 5
forward 5
forward 6
forward 4
down 2
down 8
forward 3
down 5
forward 6
up 7
up 2
forward 2
forward 4
forward 1
up 8
up 9
down 8
up 8
up 6
up 2
down 7
up 3
forward 8
forward 5
down 8
down 8
forward 5
down 3
down 4
down 5
down 2
up 7
down 1
forward 9
forward 9
up 6
down 5
up 1
down 8
up 1
forward 2
down 4
down 5
down 2
up 7
forward 9
up 8
down 3
up 6
down 2
up 2
forward 3
up 1
up 1
forward 9
down 3
down 5
up 7
down 1
up 5
up 5
up 7
down 9
down 3
up 3
forward 9
forward 7
up 9
down 3
down 2
up 8
forward 5
forward 9
down 5
down 2
down 9
down 6
down 6
up 3
forward 3
up 6
forward 9
down 3
down 2
forward 6
down 7
down 2
down 8
forward 2
forward 8
forward 4
forward 1
up 6
forward 2
forward 8
forward 5
forward 4
up 1
down 8
up 3
forward 8
forward 4
up 6
down 2
forward 6
forward 9
down 2
up 3
forward 8
down 6
up 4
down 7
up 3
forward 4
down 8
forward 5
forward 1
down 3
forward 1
forward 8
down 3
forward 4
forward 2
up 7
forward 6
forward 8
forward 6
down 5
down 2
down 8
down 2
down 9
down 5
down 3
down 8
up 1
forward 1
up 5
up 1
up 6
up 3
up 2
forward 5
forward 6
down 4
up 3
up 9
down 1
forward 1
forward 6
down 9
forward 5
forward 3
forward 2
down 7
down 5
down 8
forward 9
forward 4
down 2
up 9
down 1
forward 5
forward 1
forward 9
down 8
forward 5
down 8
forward 3
up 4
down 7
down 9
forward 3
forward 7
down 9
up 5
up 7
forward 8
down 3
down 9
down 1
forward 3
down 1
up 9
forward 6
down 9
forward 1
forward 5
down 6
up 7
forward 9
down 9
forward 6
down 3
up 6
up 2
up 1
up 9
down 9
forward 4
forward 6
up 7
forward 2
down 5
forward 7
down 5
forward 4
down 8
up 3
down 1
forward 5
down 5
up 6
down 6
forward 4
down 8
down 6
down 7
down 9
down 4
forward 5
down 8
down 7
forward 3
forward 5
up 8
down 4
down 1
up 6
up 9
down 2
down 2
up 1
up 7
forward 1
down 1
down 4
down 8
forward 1
forward 3
down 8
up 9
forward 1
down 6
forward 3
down 9
down 2
up 8
forward 5
up 1
forward 9
down 4
forward 3
up 6
up 4
down 9
down 8
down 3
forward 6
forward 6
down 1
down 2
down 2
down 2
up 7
down 2
forward 9
down 3
up 5
forward 9
up 5
forward 1
down 1
forward 7
down 8
down 9
down 1
forward 8
up 1
forward 8
down 1
forward 9
down 8
down 2
forward 4
up 2
down 7
forward 6
forward 6
forward 4
up 8
up 2
down 8
up 7
forward 2
forward 6
forward 3
up 5
forward 9
down 9
forward 6
up 2
down 6
forward 4
forward 5
down 3
up 2
forward 3
forward 2
up 7
down 1
up 1
up 8
down 4
forward 7
forward 2
up 2
down 4
forward 4
forward 2
forward 2
down 8
down 2
down 2
forward 6
up 2
up 9
down 1
down 7
forward 9
forward 4
up 8
forward 2
forward 5
down 3
down 6
down 4
forward 7
up 1
forward 7
down 8
up 2
down 8
forward 6
down 3
up 9
up 6
up 6
forward 5
forward 1
forward 3
forward 3
down 7
down 3
forward 8
forward 2
down 7
down 1
up 4
forward 2
forward 1
up 6
forward 9
up 4
forward 5
up 4
forward 3
down 1
forward 6
forward 2
down 3
down 7
forward 7
down 4
forward 6
down 8
forward 5
up 9
up 9
forward 4
forward 8
down 6
down 7
forward 1
up 4
forward 9
forward 7
forward 2
forward 6
up 4
forward 4
down 3
down 2
up 4
forward 4
forward 3
up 8
forward 8
down 9
forward 4
forward 6
forward 7
down 5
forward 6
down 3
up 2
down 4
forward 1
up 3
forward 4
down 7
down 9
down 6
up 7
down 2
down 5
forward 7
up 6
down 2
forward 4
down 9
up 8
forward 6
down 4
down 3
up 9
down 6
down 9
up 3
down 2
forward 3
down 1
forward 1
forward 5
down 7
forward 2
down 8
down 8
down 7
forward 5
forward 9
forward 9
forward 2
up 5
down 2
forward 3
down 2
forward 9
up 1
forward 1
up 6
down 1
forward 4
down 5
forward 2
up 7
up 4
up 3
forward 6
down 5
forward 6
down 6
forward 6
down 2
down 8
up 9
forward 2
down 4
forward 4
forward 9
up 9
down 4
up 7
down 6
up 2
up 7
down 5
down 6
down 8
down 1
forward 6
forward 6
forward 7
down 3
forward 3
forward 8
forward 1
forward 2
down 8
forward 6
down 6
forward 8
forward 3
forward 6
down 4
down 2
forward 4
forward 6
forward 8
down 3
down 3
down 4
up 1
forward 3
down 2
down 3
down 9
down 3
down 8
down 1
down 6
forward 5
down 5
down 7
up 3
forward 5
down 7
down 7
forward 6
down 6
up 6
forward 2
up 9
down 3
forward 3
forward 4
up 6
down 7
forward 1
up 8
forward 3
down 1
forward 6
forward 7
down 5
down 6
down 8
up 6
down 4
down 5
down 1
up 1
up 9
up 4
forward 2
down 5
down 7
forward 5
forward 2
up 1
down 7
up 6
forward 5
down 5
down 9
up 4
down 6
forward 8
down 5
forward 6
forward 1
forward 5
forward 4
down 2
down 7
up 7
down 9
down 7
up 4
down 3
up 9
forward 3
up 1
up 7
forward 4
forward 6
up 2
forward 2
forward 4
down 6
forward 4
forward 6
forward 9
forward 4
forward 8
up 9
up 4
forward 1
forward 3
down 5
down 4
up 6
up 2
forward 9
up 9
up 2
forward 6
down 5
up 7
forward 3
forward 4
down 5
up 8
forward 7
forward 3
up 5
down 7
down 6
forward 9
up 2
forward 5
down 2
down 9
forward 1
down 4
forward 3
up 9
down 2
up 5
down 8
forward 1
up 9
up 7
up 1
forward 7
forward 1
forward 7
down 2
up 6
forward 6
down 1
forward 1
down 7
down 9
forward 9
up 3
forward 3
down 1
forward 1
forward 9
down 7
forward 2
down 7
forward 2
forward 4
down 5
down 5
forward 5
down 9
down 4
forward 3
down 4
down 3
down 3
down 2
forward 1
up 8
forward 1
forward 5
forward 1
forward 2
forward 4
forward 6
forward 8
forward 7
down 5
up 6
forward 8
down 9
up 3
up 2
down 4
up 1
forward 6
up 6
forward 9
forward 3
down 3
down 5
forward 6
down 6
down 4
up 6
forward 4
up 8
down 4
down 8
down 3
down 1
down 6
down 7
down 8
down 2
down 5
forward 4
forward 6
forward 7
down 1
down 5
forward 9
down 6
forward 6
forward 7
forward 4
forward 2
forward 2
up 6
forward 9
up 6
down 1
forward 4
down 2
up 3
forward 5
up 1
forward 4
forward 4
up 4
down 7
down 5
up 4
forward 5
up 8
up 4
up 2
up 8
forward 6
down 9
down 8
down 4
down 4
up 9
forward 4
forward 5
forward 4
forward 9
down 7
down 4
down 3
down 7
forward 3
forward 1
down 1
forward 5
forward 6
down 1
forward 3
down 7
up 4
forward 4
forward 7
up 1
up 9
down 7
down 5
up 8
forward 3
forward 5
forward 3
down 6
down 1
down 9
up 9
forward 5
down 1
down 1
down 8
forward 8
up 2
down 1
down 2
down 6
down 3
forward 7
forward 1
down 4
up 9
down 7
down 6
down 9
forward 5
forward 4
forward 9
up 7
forward 5
down 6
forward 9
forward 2
forward 8
up 9
forward 2
down 8
up 8
down 8
down 8
forward 2
down 1
forward 5
down 4
up 2
forward 8
up 4
up 8
forward 4
forward 6
forward 6
forward 3
forward 5
forward 4
down 6
up 6
forward 7
up 3
down 1
down 1
down 9
forward 6
down 9
forward 2
down 7
down 2
down 5
forward 3
down 4
down 8
down 3
forward 6
up 9
forward 1
forward 4
forward 8
up 9
down 5
up 5
up 9
forward 6
up 2
forward 7
up 5
forward 8
forward 6
down 2
down 7
up 8
up 3
forward 4
forward 1
down 8
down 4
forward 6
forward 6
up 6
up 3
up 7
forward 6
up 2
down 8
forward 1
forward 3
down 3
forward 8
forward 5
forward 3
forward 9
down 6
forward 9
up 7
down 3
down 8
forward 4
down 9
up 8
up 1
forward 2
down 2
forward 1
down 8
forward 7
up 4
down 1
forward 8
down 2
forward 3
forward 9
down 7
up 4
up 2
forward 1
down 2
up 8
forward 4
down 1
forward 5
forward 1
down 5
forward 1
up 2
forward 6
down 5
down 8
down 3
down 2
forward 1
forward 5
down 8
down 1
forward 5
down 7
down 4
forward 5
down 1
down 1
forward 9
down 7
up 9
down 6
forward 4
up 8
forward 6
forward 1
up 6
forward 3
down 3
up 6
forward 2
down 2
forward 3
down 2
up 4
down 6
forward 4
down 6
down 4
up 2
down 2
up 5
up 2
down 9
down 5
forward 1
down 6
forward 4
forward 9
down 1
down 9
forward 3
forward 8
forward 9
down 4
down 1
up 1
up 7
down 5
down 3
down 2
down 8
forward 5
up 1
down 4
down 8
down 8
forward 1
down 5
forward 7
forward 9
forward 5
forward 2
down 9
up 1
down 6
down 5
forward 4
forward 3
down 4
down 3
down 8
forward 6
down 2
forward 7
down 7
forward 8
forward 1
forward 7
forward 8
forward 6
""".split('\n') if l ] ]
print(data)

has_sign = lambda n: n[0] in ('+', '-', )

def part1(data):
    """Answer part 1 of https://adventofcode.com/2021/day/2"""
    # print([ int(x) for x in data if not has_sign(x) ])
    # print([ int(x) for x in data if has_sign(x) ])
    return sum([ int(x) for x in data if not has_sign(x) ]) \
        * sum([ int(x) for x in data if has_sign(x) ])
print(part1(data))

def part2(data):
    """Answer part 2 of https://adventofcode.com/2021/day/2"""
    aim, depth = 0, 0
    for n in data:
        if has_sign(n):
            aim += int(n)
        else:
            depth += aim * int(n)
    return sum([ int(x) for x in data if not has_sign(x) ]) * depth
print(part2(data))


# AOC 2021 2
['8', '+9', '-4', '+8', '+3', '+3', '+2', '1', '4', '+5', '-7', '1', '+1', '+6', '+9', '+5', '5', '6', '4', '+2', '+8', '3', '+5', '6', '-7', '-2', '2', '4', '1', '-8', '-9', '+8', '-8', '-6', '-2', '+7', '-3', '8', '5', '+8', '+8', '5', '+3', '+4', '+5', '+2', '-7', '+1', '9', '9', '-6', '+5', '-1', '+8', '-1', '2', '+4', '+5', '+2', '-7', '9', '-8', '+3', '-6', '+2', '-2', '3', '-1', '-1', '9', '+3', '+5', '-7', '+1', '-5', '-5', '-7', '+9', '+3', '-3', '9', '7', '-9', '+3', '+2', '-8', '5', '9', '+5', '+2', '+9', '+6', '+6', '-3', '3', '-6', '9', '+3', '+2', '6', '+7', '+2', '+8', '2', '8', '4', '1', '-6', '2', '8', '5', '4', '-1', '+8', '-3', '8', '4', '-6', '+2', '6', '9', '+2', '-3', '8', '+6', '-4', '+7', '-3', '4', '+8', '5', '1', '+3', '1', '8', '+3', '4', '2', '-7', '6', '8', '6', '+5', '+2', '+8', '+2', '+9', '+5', '+3', '+8', '-1', '1', '-5', '-1', '-6', '-3', '-2', '5', '6', '+4', '-3', '-9', '+1', '1', '6', '+9', '5', '3', '2', '+7', '+5', '+8', '9', '4', '+2

<>:12: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:12: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:12: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:12: SyntaxWarning: "is" with a literal. Did you mean "=="?
<ipython-input-2-3536de7da9f3>:12: SyntaxWarning: "is" with a literal. Did you mean "=="?
  process = lambda t: ('' if t[0][0] is 'f' else '+' if t[0][0] is 'd' else '-') + t[1]
<ipython-input-2-3536de7da9f3>:12: SyntaxWarning: "is" with a literal. Did you mean "=="?
  process = lambda t: ('' if t[0][0] is 'f' else '+' if t[0][0] is 'd' else '-') + t[1]


---
## https://adventofcode.com/2021/day/3 &mdash; Binary Diagnostic

## Part 1

This part asks to find a 'gamma' value, which is a binary value whose bits represent the *majority* bit in the corresponding position of the input data, and an 'epsilon' value, which is the [ones' complement](https://en.wikipedia.org/wiki/Ones'_complement) of gamma.

### Strategy

- parse the data into a list of lists of bits.
- sum the bits in each bit position.
- create a single number whose bits are `1` if that bit position's sum is `> len(data)`, `0` otherwise.
- report the product of that number and its ones' complement.

## Part 2

This part asks to find an '$O_2$' rating and a '$CO_2$' rating by cycling through the input data until a single datum remains. Only the data that have the *majority* bit in the corresponding position of the input data are kept for the '$O_2$' rating and only the data that have the *minority* bit in the corresponding position of the input data are kept for the '$CO_2$' rating. Ties go the the 1s in the '$O_2$' rating and 0s in the 'C$O_2$' rating.

### Strategy

- parse the data into a list of lists of bits and combine the lists of bits into a single number.
- create a pair of lists for each bit position consisting of only values with a 1 in that bit posiiton and only values with a 0 in that bit position.
- find the *majority* list of data and save that for the '$O_2$' rating and the *minority* list of data and save that for the '$CO_2$' rating until a single datum remains in each rating.
- report the product of the two ratings.

Handling the tie cases (where there was neither a *majority* nor a *minority*) was tricky and I had to use the sample data to work it out correctly. This cannot be a one-liner, as the ratings depend on removing some data each cycle.

In [3]:
#!/usr/bin/env python3
#
# https://adventofcode.com/2021/
#
# AOC 2021 03
#
# aoc202103.py
#

print('# AOC 2021 3')

# Sample data for AOC 2021 3
data = [ [ int(b) for b in list(x) ] for x in """
00100
11110
10110
10111
10101
01111
00111
11100
10000
11001
00010
01010
""".split() ]

data = [ [ int(b) for b in list(x) ] for x in """
110000000001
010011111011
111000011110
110101011110
100000010100
000101101111
110100101000
011100010001
101001011011
011000001100
111101001011
010001100100
100101011010
111101110101
101001111100
010010010101
011100011000
010110011101
110001110101
001111000010
111011001011
111111111110
010000000100
001011111101
100111110101
011011110100
110101000100
111010001110
110101001011
011100100110
011100001001
101001111101
111111000010
010010001100
110010011001
010100010010
011010010000
101111000100
001010100101
100010010100
001000000110
000011110100
101101100001
111100000111
011010001110
010110001000
111101111010
001001010111
011001010011
000111000010
000010110001
101000010111
111010000100
111001110111
000000110001
011111000110
010110010111
110100001001
101100110110
100111111000
110000110000
110110111101
110011011100
010001010010
011011000101
000001100010
011001101001
000111111011
111000001101
110100000101
011000011011
100101100110
001001000001
111011011010
010101110110
100011100000
100000001011
110101111001
000101001000
110111111010
011001111111
101000000101
101000011111
010010000111
101101111100
101110100001
100111100101
101111001100
110101001111
011100001111
010000011110
000010111111
011110100101
100010010110
011101110011
000000010111
110111000110
100110010100
011110101111
101101000111
111111011100
110000100010
010110001010
011001000100
111001100011
111101110100
000011011100
110011010001
110011100110
100000011110
100100000010
001000100001
011000011111
001001101001
000100011100
100001010000
100000110010
111001101000
100011101101
000111000101
000011000101
111110001011
001111011101
110110010100
011010011011
111111111010
001010111111
101111101001
010000111100
111010110111
100100011000
111010010110
010100111100
101001010000
011100011011
100101001110
011100010110
111010011100
100110011001
100110000110
111010110010
011000010111
111101000110
000001000011
001011111011
011100000111
111011100100
101111110000
011111010010
001100111000
011001000010
100110100111
101000101110
110100101100
011101001100
111100100011
110101001101
101111000110
111010100100
100101010101
111011100000
011100101010
111111001111
010010100001
111001111111
101000110101
010001101010
000110110011
001010110011
110001101001
110110000011
100111110011
000100101100
111010101100
101011101100
010110000100
101001010101
000001010011
011110000000
101111110011
001010001000
110000010001
101010101100
011010111010
010100101000
101100011011
010010101011
110101110001
010101001101
011110011001
100000110011
010110110000
101100100010
010000110100
001000100101
100011100011
111000010110
000110011000
000011011000
010101001000
101000010100
111011111011
010110010001
100111100011
011011111100
001010011110
011110110101
111100101110
001001011110
010100010111
100011010001
110110000111
001000001101
001011110001
111001000011
101101011101
111000111010
111111110001
001100000000
110011011010
011010101001
011010101011
011010011100
100100111110
111001011110
001010001101
101101010100
100100110100
011000111111
101011010100
111010100110
001111010010
011001100000
011010010100
001100001010
101001001111
111011110110
100101100001
000100110010
101111001001
111001011000
100010001101
101101001010
011001110001
010110010110
000100010100
011011011100
000101101011
110010011110
010010011010
111110110010
000010001111
000010010011
000000111010
110001100011
000010000100
101011111000
110111001001
101111100000
110101111000
100010000011
000001111111
000110001110
000010000000
110110011110
000101101000
001101111011
011101101100
101100011101
110001010100
011010111000
011101101010
110010110101
100101100000
101001011100
100101001010
011110111011
111101111100
101000111001
111001110001
101100001111
100001100111
011001101000
111000100101
000000001011
110011100011
111010001011
111100001011
111101101001
111001101110
000110100101
000111100001
101101101101
100000000011
001100011111
101101111110
101010111000
010100000001
000110011011
000100011000
000001110110
100111101001
001111011110
000010011110
101001000010
101001011111
110011010010
101100010110
101110001111
000111110011
011011101010
101010011010
101100111001
111111000000
101100110101
110100101101
010000100111
110011000001
010001001000
000111110000
100101010110
001010001001
100100111010
001010010110
010111010010
010010100000
010110001011
011001101011
110001000111
111001001000
001101001101
101000111100
100011101001
100011111010
100000010101
110010100110
001000110101
111100011011
011001101010
101011010000
011111001110
010011010111
101100111000
011111011010
110110001010
100010111110
100001001001
000001011101
110001100101
011001100111
111001101010
001000011001
000011101000
100100001001
110001111000
010111000101
000111001101
001110100010
010110101011
100111110001
110000001001
011100111001
100111010000
101111010000
001110110100
010111001010
000100101111
100000010010
110110111000
111010010001
001101011001
001011011100
001001111000
011101001011
001101110111
111111001000
011001001001
011100100111
011011011011
101010100111
010101011100
100000010110
101101110010
110111010001
010000100110
010011100011
101111000011
011110101011
111101110010
001100101111
111101011101
001010010001
001110111110
010101000010
111010101101
100001111000
111100001111
011010100000
110001011110
010000100001
110001001001
100101101011
000010111010
000110101101
100110011000
100100110111
100010000001
001110010000
010001101110
111001000000
100010001011
111010111010
000100001101
010101101000
001101111010
111100110100
010010111100
011010010110
000001100000
111111111001
101001101111
100011000110
001100010110
000110111110
000001010001
101010000011
000110001011
000110101011
000011100111
101011110110
110100000100
111000101101
000100100010
011011111001
000010110000
111010101010
011000001101
101111110001
110101000001
000000110011
000100111111
111001100100
000011100010
001100110001
111000010000
001011000000
111000011011
100001101001
111100001000
001011100000
111101101000
100100101111
110110001111
011110011110
010011011100
110110010001
011001000111
101111110101
011101011111
010100100010
101101010110
010001111111
111110111000
001010110101
111000111000
110101011010
011001110110
011101011001
010100110111
101101111111
111111101011
111010101111
010000111011
111010000111
000100111010
010011000100
101010001011
010111110110
100001100011
111001110100
011000100101
000011111111
100101010111
011000000110
001011001000
011100000000
011110011100
100101001001
000001110000
010110011110
001111000101
100101110001
110111100111
001010010000
110011101011
011111001011
011010110000
011011010110
000111100011
110000001010
000010111101
100100101001
010100000100
001101111100
111000100010
010110000001
111010111101
000001010100
100100100110
110011000000
000111101000
000110101110
011101011010
001100110011
101011111001
001101001011
100110011100
110001111001
101101001100
110000110011
110000111110
000010101010
010001111010
001100001001
111000011100
101011000001
101000011110
111001010101
010001100001
011001111001
100010100001
111101011110
111110100001
001011000011
100010110111
010100101110
110001110011
111001011111
001101000010
000001111110
010011101100
111010110000
110001100001
101001111001
000101100001
111110110110
010010001110
001010001111
001010001100
111000000010
000101000011
010110000101
011111110111
000000000111
011101100000
000011110010
010110100100
111011000101
010111011001
111111100011
010111001011
101110111110
100001110110
111110111100
110011000110
101100110111
001000011111
000000111111
010100010000
100000001111
100010101000
110110001101
010101100101
111110101111
010010110011
000101011000
110001110100
001111111010
110100111110
111010111111
110100110101
100000111111
011011101110
000001101000
110011100010
111011110101
111100000010
101000001110
100101101001
101110010111
000001100001
000101001111
000101101010
101011001010
001100001100
111010110110
101100000100
010011010011
001000100111
001110100001
010101011101
101011111101
111110110011
001101100000
101111000010
001110010101
000111111100
000110000100
000101111001
000011111000
000010000110
001010011000
111111101001
011000001111
111010100001
111110001111
101110010110
010011000011
110001000010
110111100110
010100000111
000011000010
000000010010
100111111011
001011111000
110010001100
000111011101
000101001010
001100110101
110110110000
110111100101
000000111000
100011100111
100100111101
011011001011
000100101000
111101010101
010011111101
110100110100
110011111011
100111011011
101000100100
011000001110
101000001000
110101011001
100110111100
110010000001
000111000011
010001001100
101001000100
100000101101
011011111010
101000100010
011001011111
011001000001
001100011010
100011011111
110011010111
111000101000
001001110110
101010101011
001110110110
011111010011
100111111010
001111101110
110010101000
000001111000
100110111101
110110001001
111000011111
011111000111
111100011000
101001000110
110010000010
000100111000
001000101000
011100100001
101101101010
110110111011
001011101100
110111110111
011000111101
110000111000
101010000101
111010011011
111011101010
101100101100
000110101000
110011111001
010111011000
100101111101
101110110000
100001111010
110101100001
100010011110
011000100100
101110101111
111011011110
000110110100
010100001100
101001101000
001001000010
100110001001
001011111100
100011111100
011100001011
001100000100
100111001011
011101000101
011110000100
011011011101
001001011010
110110011101
000000001100
010111100101
111011011101
000100101110
001100011001
110001001110
101010100001
011101100011
100000111000
111111100111
001000100011
110000000011
101001010010
111101010100
111101111110
001110100100
111100100010
010000100101
010100001101
011010011110
001110000110
101000000001
010111111000
111111011011
110110101010
000000110110
111001111010
001110110010
111011010110
001100100010
011111000100
000111010000
100101110111
001011110011
111110011011
111001010011
000110011100
010111000111
101000001100
010101111011
100001011011
010100110101
010000000000
110010011100
110101001110
111010111110
101101110101
011010101111
101010011110
010111110100
010100110011
110110001100
001011110100
010001000000
100011010110
100111000000
010111100000
100010100110
001100101101
010111100110
101101000100
101110011001
011011100101
101101101111
110010100000
100100100010
001100110000
110110011100
000010000001
101001101001
001001100110
000101100011
111101000111
000110000011
011011110000
110010000011
010111000001
101101011001
101100001001
101100010101
011010011111
010100011100
100111100111
101110100110
101011010101
110110101111
010001010101
000010001100
001110000001
110011111100
000001111001
001000111101
010011110001
110100010010
100000100101
100100000011
111110010000
110010001001
011111100001
010011011001
111110110001
000011010010
011101101011
110011100001
000110101111
001111101101
110101110000
001000011101
111111001100
110101101111
000110111000
101100010100
011101100100
111000101010
110001001011
100010001111
001101000111
011000010000
110010110001
111100100001
110111110110
000010000011
100001111110
111001001001
001011011101
000100011101
001100100111
000011010001
111111001110
001111111101
110001110001
101010011101
110010010101
001011010101
111110010011
011001101110
101000011100
110100011111
000001001111
100001111001
001101110110
010111111100
111101011111
001111110001
101001101110
100100100111
100010011100
010110011111
100010111011
111011110010
111010010011
111001111100
011100010011
001010100100
111001100101
111100011001
101110001011
100000011111
010010011000
100001000011
001001111101
010111001100
100101011101
110011101010
010010101110
100011001101
101100101001
011110010000
101000011010
110100010101
010110111110
011110010111
100000001000
101000011000
000111100111
011001100110
001010011001
011011101011
101000000110
000100010010
100100101011
000101011111
010000110101
000000011010
111101111001
111011011111
010000001001
100101100011
000111011001
111011011011
000011011001
111101011001
001000001100
000110001000
110111010010
101100101011
111101110001
110101101101
100111001110
110010111110
000010001010
101101000001
000011101111
110000100100
010001101001
000000001110
001110011101
000100101011
110100111100
011000100111
001110101101
010101100100
101110100000
100110001010
101110010000
000111111010
011011110101
001111110100
000111110110
101011111110
100010110000
100100100101
101000001101
010011111111
001110111001
101010110110
110010011011
110001001000
101110100011
101001011000
100111101110
100111000111
001000111100
010101111010
100010100101
110011010011
100100000111
111010101001
110001001101
011000101001
000110100001
100011111110
001100011000
110100010000
001010110100
000100000110
001011101010
001100100110
011111101011
000101111101
001110110101
110000001111
001010000011
110101001000
001000010001
111011101011
001001011101
000001000000
000110010101
100110101010
101010000111
110101101110
100000010011
001110001011
011110000010
100000100010
111111101100
011010000011
001101001110
011100001000
000001001110
000111001000
100100011010
010000010100
111110001100
111100101111
101000100101
011100101110
000011101101
000100100100
011111111001
000100110011
001011001011
110101100000
101111111011
001101111101
100110100011
""".split() ]
print(data)

bs = len(data[0])       # the number of bits in each datum

def part1(data):
    """Answer part 1 of https://adventofcode.com/2021/day/3"""
    # print([ sum(x) for x in [ [ n[i] for n in data ] for i in range(bs) ] ])
    gamma = int(''.join([ '1' if s > len(data)  / 2 else '0'
        for s in [ sum(x)
            for x in [ [ n[i] for n in data ] for i in range(bs) ] ] ]), 2)
    return gamma * (gamma ^ ((1 << bs) - 1))
print(part1(data))

# Join the bits of a bs-length list into a single number.
join_bits = lambda n: sum([ b << (bs - 1 - i) for b, i in zip(n, range(bs)) ])

def keep(data, bit):
    """Return two lists, one with 1s in bit's position and one with 0s."""
    return \
        [ p for p in data if p & 1 << bit ], \
        [ p for p in data if not p & 1 << bit ]

def part2(data):
    """Answer part 2 of https://adventofcode.com/2021/day/3"""
    o2 = co2 = [ join_bits(n) for n in data ]
    for i in range(bs):
        if len(o2) > 1:
            has, hasnt = keep(o2, bs - 1 - i)
            o2 = has if len(hasnt) <= len(has) else hasnt
        if len(co2) > 1:
            has, hasnt = keep(co2, bs - 1 - i)
            co2 = hasnt if len(hasnt) <= len(has) else has
    # print(o2, co2)
    return o2[0] * co2[0]
print(part2(data))


# AOC 2021 3
[[1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], [0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1], [1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0], [1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0], [1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0], [0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1], [1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0], [0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1], [1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1], [0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0], [1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1], [0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0], [1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0], [1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1], [1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0], [0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1], [0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0], [0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1], [1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1], [0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0], [1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0], [0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0], [0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1], [1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1], [0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0]

---
## https://adventofcode.com/2021/day/4 &mdash; Giant Squid

## Utilities

For both parts, the data must be parsed into `order` and `boards` and two utliity functions, `update` and `bingo` facilitate the solutions.

- parse the `order` from the first line of input data.
- parse the `data` from the remaining lines of input data into lists of numbers for each line.
- create `boards` from 2D lists of every 5 elements of `data`.
- define an `update` function that updates any element of the board matching a nnumber to 0.
- create a `bingo` function that checks for any all-zero rows in a board or the transpose of a board.

## Part 1

This part asks to find the *first* BINGO from `boards` given numbers in `order`.

### Strategy

- loop through the numbers in `order` to find the first board with BINGO.
- report the product of the BINGO number and the sum of the remaining numbers on the first winning board.

## Part 2

This part asks to find the *last* BINGO from `boards` given numbers in `order`.

### Strategy

- loop through the numbers in `order` to find boards with BINGO.
- maintain a set of board indexes for winning boards until the last board wins.
- report the product of the BINGO number and the sum of the remaining numbers on the last winning board.

*Part 2* should have been an easy modification of the *Part 1*, but I originally (and mistakenly) used [`del`](https://docs.python.org/3/tutorial/datastructures.html#the-del-statement) to remove winning boards from `boards`, while at the same time remembering the index of the current board. Using `del` in the middle of a `for i, b in enumerate(boards):` loop can often lead to problems keeping track.

In [4]:
#!/usr/bin/env python3
#
# https://adventofcode.com/2021/
#
# AOC 2021 04
#
# aoc202104.py
#

print('# AOC 2021 4')

order = [ int(x) for x in """
17,25,31,22,79,72,58,47,62,50,30,91,11,63,66,83,33,75,44,18,56,81,32,46,93,13,41,65,14,95,19,38,8,35,52,7,12,70,84,23,4,42,90,60,6,40,97,16,27,86,5,48,54,64,29,67,26,89,99,53,34,0,57,3,92,37,59,9,21,78,51,80,73,82,76,28,88,96,45,69,98,1,2,71,68,49,36,15,55,39,87,77,74,94,61,85,10,43,20,24
""".strip().split(',') ]
print(order)

data = [ [ int(n) for n in x.split() ] for x in """
36 11 70 77 80
63  3 56 75 28
89 91 27 33 82
53 79 52 96 32
58 14 78 65 38

26 15 50 56  2
20 27 42 11 16
93 44 38 28 68
66 88 78 81 77
91 46 55 86  6

46 53 14 17 75
71  4 70 99 48
65 96 68 80 72
 3 97 62 37 88
82 35 36 23 39

17  1 61 77  5
74 60 12 24 48
34 19 68 65 86
44 59 38 40 95
67 64  9 52 27

44 60  8 81  3
30 71 85 23 99
68 88 38 97 48
27 70 63 28 12
67 57 34 13 93

52 82 88 61  0
68 21 59 75 71
86 36 39 20 48
50 40 19  6 34
93 26 14 41 49

74 18 93 59 77
14 45 57 61 92
10 78 42 63 52
87  3  0 62 20
25 64 48 22 96

11 73 88 47 30
10  6  5 25 67
89 41 62 94 85
45 99 58  7 57
77 19 66 43 48

94 47 45 73 44
22  8 84 79  6
14 58 26 92  5
40 48 42 25  2
37 76 18 80 74

15  3 89 77 98
13 99 10 97 59
18 96 64 47 37
68 92 90 56 11
76 81 12 91 69

82 97 69 47 10
51 12 41 23 45
71  6 67 80 46
31 70 40  9 42
27  1 17 25 74

 2 77  1 37 29
50  8 87 12 76
74 88 48 60 79
41 35 92 33 34
45 52 75 24 28

97 41 49 40 96
84 54 12 24 45
39  1 17 85 52
 3 29 67 33  9
50  7 47 48 81

76 77 15 84 71
41  7 32 29 62
30 87 14 10 48
98 22 96 45  9
66 91 83 21 55

20 42 33  9 91
11 71 64 83 61
82 54 67 38 60
77 57 81 78 98
18  1 27 55 87

 7 13 36 93 47
45 25 44 58 72
74 80 52 24 15
64 43 96 42 20
82 10 73 46 57

40 36 86 87 76
16 11 70 81 25
55 31 83 72 88
57 33 44 58  5
64 15 19 67 53

61 95 27  3 20
85  1 76 25 80
12 78 98 36  4
86 90 19 64 38
22 65 96 87 68

11 52 17 89 64
90 35 94 81 62
65 30 51 67 85
40 32 37 78 74
97 27 10 96 91

45 14 34 23 49
79 21 90 56  4
25 44 92  0 31
16 24 88 48 84
15 63 50 76 52

42 31 84 64 24
34 58 53  3 73
56 35 33 89 41
16  8 85 92  6
40 19 51 14  4

46 61 74 54 30
35 79 63  8 10
64 38 71 23 98
59 72 83 70 50
91 77 69 55 84

93 40  9 49 66
45 35 71 65 61
 5 14 20 83 10
84 47 53 96 97
 6 30 77 52 67

19 78 68 18 86
94 82 16 21 95
71 63 22  3 72
91 27 59 49 11
53 69 46 52 36

44 94 30 21 22
25 81 60 74 99
32 62 10 79 39
28 63 96 90 55
58 85 93 36 76

90 71 76 51 87
26 64  2 49 19
54 47 32 93 92
88 69 24 60 94
42 73 67 56 23

 8 22 47 12 10
59 31 99 41 17
60 23 37  0 57
21 11 77 79 91
50 34 16 72 15

27 11 12  7 83
 9 50 47 84 35
75 99 97 78 53
20 70 51 76 44
73 90  0 62 58

60 49  0 40  8
74 73 95  3 90
27 39 10 19 35
 6 50 16 72 82
71 36 11 99 52

15 97  9 75 37
33 65 30 18 10
93 14 77 80 36
82 35 88 12 21
40 22 84 49 81

18 74 94 79 17
39 51 98  8 99
33 63 50 65 40
29 55 75 91 90
24 54 87 97 48

44 81 21 77 10
 8 52 54  5 88
37 29 59 43 34
70 30 86 31 56
35 40 13  4 45

12 84 38 37 54
72 69 86 90 91
31 45 15 52 59
51  9  1 34 63
53 29 20  3 56

43 46 86 35 73
94 87 90 39 95
25  0 17 84 54
22 27 76 26 63
91 68  2 14 37

67 63 20 21 27
98 78  4 51 82
74 86 46 12 56
57 94 81 33 11
29 13 83 37 40

11 87 71 33 64
52 97 91 79 24
54 37 72 55  0
21 67 80 51 10
 6 35 49 68 18

27  7 95 81 93
99 97 67 65 72
59 92 32 43 50
56 74 42 75 41
13 36 79 78 23

94  9 47 30 85
 5 80 86 55 11
44 54 17 74 36
22 98 84  7 88
52 34  0 97 73

10 70 26 89 28
98 41 77 64 38
46  8 22  5 29
71 11 57 20 31
97 90 50 95 51

26 23 73 25 11
80 97 68  7 27
43 72 47 49 93
 2 21 50 82 66
34 81 90 18 48

79 61 33 42 50
28 44 30 99 88
57 14 35 60 31
15 27 34 13 19
72 71 64 76 21

80 73 78 18 28
79  1 76 42 58
90 85 48 81 61
52 44 51 53 39
63 98 25 24 70

22 63 35 31 11
55 48 85 65 68
49 52 40 74 97
37 69 98 79 67
 2 91  7 41 16

28 43 21 66 67
56 88 77 37 41
63 55 79 94 62
61 60 23 45 87
58 12 99 47 73

 2 21 26 27 42
65 47 71 85  4
76 13 40 56 29
50 53 28 97 90
17  1 14 74 48

 4 98 39 40 11
90 88 87 86 13
92 80 95 99 51
54 18 70 34 38
75 37 28 78 46

 7 11 73 51 47
26 69 61 91 57
55 48 14 94 82
19 37 15 54 65
25 43 90 16 81

50 30 78  7 61
99 32 91 13 21
 5 27 11 92 73
71 54 29 20 12
 8 75 65  9 39

84 13 22 90  7
64  6 21  3 23
 8 72 67 61 62
44 32 20 25 45
57 81 49 98 77

12  9 53 94  8
85  0 70 35 82
90 67 48 79 54
26 88 51  2 46
78 63 61 36 29

86 27 13 55 37
67 61 39  1 66
79 97 40 42  7
64 85 33 31 46
34 65 24 54 50

 8 58 80 35 47
31 66 45 36 54
 9 27 64 16  5
34 14 10 57 85
40 79 60 61  3

49 31  2 25  9
34 65 14 54 61
88 28 45  3 76
 7 94 24  1 86
29 66 70 96 50

72 35 31 84 37
 8 86  4 17 46
39 80 43 11  3
26 76 44 20 95
71  5 51 65 32

98 33  8 41 75
94 49 27 95 72
44 18 82  0 90
86 74  2 59 45
20 57 25 87 42

64 72 33 23 96
70  2 68 97 69
59 49 19 35 10
87 92 85 34 90
56 95 88 66 94

97 23 75 47 43
32 19 69 29 94
45 38 61  4 40
26 82 30 16  2
95 76  5 67 83

 4 75 91 82 23
52 38 47 49 46
97 17  6 90 59
 8 16 12 73 85
88 64 32 99 11

 2 61 15  7 37
45 57 43 46 92
76 99 34 14  9
51  8 18 81 50
19 47 97 29 26

70 61 79 67 17
25 69 78  4 24
87 11 95 68 91
51 89 39 66 80
29 98 43 64 86

95 40 97 32 48
44  0 64 45 83
34 88 20 86 31
84 16 96 78 65
 2 81 72 69 43

98 88 93  3 10
53 72 68 81 62
56 38 36 87 27
29 99 76 28 23
16 59 71 21 92

95 17  8  7 46
71 61  5 90 38
63 65 25 45 22
11 16 93 34 14
55 56 36 91 49

61 36  9 12 40
60 51 57 41 87
35 97 75 20 21
74 34 19 14 95
84 68 98 62  0

 3  5 57 40 61
30 79 94 86 84
20  9 13 27 34
59 98 17 12 14
28 73 18 97 75

 3 86 99 48  2
65 97 26 82 79
51 16 70  7 89
22 83 50 78 32
31 72 28 21 60

67 27 78 91 14
21  4 20 42 62
52  3 36 17 18
 6 40 46 39 63
80 75 54 96 99

89 77 18 59 99
 5 55 14 52 12
91 70 85 16 24
72 42 80 81 76
46 95 37 23 11

48 66 23 26 15
16 76 81 10 49
57 74 68 67 98
43 31 53 94 86
80 71 85  0 33

95 69 45 80 35
38 88 62 28  1
44 10 91 39 31
74 81 64 63 98
33 13 89 53 56

85 22 55 95 44
93  9 58 11 27
15 40  2 28 87
 5 84 77 48 42
94 18 16 12 79

69 74 75 16 77
45 56 60 81 68
33 73 49 14 92
94 51 24 38 15
90 10 89  6 32

15 86 73 20 71
 7 33 47 36 96
31 55 87 22 14
13 35  8 77 89
 3 37 98 52 34

92 79 95 74 85
19  3  5 73 67
93 41 81 78 77
48 88 57 82 15
36 38 42  4 69

87 36 38 65 91
18 47 41 66 35
 0 63 59 54 10
44  1 37 81 48
75 96 42  4 25

14 19 63  8 36
35 38 84 66 42
99  7 70 74  6
 4 12 86 65 22
46 40 60 31 80

38 29 26 65 85
21  6 15 77 14
61 25 86 12 35
71 67 74 59 42
46 52 30 19 93

10 61 18 67 26
15 27 20 62 38
58 24 28 45 90
98 39 59  3 92
64 35 60 68 19

34 44 11 25 56
 2 63  5 94 76
72 92  0 27 84
60  8 80 48 90
23  7 75 70 47

78 18 19 34 39
31 66 95  9 36
64 99 57 94 75
29 97 51 45 47
93 79 23 84 24

72 23 78 90 21
41 67 31  4 57
34 58 50 46 74
55 37 81 63 45
85  8 48 28 12

18 30 28 50 81
67 47 41 45 59
51 14 92  6 68
 8 46 69 84 13
93 25 58 26 75

76 16 78 36 18
 3  7 28 73 41
34 97 42 23  8
 9 67 49 83 64
81  5 29 85 79

 3 35 80 53  5
91 96 77 52 69
44 32  4 60 26
41 13 28 39 64
73 27 34 71 92

72  4 77 80 29
32 36 70 47 79
96 56 69  2 90
13 20 24 81 67
23 25 83 89 91

32 46 88 81 75
 5 98 15 72 31
56 89 90 21 16
37  2 82 93 18
63 52 49 19 41

52 51 76 91 33
29 37 32 43 42
27 34 21 72 87
62 64  8 73 41
23 46 67 96 85

82 19  5 88 54
71 27 92 48 16
25 96 40 56 37
41 11 26 58 95
63 17  1  0 24

46 36 85 78 32
55 50 94  9 57
 0 20 24 68 28
52 22  3 84 17
16  2  1 66 69

14 87 83 79 36
 9 64 77 49 24
25 92  5 62 91
73 33 74  6 65
39  2 59 71 50

99  0 48 98 45
50 27 92  8 73
91 80 54 42 57
18 78 55 19 36
76 28 53  6  7

29 68 27 95 47
40 32 79 60  2
44 53 57  6 25
41 56 66 30 77
26 13 83 23 51

 7 76 59 44 22
81 15 48  8 47
77 79 32 61 39
65 29 95 35 45
 1  6 13  9  3

 3 52 93 20 70
49 80 40 66 53
 2 71 41  1 13
44 24 15 83  0
14 17  7 56 63

77 12 99 19 21
62 63 98 56 66
28  4 22 68 55
49 65 96 84 57
41 74 46 60 53

64  7 16  8 38
55 68 21 43 99
92  0 79 35 96
75 28 51 87 53
57 73 84 18  3

95 90 17 40 51
46 12 23 91 38
80 10 68  9 93
65 69 49 27 66
94  4 39 97 31

 4 64 39  3 33
26 88 10 96 54
21 48  7 78 50
22 90 16 15 72
92  2 71 70 68

42 26 72 54 41
97 94 80 47 63
19 24 90 78  6
48 34 50 98 89
33 81 66 38 10

65 24 23  1 19
54 35 76 71 49
10 75 99 91 97
21 78 17 18 81
 3 48 72  7 96
""".split('\n') if x ]
print(data)

boards = list()
for i in range(0, len(data), 5):
    boards.append(data[i: i + 5])
print(boards)

def bingo(board, rc=[0, 0, 0, 0, 0,]):
    """Return True if board has BINGO, false otherwise."""
    # Check each row of board and each row of board transpose.
    return any(row == rc for row in board) \
        or any(col == rc for col in [ [ board[c][r] for c in range(5) ] for r in range(5) ])

def update(board, n):
    """Update board w/ zeroed-out n, if it exists in board."""
    for r in range(5):
        for c in range(5):
            if n == board[r][c]:
                board[r][c] = 0
def part1(data):
    """Answer part 1 of https://adventofcode.com/2021/day/4"""
    for n in order:
        for b in boards:
            update(b, n)
            if bingo(b):
                return n * sum([ sum(r) for r in b ])
print(part1(data))

def part2(data):
    """Answer part 2 of https://adventofcode.com/2021/day/4"""
    found = set()
    for n in order:
        for i, b in enumerate(boards):
            update(b, n)
            if bingo(b):
                if i not in found:
                    found.add(i)
                if len(found) == len(boards):
                    return n * sum([ sum(r) for r in b ])
print(part2(data))


# AOC 2021 4
[17, 25, 31, 22, 79, 72, 58, 47, 62, 50, 30, 91, 11, 63, 66, 83, 33, 75, 44, 18, 56, 81, 32, 46, 93, 13, 41, 65, 14, 95, 19, 38, 8, 35, 52, 7, 12, 70, 84, 23, 4, 42, 90, 60, 6, 40, 97, 16, 27, 86, 5, 48, 54, 64, 29, 67, 26, 89, 99, 53, 34, 0, 57, 3, 92, 37, 59, 9, 21, 78, 51, 80, 73, 82, 76, 28, 88, 96, 45, 69, 98, 1, 2, 71, 68, 49, 36, 15, 55, 39, 87, 77, 74, 94, 61, 85, 10, 43, 20, 24]
[[36, 11, 70, 77, 80], [63, 3, 56, 75, 28], [89, 91, 27, 33, 82], [53, 79, 52, 96, 32], [58, 14, 78, 65, 38], [26, 15, 50, 56, 2], [20, 27, 42, 11, 16], [93, 44, 38, 28, 68], [66, 88, 78, 81, 77], [91, 46, 55, 86, 6], [46, 53, 14, 17, 75], [71, 4, 70, 99, 48], [65, 96, 68, 80, 72], [3, 97, 62, 37, 88], [82, 35, 36, 23, 39], [17, 1, 61, 77, 5], [74, 60, 12, 24, 48], [34, 19, 68, 65, 86], [44, 59, 38, 40, 95], [67, 64, 9, 52, 27], [44, 60, 8, 81, 3], [30, 71, 85, 23, 99], [68, 88, 38, 97, 48], [27, 70, 63, 28, 12], [67, 57, 34, 13, 93], [52, 82, 88, 61, 0], [68, 21, 59, 75, 71], [86, 36, 39,

---
## https://adventofcode.com/2021/day/5 &mdash; Hydrothermal Venture

## Utilities

For both parts, the strategy for finding the `overlap` is the same:

- parse the data into 2-tuples of 2-tuples representing the end points of line segments.
- create a 1000 &times; 1000 `grid` of zeros.
- create ranges of *x* extents and *y* extents from the end points, with negative steps if sloping down or to the left.
- if the line is vertical, copy the constant x value to match the number of y values or if the line is horizontal, copy the constant y value to match the number of x values.
- `zip` the ranges into coordinate pairs and increment the values at each coordinate pair in the `grid`.
- report the number of entries in the `grid` whose value is greater than 1.

## Part 1

This part asks to find overlapping latice points for horizontal and vertical line segments defined by their endpoints.

### Strategy

- find the `overlap` for only vertical and horizontal line segments.

## Part 2

This part asks to find overlapping latice points for horizontal, vertical, *and diagonal* line segments defined by their endpoints.

### Strategy

- find the `overlap` for *all* line segments.

In [5]:
#!/usr/bin/env python3
#
# https://adventofcode.com/2021/
#
# AOC 2021 05
#
# aoc202105.py
#

print('# AOC 2021 5')

make = lambda s: ( int(s.split(',')[0]), int(s.split(',')[1]), )

data = [ ( make(f), make(t), ) for f, t in [ x.split(' -> ') for x in """
491,392 -> 34,392
337,52 -> 485,52
256,605 -> 256,959
889,142 -> 153,878
189,59 -> 512,382
399,193 -> 598,193
578,370 -> 795,153
79,450 -> 569,450
565,444 -> 270,149
39,28 -> 39,846
114,353 -> 114,383
356,61 -> 356,327
140,132 -> 515,132
361,848 -> 361,527
466,257 -> 466,784
818,397 -> 818,14
693,554 -> 693,984
171,290 -> 171,655
989,889 -> 170,70
527,855 -> 527,549
209,355 -> 486,355
800,430 -> 291,939
980,38 -> 31,987
964,559 -> 964,799
491,612 -> 930,173
57,977 -> 958,76
149,465 -> 349,465
512,624 -> 629,507
460,943 -> 460,441
988,29 -> 988,968
104,337 -> 441,337
939,48 -> 939,546
941,904 -> 498,461
850,972 -> 649,771
840,901 -> 23,84
231,790 -> 231,873
230,668 -> 840,58
410,922 -> 435,897
341,337 -> 341,406
264,752 -> 258,752
457,969 -> 457,757
465,42 -> 465,350
748,783 -> 502,783
461,930 -> 461,142
392,265 -> 215,265
417,805 -> 417,231
825,870 -> 60,105
524,167 -> 703,346
963,829 -> 308,174
730,361 -> 730,252
61,373 -> 61,593
873,893 -> 132,152
820,719 -> 417,719
142,238 -> 212,168
142,653 -> 676,119
392,955 -> 392,453
368,385 -> 414,385
464,762 -> 592,762
542,168 -> 542,789
622,693 -> 166,237
477,290 -> 792,290
731,56 -> 731,677
516,77 -> 326,77
595,973 -> 779,973
68,487 -> 128,487
389,738 -> 762,738
721,13 -> 827,119
797,625 -> 347,625
75,67 -> 75,458
931,142 -> 219,854
422,835 -> 980,835
278,565 -> 753,565
225,970 -> 806,389
791,725 -> 691,725
924,975 -> 18,69
326,763 -> 969,120
663,895 -> 663,559
940,965 -> 142,167
146,425 -> 791,425
832,968 -> 272,408
494,804 -> 694,804
23,25 -> 900,902
621,163 -> 894,163
587,605 -> 587,716
41,931 -> 383,589
888,530 -> 341,530
292,801 -> 292,567
537,213 -> 245,213
513,84 -> 527,84
623,516 -> 623,128
549,729 -> 509,729
576,232 -> 869,232
513,847 -> 433,847
536,612 -> 434,612
608,377 -> 33,952
137,762 -> 424,475
329,286 -> 584,541
493,296 -> 493,316
160,343 -> 189,343
477,929 -> 976,430
695,607 -> 557,607
745,322 -> 28,322
777,73 -> 76,774
163,723 -> 163,816
30,549 -> 63,516
163,914 -> 898,179
603,823 -> 603,78
498,616 -> 886,228
229,591 -> 341,591
742,841 -> 343,841
720,808 -> 934,808
985,48 -> 48,985
368,859 -> 178,859
506,30 -> 144,30
19,110 -> 19,750
293,689 -> 293,294
13,462 -> 980,462
536,963 -> 346,773
836,471 -> 462,471
506,952 -> 489,952
830,15 -> 461,15
392,378 -> 237,378
295,48 -> 295,825
264,679 -> 264,602
487,582 -> 487,116
832,677 -> 788,677
469,770 -> 211,512
400,773 -> 394,773
262,836 -> 262,454
51,17 -> 969,935
483,525 -> 838,880
71,124 -> 164,31
103,226 -> 912,226
785,169 -> 785,454
858,825 -> 176,143
248,960 -> 427,781
255,37 -> 767,37
832,149 -> 506,149
256,246 -> 86,246
447,448 -> 765,448
654,159 -> 654,158
120,500 -> 120,341
200,19 -> 839,658
451,251 -> 763,563
931,75 -> 931,312
69,404 -> 311,646
31,678 -> 31,231
410,307 -> 410,236
988,976 -> 387,375
654,402 -> 738,486
30,942 -> 942,30
115,652 -> 98,669
405,764 -> 375,734
88,759 -> 125,759
636,835 -> 722,835
300,60 -> 126,60
159,225 -> 159,319
934,188 -> 934,74
46,822 -> 708,160
605,612 -> 605,463
200,281 -> 536,617
392,11 -> 79,324
917,126 -> 258,785
803,143 -> 803,180
116,556 -> 651,556
922,222 -> 468,676
266,782 -> 896,782
733,448 -> 764,448
915,75 -> 305,685
150,243 -> 842,243
485,641 -> 963,641
965,206 -> 965,275
78,868 -> 748,198
37,947 -> 859,947
429,289 -> 429,48
378,261 -> 378,624
768,494 -> 768,782
702,566 -> 113,566
290,148 -> 913,771
806,931 -> 849,931
725,970 -> 299,970
38,565 -> 740,565
262,730 -> 973,730
826,376 -> 826,97
318,576 -> 318,227
159,868 -> 448,868
344,256 -> 344,615
824,188 -> 588,424
505,843 -> 897,843
293,348 -> 293,488
433,833 -> 165,565
56,471 -> 169,471
77,896 -> 914,59
405,904 -> 405,174
274,364 -> 274,88
785,704 -> 538,704
877,389 -> 681,389
790,936 -> 327,936
89,143 -> 755,809
721,450 -> 721,406
253,664 -> 811,664
881,143 -> 97,927
205,738 -> 645,738
869,951 -> 282,364
374,697 -> 374,592
251,989 -> 251,977
521,187 -> 885,187
536,401 -> 536,38
636,840 -> 636,873
695,333 -> 52,976
790,757 -> 790,358
314,765 -> 882,765
880,439 -> 127,439
266,848 -> 810,304
802,419 -> 802,936
554,67 -> 554,956
311,379 -> 685,753
183,544 -> 305,544
857,341 -> 407,791
306,559 -> 727,980
184,477 -> 509,152
934,174 -> 934,154
28,12 -> 28,968
418,984 -> 112,678
788,89 -> 837,89
229,425 -> 192,462
714,701 -> 424,411
198,313 -> 156,355
142,742 -> 215,742
15,639 -> 15,787
573,396 -> 462,396
954,977 -> 76,99
645,448 -> 652,448
958,822 -> 376,240
47,359 -> 212,194
524,366 -> 524,916
100,977 -> 501,576
932,148 -> 115,965
854,120 -> 421,553
318,630 -> 318,964
196,31 -> 874,709
812,826 -> 812,679
111,890 -> 897,104
46,35 -> 972,35
40,842 -> 40,835
390,510 -> 98,510
832,57 -> 124,765
422,331 -> 422,44
696,837 -> 696,555
849,571 -> 849,679
598,143 -> 598,261
670,745 -> 670,757
660,390 -> 660,912
960,578 -> 960,253
123,343 -> 123,28
643,199 -> 969,199
66,642 -> 669,39
776,30 -> 776,173
595,951 -> 84,951
908,183 -> 724,367
330,332 -> 330,455
954,955 -> 188,955
981,269 -> 90,269
235,579 -> 513,579
217,25 -> 217,990
811,810 -> 811,405
245,255 -> 367,255
860,225 -> 860,100
753,626 -> 697,626
755,404 -> 836,404
733,476 -> 336,476
562,172 -> 964,172
339,989 -> 749,989
167,581 -> 167,611
217,475 -> 217,747
103,598 -> 431,270
11,989 -> 989,11
925,90 -> 46,969
26,963 -> 935,54
40,925 -> 40,816
67,942 -> 984,25
933,652 -> 933,242
942,292 -> 942,138
889,909 -> 180,200
604,770 -> 237,770
30,627 -> 973,627
750,777 -> 750,645
254,797 -> 254,169
939,167 -> 347,759
889,682 -> 394,682
788,338 -> 388,338
757,252 -> 169,252
806,131 -> 699,131
562,270 -> 562,481
950,349 -> 459,840
219,915 -> 932,202
977,505 -> 977,708
915,559 -> 915,125
366,397 -> 366,717
54,723 -> 433,723
570,842 -> 236,508
513,365 -> 513,80
569,523 -> 569,266
278,764 -> 278,178
136,136 -> 84,84
787,108 -> 787,809
461,388 -> 855,782
64,898 -> 848,114
628,71 -> 178,521
842,66 -> 842,699
293,68 -> 742,68
960,102 -> 358,704
834,669 -> 27,669
11,43 -> 374,406
399,803 -> 340,803
564,211 -> 20,755
370,841 -> 370,321
518,590 -> 518,255
470,150 -> 470,850
769,182 -> 234,717
97,787 -> 97,382
36,31 -> 982,977
831,467 -> 471,827
253,836 -> 547,836
957,681 -> 957,919
768,831 -> 768,275
98,36 -> 955,893
283,413 -> 840,413
21,870 -> 20,870
979,507 -> 979,37
339,757 -> 210,757
388,594 -> 801,594
867,939 -> 91,163
755,864 -> 755,501
856,177 -> 736,57
74,365 -> 376,63
386,451 -> 815,22
389,883 -> 679,593
116,216 -> 157,175
693,960 -> 693,454
704,962 -> 306,962
613,442 -> 867,442
578,13 -> 578,855
417,683 -> 118,683
127,161 -> 742,161
646,979 -> 646,270
14,842 -> 14,802
496,902 -> 506,912
468,354 -> 468,875
714,431 -> 714,172
554,297 -> 554,790
717,664 -> 883,664
551,182 -> 980,611
794,932 -> 499,637
384,499 -> 507,499
32,368 -> 257,368
984,131 -> 904,131
973,16 -> 10,979
189,178 -> 189,752
492,404 -> 492,593
11,515 -> 117,515
230,182 -> 230,954
652,16 -> 663,16
698,693 -> 490,693
252,942 -> 587,942
551,901 -> 428,778
899,320 -> 903,316
14,577 -> 313,278
409,576 -> 409,475
466,883 -> 819,883
221,472 -> 609,472
686,828 -> 686,720
988,989 -> 13,14
514,171 -> 227,171
868,842 -> 632,842
279,824 -> 697,406
678,464 -> 678,687
736,358 -> 736,259
933,66 -> 24,975
679,470 -> 679,689
979,953 -> 45,19
98,826 -> 737,187
612,732 -> 612,681
985,23 -> 23,985
787,732 -> 332,277
660,211 -> 660,61
395,19 -> 246,19
129,876 -> 955,50
676,246 -> 821,246
980,26 -> 18,988
142,945 -> 142,218
165,240 -> 540,240
941,522 -> 941,129
876,274 -> 876,340
627,782 -> 905,782
928,235 -> 246,235
336,449 -> 92,205
748,62 -> 748,787
804,725 -> 356,277
910,89 -> 19,980
391,99 -> 155,335
608,127 -> 516,219
337,255 -> 337,649
818,831 -> 818,859
146,204 -> 301,359
629,646 -> 906,923
87,860 -> 824,123
613,867 -> 613,946
286,339 -> 286,626
942,120 -> 595,467
35,207 -> 187,207
684,559 -> 283,158
48,768 -> 48,349
656,965 -> 656,27
865,341 -> 865,576
218,786 -> 152,786
697,69 -> 583,69
790,79 -> 552,79
310,547 -> 846,11
428,809 -> 428,940
664,829 -> 664,455
265,775 -> 749,775
362,221 -> 309,168
437,253 -> 437,597
601,324 -> 245,680
24,69 -> 24,476
420,344 -> 420,525
215,866 -> 635,866
926,770 -> 315,770
413,650 -> 413,624
751,765 -> 475,489
673,709 -> 39,75
230,689 -> 805,689
31,209 -> 789,967
698,255 -> 909,255
641,752 -> 866,527
346,780 -> 391,825
328,905 -> 328,130
628,674 -> 628,354
666,110 -> 98,678
846,651 -> 846,371
28,946 -> 28,482
289,844 -> 458,675
605,602 -> 605,297
355,217 -> 239,217
453,96 -> 195,354
988,90 -> 145,933
801,194 -> 801,109
894,708 -> 894,212
177,447 -> 607,877
824,391 -> 788,391
386,940 -> 471,855
703,425 -> 583,425
848,110 -> 36,922
603,596 -> 685,678
584,458 -> 584,482
464,903 -> 343,903
888,413 -> 405,413
320,185 -> 103,185
475,458 -> 55,878
371,843 -> 371,466
785,507 -> 785,570
904,553 -> 904,983
872,600 -> 872,848
296,693 -> 751,238
490,488 -> 322,488
37,371 -> 185,223
238,618 -> 238,883
232,89 -> 123,89
20,14 -> 961,955
794,318 -> 914,318
407,499 -> 246,338
641,514 -> 227,514
284,210 -> 562,488
164,566 -> 498,900
20,825 -> 150,955
235,384 -> 537,686
151,116 -> 979,944
697,133 -> 59,771
212,226 -> 38,226
523,527 -> 523,497
119,493 -> 352,726
927,157 -> 154,930
336,149 -> 581,394
103,580 -> 354,580
891,494 -> 532,853
22,272 -> 538,788
544,296 -> 519,271
821,382 -> 821,155
501,807 -> 501,202
588,76 -> 708,76
773,681 -> 184,681
754,936 -> 86,268
582,972 -> 40,972
530,458 -> 530,329
109,433 -> 649,433
411,215 -> 411,311
433,568 -> 433,585
232,504 -> 799,504
72,442 -> 38,442
""".split('\n') if x ] ]
print(data)

isvert = lambda ps: ps[0][0] == ps[1][0]
ishorz = lambda ps: ps[0][1] == ps[1][1]

def overlap(data):
    """Return..."""
    grid = [ [ 0 for c in range(1000) ] for r in range(1000) ]
    for ps in data:
        x1, y1, x2, y2 = ps[0][0], ps[0][1], ps[1][0], ps[1][1]
        rangex = list(range(x1, x2 + 1)) if x1 <= x2 else list(range(x1, x2 - 1, -1))
        rangey = list(range(y1, y2 + 1)) if y1 <= y2 else list(range(y1, y2 - 1, -1))
        if isvert(ps): rangex *= abs(y2 - y1) + 1
        if ishorz(ps): rangey *= abs(x2 - x1) + 1
        for x, y in zip(rangex, rangey):
            grid[x][y] += 1
    return len([ n for sl in grid for n in sl if n > 1 ])

def part1(data):
    """Answer part 1 of https://adventofcode.com/2021/day/5"""
    return overlap([ ps for ps in data if isvert(ps) or ishorz(ps) ])
print(part1(data))

def part2(data):
    """Answer part 2 of https://adventofcode.com/2021/day/5"""
    return overlap(data)
print(part2(data))


# AOC 2021 5
[((491, 392), (34, 392)), ((337, 52), (485, 52)), ((256, 605), (256, 959)), ((889, 142), (153, 878)), ((189, 59), (512, 382)), ((399, 193), (598, 193)), ((578, 370), (795, 153)), ((79, 450), (569, 450)), ((565, 444), (270, 149)), ((39, 28), (39, 846)), ((114, 353), (114, 383)), ((356, 61), (356, 327)), ((140, 132), (515, 132)), ((361, 848), (361, 527)), ((466, 257), (466, 784)), ((818, 397), (818, 14)), ((693, 554), (693, 984)), ((171, 290), (171, 655)), ((989, 889), (170, 70)), ((527, 855), (527, 549)), ((209, 355), (486, 355)), ((800, 430), (291, 939)), ((980, 38), (31, 987)), ((964, 559), (964, 799)), ((491, 612), (930, 173)), ((57, 977), (958, 76)), ((149, 465), (349, 465)), ((512, 624), (629, 507)), ((460, 943), (460, 441)), ((988, 29), (988, 968)), ((104, 337), (441, 337)), ((939, 48), (939, 546)), ((941, 904), (498, 461)), ((850, 972), (649, 771)), ((840, 901), (23, 84)), ((231, 790), (231, 873)), ((230, 668), (840, 58)), ((410, 922), (435, 897)), ((341, 337), (341,

---
## https://adventofcode.com/2021/day/6 &mdash; Lanternfish

## Part 1

This part asks to find the number of *lanternfish* after 80 days given initial conditions and following a circuitious growth pattern:

> each lanternfish creates a new lanternfish once every 7 days&hellip; a new lanternfish would surely need slightly longer before it's capable of producing more lanternfish: two more days for its first cycle&hellip; A lanternfish that creates a new fish resets its timer to 6, not 7 (because 0 is included as a valid timer value). The new lanternfish starts with an internal timer of 8 and does not start counting down until the next day.

### Strategy

- parse the data into a list of lanternfish ages (noting that these 'ages' count down, not up).
- repeat for 80 days:
 - decrement all the ages in the data.
 - for any ages that go below zero, set their ages to 6 and add a new fish with age 8 to the list.
- report the number of lanternfish at the end of 80 days.

## Part 2

This part asks to find the number of *lanternfish* after 256 days given the same initial conditions and following the same circuitious growth pattern.

### Strategy

This exponential growth is too much for a na&iuml;ve approach that follows the strategy of *Part 1*. It takes way too much memory and &mdash; even if optimized using `set`s &mdash; crashes at about day 170.

However, it is only necessary to count the *number* of lanternfish with ages between 0 and 8 days.

- parse the data into a list of lanternfish ages.
- create a `fish` list of 9 element  for the 0 - 8- day cycle consisting of the number of lanternfish at theose ages.
- repeat for 256 days:
 - slice the `fish` list, removing the number of lanternfish at day 0.
 - add that number into the number of fish in the `fish` list at day 6.
 - append that number to that end of the `fish` list for day 8.
- report the number of lanternfish in the `fish` list at the end of 256 days.

In [6]:
#!/usr/bin/env python3
#
# https://adventofcode.com/2021/
#
# AOC 2021 06
#
# aoc202106.py
#

print('# AOC 2021 6')

data = [ int(x) for x in """
1,3,4,1,5,2,1,1,1,1,5,1,5,1,1,1,1,3,1,1,1,1,1,1,1,2,1,5,1,1,1,1,1,4,4,1,1,4,1,1,2,3,1,5,1,4,1,2,4,1,1,1,1,1,1,1,1,2,5,3,3,5,1,1,1,1,4,1,1,3,1,1,1,2,3,4,1,1,5,1,1,1,1,1,2,1,3,1,3,1,2,5,1,1,1,1,5,1,5,5,1,1,1,1,3,4,4,4,1,5,1,1,4,4,1,1,1,1,3,1,1,1,1,1,1,3,2,1,4,1,1,4,1,5,5,1,2,2,1,5,4,2,1,1,5,1,5,1,3,1,1,1,1,1,4,1,2,1,1,5,1,1,4,1,4,5,3,5,5,1,2,1,1,1,1,1,3,5,1,2,1,2,1,3,1,1,1,1,1,4,5,4,1,3,3,1,1,1,1,1,1,1,1,1,5,1,1,1,5,1,1,4,1,5,2,4,1,1,1,2,1,1,4,4,1,2,1,1,1,1,5,3,1,1,1,1,4,1,4,1,1,1,1,1,1,3,1,1,2,1,1,1,1,1,2,1,1,1,1,1,1,1,2,1,1,1,1,1,1,4,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,2,5,1,2,1,1,1,1,1,1,1,1,1
""".split(',') if x ]
print(data)

def part1(data):
    """Answer part 1 of https://adventofcode.com/2021/day/6"""
    for d in range(80):
        data = [ x - 1 for x in data ]
        new = len([ x for x in data if x < 0 ])
        data = [ x if x >= 0 else 6 for x in data ] + [8] * new
    return len(data)
print(part1(data))  # 386755

def part2(data):
    """Answer part 2 of https://adventofcode.com/2021/day/6"""
    sets = [ set() for i in range(9) ]
    for i, n in enumerate(data):
        sets[n].add(i)
    # print(sets)
    fish = [ len(s) for s in sets ]
    for d in range(256):
        eights = fish[0]
        sixes = eights + fish[7]
        fish = fish[1: ] + [eights]
        fish[6] = sixes
    return sum(fish)
print(part2(data))  # 1732731810807


# AOC 2021 6
[1, 3, 4, 1, 5, 2, 1, 1, 1, 1, 5, 1, 5, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 2, 1, 5, 1, 1, 1, 1, 1, 4, 4, 1, 1, 4, 1, 1, 2, 3, 1, 5, 1, 4, 1, 2, 4, 1, 1, 1, 1, 1, 1, 1, 1, 2, 5, 3, 3, 5, 1, 1, 1, 1, 4, 1, 1, 3, 1, 1, 1, 2, 3, 4, 1, 1, 5, 1, 1, 1, 1, 1, 2, 1, 3, 1, 3, 1, 2, 5, 1, 1, 1, 1, 5, 1, 5, 5, 1, 1, 1, 1, 3, 4, 4, 4, 1, 5, 1, 1, 4, 4, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 3, 2, 1, 4, 1, 1, 4, 1, 5, 5, 1, 2, 2, 1, 5, 4, 2, 1, 1, 5, 1, 5, 1, 3, 1, 1, 1, 1, 1, 4, 1, 2, 1, 1, 5, 1, 1, 4, 1, 4, 5, 3, 5, 5, 1, 2, 1, 1, 1, 1, 1, 3, 5, 1, 2, 1, 2, 1, 3, 1, 1, 1, 1, 1, 4, 5, 4, 1, 3, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 5, 1, 1, 1, 5, 1, 1, 4, 1, 5, 2, 4, 1, 1, 1, 2, 1, 1, 4, 4, 1, 2, 1, 1, 1, 1, 5, 3, 1, 1, 1, 1, 4, 1, 4, 1, 1, 1, 1, 1, 1, 3, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 4, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 5, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1]
386755
1732731810807


---
## https://adventofcode.com/2021/day/7 &mdash; The Treachery of Whales

## Part 1

This part asks to find the *minimal* sum of the distances (positive or negative) that each number in a list must change in order for the numbers to be equal.

### Strategy

- parse the data into a list of integers.
- check the `abs` of the difference for every number between the minimum and the maximum values of the list and each number on the list and calculate their sum.
- report the minimum sum.

## Part 2

This part asks to find the *minimal* sum of the [triangular number](https://en.wikipedia.org/wiki/Triangular_number)s of the distances (positive or negative) that each number in a list must change in order for the numbers to be equal.

### Strategy

- parse the data into a list of integers.
- check the `abs` of the difference for every number between the minimum and the maximum values of the list and each number on the list and calculate the [triangular number](https://en.wikipedia.org/wiki/Triangular_number) of their sum.
- report the minimum sum.

In [7]:
#!/usr/bin/env python3
#
# https://adventofcode.com/2021/
#
# AOC 2021 07
#
# aoc202107.py
#

print('# AOC 2021 7')

data = [ int(x) for x in """
1101,1,29,67,1102,0,1,65,1008,65,35,66,1005,66,28,1,67,65,20,4,0,1001,65,1,65,1106,0,8,99,35,67,101,99,105,32,110,39,101,115,116,32,112,97,115,32,117,110,101,32,105,110,116,99,111,100,101,32,112,114,111,103,114,97,109,10,273,102,514,428,300,13,9,457,92,169,1654,471,479,178,158,124,354,83,705,30,80,199,632,31,840,580,1228,1597,151,1374,1665,469,43,1113,103,1,1456,132,2,618,423,824,789,145,485,585,543,694,1266,866,1276,726,680,1714,503,79,137,208,8,1447,455,33,1098,1346,1028,178,1095,21,19,52,668,29,382,1659,310,225,21,15,258,915,434,92,181,120,408,612,684,2,5,1507,127,746,203,66,4,82,440,1796,166,515,216,422,175,1643,240,100,178,375,487,134,599,581,38,101,19,882,1580,282,228,409,1124,409,255,1004,90,123,146,1130,461,84,9,1537,240,42,812,815,72,140,299,317,398,982,340,529,521,204,1137,895,912,313,27,540,638,403,188,163,133,34,1038,1597,440,200,275,2,1057,682,108,340,1096,361,2,242,464,392,432,334,955,145,275,605,858,173,375,435,3,3,784,396,324,1004,25,794,61,1358,752,31,563,23,407,886,870,501,1353,195,751,1407,10,874,31,33,589,124,403,205,225,40,1510,150,172,74,9,715,39,14,36,1775,29,1094,1007,199,4,26,301,878,751,538,33,102,109,297,236,119,195,431,34,179,827,6,204,91,594,65,255,1136,820,163,1508,388,680,968,1587,235,294,543,197,640,143,95,28,814,1053,827,167,54,606,0,823,3,340,619,195,31,216,330,287,382,676,392,5,1233,248,1000,323,872,234,316,4,112,663,113,1402,357,416,148,53,102,681,15,294,407,269,297,386,4,254,1666,454,139,1173,65,572,132,3,368,290,271,716,646,626,1727,411,196,181,1256,92,29,4,337,207,557,425,43,465,35,85,1218,241,936,247,94,1433,1002,400,624,88,1072,1048,370,101,264,78,379,27,65,672,1368,692,822,1020,317,472,1019,298,486,2,18,163,1304,994,952,455,454,661,1,473,561,313,92,425,218,29,49,618,790,615,347,462,169,275,247,1445,1880,225,1778,159,176,569,32,529,602,34,365,84,753,253,962,137,917,401,507,242,451,751,67,20,1208,411,226,829,317,283,219,154,683,30,1092,24,386,24,117,545,35,188,621,14,1453,24,892,330,337,754,407,481,906,643,552,864,808,360,704,118,368,297,1446,1348,104,1077,588,298,141,971,2,801,74,434,663,543,872,447,368,109,292,526,933,489,65,33,1061,1030,727,718,62,31,518,457,1569,815,422,187,211,1193,256,811,88,65,275,998,618,113,208,160,113,270,1085,295,20,161,117,134,1045,132,28,29,779,1108,24,801,240,184,414,79,335,98,486,195,100,302,574,561,353,8,260,1,540,584,410,1299,266,44,1120,877,252,377,849,83,547,637,827,298,1151,222,90,533,551,203,203,67,881,6,812,88,1314,178,169,576,885,767,278,1565,154,108,543,31,100,190,298,254,1478,594,644,957,177,20,1578,482,121,106,841,195,16,51,561,205,55,97,107,380,128,655,629,995,1424,1005,276,838,143,506,450,56,172,955,20,1045,253,436,1016,1106,68,540,807,265,405,301,539,1236,874,986,1092,274,1208,738,89,107,510,90,15,1402,313,712,35,222,494,125,113,290,259,274,214,70,1416,242,1312,1023,974,128,1787,91,13,992,84,673,185,375,385,0,285,135,116,105,26,103,929,733,567,294,174,82,1181,941,161,1242,387,20,882,1789,1164,1157,936,1110,1142,1308,657,931,29,603,1001,157,22,786,161,835,459,843,50,3,51,42,476,509,1214,733,1102,1011,0,832,1186,246,284,503,455,146,398,13,1109,106,90,511,1232,1837,580,285,86,1388,1199,195,225,742,194,1448,1732,309,1074,1380,251,1010,137,382,1367,490,1828,47,11,888,251,16,37,393,1407,233,5,814,780,850,22,1196,957,492,4,254,745,580,651,225,1072,872,323,618,24,303,79,7,75,11,15,65,449,205,103,836,150,111,424,786,194,1752,55,674,1469,1050,891,50,792,0,381,31,152,141,91,1521,420,18,779,450,68,929,122,106,7,142,185,355,768,581,1024,140,438,350,1838,815,977,23,663,324,30,7,408,461,40,108,203,459,530,69,120,177,962,162,1566,253,2,308,232,42,1564,1161,48,270,253,83,652,247,539,166,159,856,331,1701,970,1085,442,21,868,960,298,534,378,75,226,586,21,57,636,279,1112,63,1519,555,191,773,168,120,603,716,544,1546,378,418,149,138,1212,575,29,284,577,223,145,387,639,1204,154,613,48,116,307,341,716,3,831,987,629,1338,852,189,340,1213
""".split(',') if x ]
print(data)

def part1(data):
    """Answer part 1 of https://adventofcode.com/2021/day/7"""
    return min([ sum([ abs(n - i) for n in data ]) for i in range(min(data), max(data) + 1) ])
print(part1(data))

triangular = lambda n: n * (n + 1) // 2

def part2(data):
    """Answer part 2 of https://adventofcode.com/2021/day/7"""
    return min([ sum([ triangular(abs(n - i)) for n in data ]) for i in range(min(data), max(data) + 1) ])
print(part2(data))


# AOC 2021 7
[1101, 1, 29, 67, 1102, 0, 1, 65, 1008, 65, 35, 66, 1005, 66, 28, 1, 67, 65, 20, 4, 0, 1001, 65, 1, 65, 1106, 0, 8, 99, 35, 67, 101, 99, 105, 32, 110, 39, 101, 115, 116, 32, 112, 97, 115, 32, 117, 110, 101, 32, 105, 110, 116, 99, 111, 100, 101, 32, 112, 114, 111, 103, 114, 97, 109, 10, 273, 102, 514, 428, 300, 13, 9, 457, 92, 169, 1654, 471, 479, 178, 158, 124, 354, 83, 705, 30, 80, 199, 632, 31, 840, 580, 1228, 1597, 151, 1374, 1665, 469, 43, 1113, 103, 1, 1456, 132, 2, 618, 423, 824, 789, 145, 485, 585, 543, 694, 1266, 866, 1276, 726, 680, 1714, 503, 79, 137, 208, 8, 1447, 455, 33, 1098, 1346, 1028, 178, 1095, 21, 19, 52, 668, 29, 382, 1659, 310, 225, 21, 15, 258, 915, 434, 92, 181, 120, 408, 612, 684, 2, 5, 1507, 127, 746, 203, 66, 4, 82, 440, 1796, 166, 515, 216, 422, 175, 1643, 240, 100, 178, 375, 487, 134, 599, 581, 38, 101, 19, 882, 1580, 282, 228, 409, 1124, 409, 255, 1004, 90, 123, 146, 1130, 461, 84, 9, 1537, 240, 42, 812, 815, 72, 140, 299, 317, 398, 982, 340, 5

---
## https://adventofcode.com/2021/day/8 &mdash; Seven Segment Search

## Part 1

This part asks to find the number of unique segment combinations in the scrambled 7-segment digits. There are only four unique segment length:

- segments of length 2 &mdash; corresponding to '1'
- segments of length 3 &mdash; corresponding to '7'
- segments of length 4 &mdash; corresponding to '4'
- segments of length 7 &mdash; corresponding to '8'

### Strategy

- parse the data into 2-tuples of strings: the first of which is the 10 scrambled 7-segment display combinations and the second of which is the 4 digits of the scrambled 7-segment display.
- create a list from all the digits of the scrambled 7-segment display which are of length 2, 3, 4, or 7.
- report the length of that list.

## Part 2

This part asks to find the 4 digits of the scrambled 7-segment display based on the 10 scrambled 7-segment display combinations. The unscrambled segments are:

```python
segments = [ 'abcefg', 'cf', 'acdeg', 'acdfg', 'bcdf',
    'abdfg', 'abdefg', 'acf', 'abcdefg', 'abcdfg', ]
```

### Strategy

- parse the data into 2-tuples of strings: the first of which is the 10 scrambled 7-segment display combinations and the second of which is the 4 digits of the scrambled 7-segment display.
- use a brute-force method of checking all $7! = 5040$ permutations of `'abcdefg'`, recreating the 10 scrambled 7-segment display combinations with each of the permutatsions substituting for the original, and finding when they match.
- decode the 4 digits of the scrambled 7-segment display using the matched 10 scrambled 7-segment display combinations and convert them to a decimal number.
- report the sum of the converted decimal numbers.

This approach is entirely brute-force and takes several seconds to compute. It has the advantage of not requiring any logic, *e.g.* involving the unique segment lengths of the '1', the '7', and the '4'.

In [8]:
#!/usr/bin/env python3
#
# https://adventofcode.com/2021/
#
# AOC 2021 08
#
# aoc202108.py
#

print('# AOC 2021 8')

data = [ tuple(x.split(' | ')) for x in """
fgcae ebafc cabdef eg abecfg abgfed feg gafdc bceg ebgcadf | defagbc faecg cfdag gecb
eagd cad fgadbc aefdcg dcebfg fcegd cbeaf ad dbgfeca defca | cfdeg gdcabf fcgde afgced
gfdeca aeb eb fbdag eafdc adfbe cefdab bdaegcf efbc ecadgb | eb dbafe eab faecd
facbdge efdg gcafd daegc caegb aecfdb ade ed gafbdc dgfeac | de abcdef faedcg dfgca
dcaegbf bc dcgeab cbgad cebg cdfaeb fbadg acdge cefdga cdb | gdcfae gbec gdace cgadfe
ceagfbd fbaeg fadge fbegad abgecf dafcg ed edab ged dfcbeg | gebfa de gbafec ed
acedbf adfbg cgafedb geac cgb befcgd bcgaf bfgace cg bfeac | bcdfeg fecba cafgeb bgdfa
egadc cea ac agbcedf cgab bgcade fbcaed eadfbg fegdc ebdag | fdecabg fcged cdbage efgdab
cbfge gdc cdea efdag dc cdfeg gfbcad gcdeaf cdeagbf egfadb | dfcge egcfd fcdbag dc
gaedb fbced gcdbef cge gc decgb dcbgfea cgfb cgdfea fbcade | fdegbac fecbd ecg degba
geaf bcfedg agbcd bfeagd dgfbe cbdaef beacdfg abe agebd ea | fbecdg geaf gebfad adgbc
bed afgebd adecf bafgedc dbca cfegb becdf fabdce bd gcfdea | gfdaeb ebfgad dbefc cbda
gacfebd ag bedfca agbfde egfcab dfga degab fbade bag bdecg | dgaf abcfed agb bfecag
afebg afdeg gcbe acebdf cfbage cafeb gab decgabf bg gcfdba | gb caebf abgef acfebd
efdab fabdgce gcbfa eg gacbfe beg ecag beafg dfabcg bgecfd | bge fgdcbe gcfdba ebdaf
aecbd bdagef gd bfega aefgcbd gfde gfdcab dbg edgba febagc | dg dagfbc dgfe eabdgf
gdfba egfacbd gdcefa baf gcba fdagcb dgfac ab dcfeba ebgdf | dcfag bfa gafcd cbag
afbe bdagc cedfb defcab ebfdgac gfedbc cbfad af adgcfe adf | dafbc dfbac fdcegb gadcb
fcgedb ca fdcage cagdbef ceab acedfb fdbce cafdb cda afgbd | ac dcafb efgdac ebcfda
fbad gbcda dcefgb cfeadg dgbcaf bcafdeg ad gcabe adc dfbcg | gbcdef bcfdg cgbfd bfadgc
afcgeb bedag bdecafg agb bedfga fdagce bg bgfd dfgea cdabe | badge cagdfe efdag afegbd
gfed dcaef ge bafdce daceg acebfg cefadg egc ecdabfg gacdb | bcgad bcegaf agecd degcafb
deacb adcge ab acb fbdce faedbgc fgadec gabd deabgc ecbfag | dfbec ab cbagfe bcfgae
gcabfde ecf cbdeg bacgf fedg ecfgb gfedcb fcaedb cebdag fe | dbcegf bcgdfe gfde defg
daefb bfg gedafb fabge dbafec cfega bdga cgbdfe gb gbacedf | aecfg bcedaf begdcf dgba
bagce bf bdacfeg efbg fcb cefab gbfadc cafebg ecdfa bacdge | fegb cegba bagce efbg
becag cfeg cefgbad fbace gfeacb acdegb bef ef adbcf fdabge | ef bdfac cbegad gbeac
egb afcbe fbaeg eabgfdc gcab gb gfdea fgbecd bcdafe gafbec | fcdgeb edcgbfa gbe fgeba
dga caebd ecdag cegfd abdfce dafbge ecbgda bcdgefa ga agbc | afdbec ecfdab gdaec gad
fc gbdefc cfe ebdaf fcbeda gbafde edacg bfcdgae dacef cabf | decgfba cdbefg cf ecdabf
febgd dafgbc caed cgd ceadgf fbecga dcgfe aegfc gbedfca cd | dgfeb fgced dcafebg agdfce
ecdafgb bgade bgd fabd gbaef bd egadbf ceadg cfbgea dgbfec | edagc bdage bfda dbgae
cgeba aefgcd dfceagb dc ced facbed cdfb dbaec adfeb fgedba | fbdea bgcae efbda fcdeag
caegbf dcfga afcedgb afgdcb fcedag ab edbcg dbfa gdcab abg | bag cbdag agb ab
gadfecb befc fgdbea cf fedagc fac bcgfa agbfe adgcb feagcb | gbcda cgbad bcgfa cf
dae aefcb dgabec dacfg afebdc ebfd afecgb aedcf fbcagde ed | ecabfgd bedf bcadef egdacfb
abcf fcega fdgce fegbda eafdcgb ac gabecd gbfae beagfc eca | edbgca edbfga cae gface
bgedcf afcdbg ag gcbaef fcedgab afgdb cfgbd befda acdg agf | fdbga ceadbfg egfbac fag
bad edafc bdeg abcgde ecafgbd gfadcb bgaec db edcba geafcb | cdafe fdcabg cdfageb dbge
geb bgcf agfcde gb befag gfbcae defab gabdec eacfg gabecfd | afbedgc gceabf abgef egacf
fdeac acg cfegda cbeadf fegdbca ag acefg adge bfdgca gbcfe | gecdaf efgca cgbafd cfgeb
begdf bdfgc ebcf adfcg cdegbf dgeafb cbg cb bfeagdc gbdcea | acgedb fagdbe bgfde dfgac
afcgdb aedc bedgf egafcd afdge gecaf fcgebda gda da ceabfg | gedbf gacfe adg agdef
bdeafg acgebdf dgcfa fa cafe dgfbc gaf edagfc cgabde agedc | fadbge bdgfcea dgcefa cgeda
gacfbde defag cbgef gbca efadcb afcbeg cgbdfe ba eba gefab | fegab abe ebfcgd fbgae
gfbdec fbcade cabdegf ebdg bfd dcfgb cadgf gebcf db fcabge | eacdgfb bdge ebdg ecafdb
egcfba fdcae fcdaeb gcfdae fabd ba cdeab fcdbaeg eba decbg | cabed facbed cbade dfcea
agdfe acfdeg fcdbeg dgf gdaec df cadf ceagbfd abgfe gbdaec | bgcdef abfge gbefcd df
dgebf afgdb bfa fcbade af dcafgb agcf gcbda dabgecf gadecb | dbcga abcdge fadgbce eagcbd
dbcga bea egacdf dageb be efbd abgfce gadfe fcbegad aebfdg | eba be bdage bedga
gcbd egbdafc fgc fbgedc gc aedbfg cefgb fedbg cfaegd efabc | bface egfbc bgdacfe gc
fdgae dc ced gbcd gbcefd decfba becfg ecfabg cgfde gbcadfe | edbcfg cd cafgbe cdegbf
geadcf efg gadef fg fecad acbgfe dagecbf dcgf gadbe afbdce | edafcg bgcfade gfdc abedg
edcba ecgdb aedbcf aebf dabfc fdacge badgfc ae ead gfcbade | gcebdaf degbc ebfadc efdcba
caedbg dbgec dcbf ecgdbf cgdef dgf bgaedcf egacf afebgd fd | cdfbeg ecfbgda gcbfed cbgedf
bdag acdeb ecgdb egbcfa fcdbega gb dbecag cbdafe ebg gdcef | bedgc abdfcge efagcb cdgef
bfade bfdga dfbgec cagbfd dfgacbe gba gacf ag gdcbf abgedc | cfag abdcge ebafd abefd
agcdef bcfda bdgca aebdfcg eagdc gb dbg gbea cedagb bfgdec | dfabgec eafdgc acdge gdecab
ebacdfg cgbfad egdbc bdgfa daef bae gabed febadg ae gacbef | fagdb daebgf fgdab bea
dcgbf cbedf degc bgc fcgdbea fbadg cfdgbe gc efacgb fdbace | edfcb cfeabg cg edbacf
bcdagfe dfacb cbfdge bgcdf fdgeac acd agbd acbef da dcgfba | cbgdf dgab ad gbdcaf
edgfbca gbe be ceba bdaecg gefcd dbagc egbadf dcegb dfgabc | gcfde gfceabd gfbcad eagfdb
dfcbg fcdga efgb gecbfd gecbda dfbgaec bedfc dgb bfadce bg | dbcgf bfge dacgf dfgcbe
cga ebdgaf bfdag cbgfe bfadgc gbfeadc ac cagfb cdba cgadef | bfdag agedcf aegcbfd gcfab
gcead gfdbec cbdge gabfce eb dfgcba ecfdgab befd dgcbf ebg | cdgae fbdegc bcdge gcdfb
da ebgfda fcdeagb acgbfe gedba dbegc agdecf dae bafeg bfda | gdafec fegba edfbga aed
fbagec gdfba bcg gebcfd cbafg bcdfgea ebac cefag faedcg bc | gfbac baegcfd fabegc dgeacbf
dfbeag fabdg fdbe abdeg eb dcega gcefba cfdbag dgcfbae geb | cgbafd bdef dcage eb
abdcfe gba dagf cagbefd fdbea bfega ag dafbge dcbeag gfceb | afbcde ecgfb dfbega bdgeca
dg dge gdbc cfdae bcgae cbdage abgfde cfedagb cdgae eacgbf | eabgc bgeac bcdg cagbe
bfd dgaeb gcabde fd bfgce dgfa dbefg gadbfce dbafge fabcde | edfcba efbcg df bdf
gcbfd agbecd fedc edcbfg fdb eadfbg bcfag fd gedcb gbacdef | fgbac bdagfec gfbdaec aegbdc
cgbdfe ce acedg adcfeg bcfegad fcea ceg abdeg afbdcg fcgda | ecg aefdcg dacge ec
egbdfca efacb agcdbe cbaed bdafgc dfaecg debg bd bda agced | geadbc efbca gabfdc bd
edcfb bfgecd ecabfd eca abcd fgeab fedcag abfedgc ac bfeca | bgfae eca cdgfeb bfaec
cadef cebdga ebd bacdfe dagfec dbfa fcebg ecbgfad db fdecb | befcd acgdeb abdf dbfa
gbfecda bfd cdagb fbdacg fgdbec gbaf cbadf aefdc eadcgb bf | adcgb dfbca agbf dafcb
abedg acbgf fd gaefcb cagbdef cdaf dcbfeg bdagf dgcbfa bfd | gbadcef df fadgb gabcdf
fbgadc dbcfg dcega cgdfe cfedbg caefgb ef gef gfaebcd fedb | fcedg febd gbcdfa cdgfab
bg adgb fcaedbg cgfda fcbae bcg dfacge fgcdba decgfb bcagf | cgafb dbfcage bdgcfe dbga
ed afbdg acefb aecbfg cfdabeg gedfcb fcdabe ecda def ebdfa | gbafd gedfcb dfegcb dfgba
gcdfae efgdb abdfcg fde gdabf dbcegfa fedgab efab ef ebdcg | eafb gbfda gacedf cbdge
edagfc gfaecbd bgced cbegfd cb gefdc badgfc bdc efbc adegb | dgbec cegafd dcbgef dgecb
gedcab beg eg cafgb fbegc gdfe bdgfec gabcedf bdafce bcdfe | gcefb afcbed ge gdfe
fdbagc cdgefab edacf ceba ea cfbaed ecfdg abfegd adfbc eda | ea beadfc abcgdef ecdgf
fbc gfbacd fecda cbdfa dbgf dceabg gbcdfea efbgac cdabg bf | gbdf agbced gaedbc gfdb
aegcb bfgecd fbegad fcagdbe dfgce fcbd gdeacf fb bgf bgfce | bgafedc gcdaef dgfcbe eadgcf
def dbce agdfeb ed fdgbcea dgcfb aegfc dfgbac gecfd cdfgbe | cdfegb ed cdgfaeb ebdc
ecbfad afdb eagbfc caebgdf edfcb dgfec cgdbae bd bcafe bdc | bfacegd fbdcae dbc bgfdcea
dfgba eg cfbead gde bfedgc dceab cabfdge gdbae aecg aedgcb | egd adebg gde debcfa
cadfb egfb afgbc adbegc ecgadf ecagb fga ecfgab bgacfde fg | afcbg cgfba gf dacbge
cegbf dec efcdg facdge dfae dcbafge ed adgfc fdbagc cgaebd | dce gbcfe afcdgbe dcgabf
cfabe fa eabgfc cgaf fba gfbce dcfbge edbgcfa efbadg acebd | cfebga bfa fedcagb abfce
acdfb dbagf afcebgd beag afgedb gfdea gbd fgdcbe gb cdeagf | dafge gafed gfacde gb
gdfeac dfgce ebfadcg edagc dacf baegdc fd gdf egcfb dabgef | degfbac cfdeg daebgf cdeagb
fcgabe ebcd ecfdg dabcgf gfecabd cfd ebcfg dc bcfegd adefg | agedf cd bcefg dc
cbaeg bcfea fb feb gfaceb gdfbec dagbec gfab deacf bgcaedf | acbfge bf afgb efb
egdba cadgfbe efadbg cg begc bfgdca caegd abcegd dcg acdfe | fbegcad bceg gcd cdgebaf
agbcd dafcgb cfdg ceadb fdgeba eafbcg gfdab gbc bgdcafe cg | gfadcbe fbagd decba gc
gfbec adgc dge egdcfa abgfde abgdfce dg eacfdb fdaec gdfce | fecgd gd fgcbe acdef
fdbceg bfedc af fegcad cbdag daf efab dabcef fbeadgc cbfad | fcabd cbfad gcfdbe gadbc
ebgac fabdeg bedca cg aegdcfb geacbf ceg efgba facg fbedcg | gecdfb aebfg fagc ceg
eagb dcgeb ba abd cbeagd cdgafb fecbdga fgedcb dacfe dacbe | bdfeacg cadgbf bgedfc fcdae
dbac cfgae cbfgde ba bga gcfbad dcfebga gcdbf feagbd cgbaf | cgafb fagbdc dcfbg afgebd
adbgfe fgb egdafc cbafd dfegbc edgafbc egfcd cegb gfcdb gb | bg fdacge efcadg egdfba
agfbe cgaefdb gbdf edagb afg cdgafe gfedab fg egcdba fabec | fcbdega fag agf agf
cae edabfc cdfega ca cfba gadeb fdecb ecagfbd cbgdef acdeb | facdeb fgecad bfadce efcgbad
facb dbfec dceabf efgcd cb aecfbgd dgfbae eafdb ebdagc bcd | bfedc cdegab cbdfe adefb
fecbga badgc dga bfgadec dg geacb cgedba dfebag gcde fcabd | decg gda baceg gd
gecbd gcbdfea cbfg bg bge egbcdf dcbef beafdc cdeag bfgeda | agcde dceag gfabde beg
gefba gacfbe facdeg cg cgab gfc efbdcag cfgeb cefbd afegbd | gfc afbge dafegb aebcgf
egd aebfgd gefc ge gedbfca bdcfe dfcegb gecdb edbacf cdbag | dacbg edcfbg bcdfe ge
df ebdga gcdefa cfbd bgdfa afgcb dfeagbc bfacgd fgd facebg | gaebd gecbaf fdcb dfbag
fag cegfdab cadebg dabcgf abefg eafc ecafgb ebacg fbdge fa | ebfag dbcgfae gbecad fdbgac
gecbd gefa gfc fabdcg bfaecd ecgafbd fg befgc efabc gecbfa | gfae gcf egbdafc edgbc
bfgae fcebag fdbe fd fedag adgfbc fdbgea ecagd agcbfed fad | fgabe dfeb ebfd gefba
ecdgfb afge bdage ebcda eg abdgef fgadb gabcfd dge bcdagef | gdebfa eg agfbdec afeg
dbc acefd cegadbf fbcde afcb fdcaeg bc acdbge febdac debfg | ceafd caefd gfbaced dcb
fecgb fgacd gdcefba de gbafce febd gecfd edc fecdbg ecbgda | becdfg ed becgad gcdeba
agfdbe fbac bcd edacfb bgecfd cb cdeba cfgdeab acged edfab | cb dbc adbce bdfae
dgacef bdfa ecgbf ab fegba dgafe efdbgca abg acebdg afbdge | gefda ecgafd ecfbg begcad
gbfcea bgfa afdebc aegdcb af bgcdfea bgeac gecdf afc fgace | bfgecad fca afc abfg
cfe dgcfe fdagcb gebdc egfa gbcdefa dcebfa fe agdfc fgaedc | dfgac fe fce fcdbega
fecgab gcbdef cbaefgd dfgbe dgcfe eb bfe dbfga edbc acfegd | fbdeg fdgeca agefbc egcfd
aecd bac dfacbe cafdb ac gefcab gfcdbe fcbde gbdaf cbdegaf | gcdbefa fbgcae ecad fagecb
eagbf cagedf geafdbc fdgbce adefb aecfd adcb deb faecbd bd | ebd deabf fadcge cdagfe
gadefcb bfcga eadcgb egdbfc deag ecg edabc acedbf eg abgce | gdea bagce gce gce
agcfe bec gecab gbeda facb dbfgec fcegab gfacde gfdaceb cb | cb cefdgb cadefgb bc
fdgb df egabcf fegda cedga fegab efdbac def cgdefba gafedb | facdbe bafceg agedf fdebga
fdaecg dbcafg abfgec dc caefg cedg aecfd abdgfce eadbf fcd | cgefab gbfacd fbegac fabecg
dfecabg bcfeag gdafce dagbfc cdefb dca gafbc dbag da bcadf | dca bagfce cbfda cdagbf
dabfgec febadg gbcdae gfbe adebf ef cabdf edfgca ebgda eaf | gfacbed abgced egdfca egfb
cfdea dc fdagebc fegcbd agdc gcfade fcabe cfd efdgba gfead | bdfcge agdc dgefa cfd
gbfca febadcg bc bdegcf beca begaf gabedf cgfbae cgfad cbg | bcg dcaefgb dfgceb afebdg
cg cgbf bedcg fcagde adefbcg efdgcb ebacd cgd edbfg egdafb | cfgedb bgcf acegdf cfgb
bfad adcgbe faceg fagbdc df afdgc efcbdag dfbegc gfd badcg | gfd abgcd fgd abfd
bcadgf cgdfb adgcb gf gafc dcfeabg bdagce dgf dfbega cebdf | adcbfg gfca fdcbe gfac
daebf fcabgde bgdcef gab ga edbcga afcg ebfga aefbgc egbcf | ebcfg ebcgfa fcgebd agcf
gedab fg afgecb cfgd feg cfabed befdc fgdcbe gdceafb befgd | ecafbg ecfbd febdc gf
gcbadf ce gfcdb fec feabd gbecdf dbcfage febdc agcdfe egbc | bafed gcbe gefcbd egcb
cbdfg gbcafd feb gaecf gcbfe gfbdae be fcgabde bdgcef becd | abgedf gdfebc aedgfb fbe
edacgbf fbdae edgac bg gab bagdec dagfce fadbgc cebg bgdea | aedgb bg cebg adcge
bda gbfea gedcab gfbceda bgdfa bfcdg febcdg bagcfd cfad da | dbecag bgfdc gdbfa facd
ceabd dabfe acgde bc fbca cgbfde febgda dfecagb ebafdc bdc | cbdae dbfea fgdceb gbfedc
acg fadbgce cfgdeb dbgce efdca ag dbga cagbef egacd cdgbea | gdecabf gcbfea ecbdg gac
dfgacb ged egfdab efcgbda gcefbd debga ebadc ge aegf gfdab | cdfgab cdafgb bfcgda ge
gdbeca bcfde eafg cefbgad dgafcb ge degfb adefbg dgfba bge | bdfeg begdf ebfadg eabdfgc
cfbdgae gbaec bagfcd gfcba dcaeg bacfeg dbeacf bec efgb eb | ceb egcab cagfb dgcae
fdcagb gdaecb fcadg bcdgaef gd dfcea gbcaf aecgfb cgd dgbf | gfadc gfdb badgfc gbfca
bcafed defgcab fgcb cfbae cagde agebfc gbcae gbe gadefb gb | bg gfcaeb bg aedgc
bcfadeg gbfd eacfbd gdafe afebg bafegd geafcd gebca fb bfa | agdefc eafbdg fgead gedaf
fcgeabd dgeaf ebgfad gceafb geadc ac aec ebcdg cafd adgefc | gbfadec egcbd acfd dgabef
eac fbdgec ea eadb cbaeg agfdecb eafdgc dcgbe bcfga adcbeg | aec abde eac ea
cedb gcadbe ed edgfbac fbega abdge gacdb fdacgb dcefag aed | cdagb gbcafd gdefac gedafc
cae agfbec ae begcd feab fadgbc ecfadg ecabg cdgbefa cabfg | ecgba afcgb efba dgeafc
fecgabd badf efadg abedfg fea fdgceb fedgb aebfgc af gdcae | ebfgca fae fea af
bgedac gbfae dcbefg acbf fb gaedf cagedbf aebgc gebfca fgb | aedgf fdgea bgfae bfdgeac
bagcfe eadcb gb facegdb bgc fdcag efbcad beadgc bgadc ebgd | gbc fbcage becad gbfcae
cagde gbca dcgbea gc efcad dbgfea dfgecb caedbfg adgbe cdg | gc egdfbc bcga cg
efgcbd aebgcd dfe eadfb abged abdcefg bacfd ef bdfaeg faeg | fgae cgdaeb adefb afcbd
cgbfea gcbda gefdcb eadf febag bdf fd febgad fadbegc bgadf | gebcfd fgdbea dfb dbf
dg cdgfe gecfad dfbce bgefda fgd eafcg efcbag dgac bcdagfe | afdebg gfd aecgf gfcea
edfga cgefda gcdbe fbae ab egdabf cfgbda deabg bad adefcgb | ebadg agdeb fbae gbdae
gbdcfa gbade ebgac ecbfa adfgbec badecf bgc gcef fbgace gc | gc fcge gacefdb ebgca
acefgd ebgaf egfda egcd bgfaecd dgcfa ed abcefd efd abdgcf | def ebgaf fed befcda
fecag cag cfagbd agfcbde fabec eabg fdcge cgbfea fadebc ag | cfgbda dfgbeca efdcg dfgcaeb
bgecfda ecdag dgfcbe bdgac adbgf afgdbe bfac gdcabf cbd bc | bc acbgefd fagcdb fcba
ba efacg cfbgde cfdbg bacgf bgfdea abf bcad cfbeadg bgcfad | bcdgef fdgaeb ab cagfe
cbdaf bafdgc eacbd fd dcf fcabg bcdfeg bedgcfa dgfa agbecf | dfga bgfac df agdf
edcabf cadbf bgfdcea bgcfad bgcde dfg fg bdfgc cgadfe abfg | adfecg gfbcd acgdfeb cbgdaf
badgfc dg bagcde bceda dbcfea beafg debag adg fcbadeg edgc | gebda dcagbf dceba egfab
edcf dacfbg dbcefag fbd df bdegfc ebdagc bgfea begcd bfedg | dgebc cbgde dgfbac bdf
bdcfg acegfb acebfd fdcag egadcf da daf cgeaf edag bafcegd | gdcaf fgaec bafdec fdaecb
cagefd fde gdfba fcgaedb abefd ef dafbeg ebfg afcbgd ebdca | egdbfa bceda dfabg bdace
fcgb gcdae bg gfadeb cbfegd fcabed bdg gcdbe fdcbe adbefcg | dgb gfbdec befdc gfbc
fabde bgfde bgecda cedgb gf cabfdeg ebfdgc fgbeac fcdg gfb | fgbde efdgb edgbc afedb
ebacf cedfab fde eabfd fd baecgf bagde agdebfc dfcb egfadc | ebfdgac acdegf abdefc ebfad
gdcb cd cfgae cgbedf fbegd efgdc fadcbe gfeacdb dce dfagbe | gbcd cde gacfe gefdbc
geb afedgb bfegca bgade eg dgef gadbc eafdb afebdcg fcbead | cagbd defcba dbafec geafcb
fgbdc gbfade gba gefa dbafg cbadge bfgecda ga edbafc dfabe | afbdeg dgfba bgdfa dcfgb
agef badce ef febad cabfdg gdfab cbgeafd egfbdc defgba fbe | abefd geaf gafdbe ebcad
gd gad bfdg gecba fedabcg fcgeda aedfbc adebf agbdfe dgeab | ebcdaf agd gcfbdae egacb
cedbfa ba cgbfa abf dfegac cafeg gabe befgca ebdfcag cbfdg | fab aegcf faecbd fdcebga
daefg febdga aegfdbc efgdca eafb bge eb agbdec febgd gbdfc | gbcfd edbfg egb bacegd
fbdecg bdafec cfaeb gedac def dceaf abfd fd gfecba gfdaecb | ebfac bdfa gbcdef fd
fcbga cbdfeag bafgce fdacg dc fcd fcgbad fadge efcdgb cdab | gaefcb bafegcd acdb abcgf
ecgabd acgdf abge ae bcfead fgdaceb ead daegc bcdefg gcbed | egba gaecd cgadbe gdbce
aegfbc gf afebdc agebdfc ebcdf feg dcefg bdfg dcgea bgedcf | edbfcg fdgb bdgafce febgcd
dcg bcdefa dbfceg fdeacg acbeg bfeagcd cfdae dg dfag agdec | dfcgea dg egdca edagc
agcfeb fagbed fdbceg bag gebfd afgd agbfcde acbed ag badeg | cbdea fcedgb gfebac abcegf
adbegfc fgdace cadge afcg ebdfca ebgad eac bfgdce cgefd ca | acged fcedg ebagd dgacefb
gfeadb gfeab bcfa agebcfd aebgfc fecgbd efc fc gadec egcfa | fgbace fc debgcf afgceb
bacg ab cfgbd bfadge acfed fgdecb agedcbf fcabgd bfa dbafc | gfdcb cbga abcg afecbdg
ge beagc cfgabd bgaced bgcda fbadgec age ecdagf egbd fcbae | aeg gedbac cadfeg fbgcda
dgbafe abfdgec gdf fd agebcf gadec dfcgba befd edfga aebfg | abcgefd dagec dfg df
edfcga bcegd baeg cbgdae agdbc gce acgdebf eg gfadbc cefbd | dcbeg bgedc cedbg edcbg
adfbe dg cagef dfgb gdbeca aefdg gda edcbaf fdgeba gdecbfa | cdabef eafbd bafcegd dg
cd edcbfg dbage fcaebdg facd bgcfea afbedc afbec dbc adecb | adegb bcefag abegd cbgedf
gdcbf da ecgbfda adc adgb bagcfd dfbcea egfac dfbceg gdacf | gdba cfdbg adbfec fcaeg
bcg bc gdcbae dbca abfgde gdeba ebfacdg egcba faceg dgfbce | geadb badecg ecbfgd baecg
""".split('\n') if x ]
print(data)

def part1(data):
    """Answer part 1 of https://adventofcode.com/2021/day/8"""
    return len([ s for t in data for s in t[1].split(' ') if len(s) in { 2, 3, 4, 7, } ])
print(part1(data))

import itertools

segments = [ 'abcefg', 'cf', 'acdeg', 'acdfg', 'bcdf',
    'abdfg', 'abdefg', 'acf', 'abcdefg', 'abcdfg', ]

alpha = lambda l: [ ''.join(sorted(s)) for s in l ]

def rearrange(perm, segments=segments):
    """Return sorted segments permuted based on perm."""
    order, segs = 'ABCDEFG', [ s.upper() for s in segments ]
    for i, c in enumerate(perm):
        segs = [ s.replace(order[i], c) for s in segs ]
    return alpha(segs)

def part2(data):
    """Answer part 2 of https://adventofcode.com/2021/day/8"""
    decoded = list()
    for the10, digits in data:
        the10, digits = alpha(the10.split(' ')), alpha(digits.split(' '))
        for perm in [ ''.join(x) for x in itertools.permutations('abcdefg') ]:
            arr = rearrange(perm)
            if all(a in arr for a in the10 ):
                decoded.append(sum([ arr.index(d) * 10 ** (3 - i)
                    for i, d in enumerate(digits) ]))
                break
    return sum(decoded)
print(part2(data))


# AOC 2021 8
[('fgcae ebafc cabdef eg abecfg abgfed feg gafdc bceg ebgcadf', 'defagbc faecg cfdag gecb'), ('eagd cad fgadbc aefdcg dcebfg fcegd cbeaf ad dbgfeca defca', 'cfdeg gdcabf fcgde afgced'), ('gfdeca aeb eb fbdag eafdc adfbe cefdab bdaegcf efbc ecadgb', 'eb dbafe eab faecd'), ('facbdge efdg gcafd daegc caegb aecfdb ade ed gafbdc dgfeac', 'de abcdef faedcg dfgca'), ('dcaegbf bc dcgeab cbgad cebg cdfaeb fbadg acdge cefdga cdb', 'gdcfae gbec gdace cgadfe'), ('ceagfbd fbaeg fadge fbegad abgecf dafcg ed edab ged dfcbeg', 'gebfa de gbafec ed'), ('acedbf adfbg cgafedb geac cgb befcgd bcgaf bfgace cg bfeac', 'bcdfeg fecba cafgeb bgdfa'), ('egadc cea ac agbcedf cgab bgcade fbcaed eadfbg fegdc ebdag', 'fdecabg fcged cdbage efgdab'), ('cbfge gdc cdea efdag dc cdfeg gfbcad gcdeaf cdeagbf egfadb', 'dfcge egcfd fcdbag dc'), ('gaedb fbced gcdbef cge gc decgb dcbgfea cgfb cgdfea fbcade', 'fdegbac fecbd ecg degba'), ('geaf bcfedg agbcd bfeagd dgfbe cbdaef beacdfg abe agebd ea', 'fbecdg geaf geb

---
## https://adventofcode.com/2021/day/9 &mdash; Smoke Basin

## Part 1

This part asks to find local minima in a grid.

### Strategy

- parse the data into a 2D grid of integers.
- for each entry, check the value to the *north* (if there), to the *south* (if there), to the *west* (if there), and to the *east* (if there) and remember the entry's successor in a grid of zeros if it is less than all four surrounding values.
- report the sum of the minimal grid values.

*Part 1* uses a utility function `minima_grid` that checks each data point and its four compass-point neighbors to fill in a corresponding grid of minima points.

## Part 2

This part asks to find the product of the sizes of the largest 3 'basins' surrounding local minima. A *basin* is defined as minima points surrounded by maximal points (9s) or the grid boundary. 'Locations of height 9 do not count as being in any basin, and all other locations will always be part of exactly one basin.'

### Strategy

- parse the data into a 2D grid of integers.
- use the `minima_grid` utillity function to locate all minima points.
- use the [flood fill](https://en.wikipedia.org/wiki/Flood_fill) algorithm to collect all points within a basin around every minima point.
- sort the basin points and add them to a `set`.
- report the product of the longest three basin sizes.

*Part 2* uses a utility function `flood` to implement a n&auml;ive stack-based recursive [flood fill](https://en.wikipedia.org/wiki/Flood_fill#Stack-based_recursive_implementation_(four-way)) algorithm.

In [9]:
#!/usr/bin/env python3
#
# https://adventofcode.com/2021/
#
# AOC 2021 09
#
# aoc202109.py
#

print('# AOC 2021 9')

data = [ [ int(n) for n in list(x) ] for x in """
8969799987646798965432975435334567987976999867976794468999979759865767896545699865678952123899325456
7658678998434597654321984320123458976765789998965432367998968998754556789434987654489543535698912349
6243457899325679997620195431934569765654667999993101246796856997643245679759865443356954656987894498
4102345678912998789531297659895978954213456899874512659965239876432134578998754321267899877976789987
3212466989109887678942989797659799542102345798765423867894103987543026799989866532345678999765469896
4323487893299795489899978987947689654243496789876864988943212498654135999967987765466789987654398754
5694698999987654398788967895434589879359989999987879999994467598795276789756798876567895699873219865
6788799998998975976567456899598678985498879898798989865879978939876987993145899987879954598765102987
7899899897989989875432345678998789897987968799659197654756899857989899921034999898989433459854213698
8913998766779999964321234569999897789876754678943296543434998769997797892129898789995321298765434569
9101987655767989875732345679987946689654343469764987542127899898765656789298797678976510159977675678
3212396543256878986893478999876434596543212378965698321016789999854245991987664599987621245698789789
5433495432145767897954567896985423689954301299986986432125899998762127892976553469998753457789899892
6567989543023456798966878994597434567896212989897998764234678987654679999897432348999864567997999953
7699978932124569899987989789986545678997329878798969976656789998785793599789645667898965989456789867
8988767993237678998998995678998698789865498765689654399787898999887975987689956788977899992398999879
9976458789398899687899234567999899899978987654569543219899956789998989896579899899866458943989109989
9854345679479976556954346788998999999989876543468965323987548999969498765466788956954367969878998797
8765456796567895434699459899996878998694987742556896439876439999854329654354567899875167898657897656
9896577897679966724978998943985456896513498651345689546989998898765439843212456789984356789346789843
5998678998789653219866987899876368954323489710556898768998787789876898756533568899995679891245898932
4299789349898742109654346798765458976535679921237999879867546678987989987654679978976789910234567891
5989894234969876298743234569878567899796798545346899998653434569399876599785789567987898929345688932
9878943123459865459652127999989678978998987655456789129742129679210997679897995456798987898957899543
4965431012567986798764335679598789469899998767767891019843298999429698789998932348899876767899999654
3986949143479997899865466789409892346789979879878992123969976578998539997899321467999765646978998765
2399898954567898999876567893219921235798766990999789235698895457997623456921932346998654334567899978
1299767895789999999987678999398633896899954321235695476987789598998735797899894459876543212456899899
2988956799899998989998989798976545789999896532346789569986679679439987898986789667987654201268999798
9876545788987887679899897657987656798998789987656799698785458994321299999575678978998764312349987677
8787434867976544556797623546698767987887678999767978988654356789490123985434567899799876543456997536
9643323456895433545679510134599879876765567899878969876543234899989349876423468976567998954567895215
7432102568954321234595431235678998765634345678989456998754345987879956994312469965456899996789954324
6543212349975410123489545676789769874321234789790365679976576896567898984203457896597946987898766534
7695323457897521236679686787896656965454345689621234567987687932498959876412679989989532498939878745
8986445569998934345689899998955549877965678796542347678999798940989942986567897678978901359012999987
9997556978969765456897998899643435988876789898753456789999899759878891987879976564568992459223989999
9998967889349876577896767789532123999998898999897598999988959898767790298989985323456789998939878998
9879878993212987698965656679921039876439967899999979899876545987656689349896546012367899876899767987
8867989854623999999873245567892134965323456789998765789987632496545459998765432123456998765698959876
7656799769539897895482133456954379854212597993987653999898521569632367899979643236567898754987939984
9545678998998765989321012567895459763102379932199654569765437698743458932398654387989987543656898765
8936567897899874578932123456976598765213467891034987698996548899654567891019767898999876521246789897
7623468976799765799543438967898679984324579932123498997989679998765678942423989999978988430134899998
5434578985679878997654567898939789995445698965349569876678989899876789759994596598769877321475678999
6559689643456989298775678999029895987576987896467978965457899782989899998789789429898765432386799989
7798789432345690129976789998939974599999896889878999784346998651296989876598993219989876743457898878
8989895431258789245987899987898953459878784978989989653245696542345679999457894398879987857567947566
9877987646779898659998999876567994979967643467899878964126789655456989998379965976569898967679434345
9965499867895989798999598765476789398756532456798967893235899766967998987567899879456799298989321234
9876789978954878987995459654345891296543101236987656789345678979899896798679998768345692129695433545
1988899989763567896889698743236892989754752345698545678956799998789765698789876753238789234569546656
3499949999874878945779987632123999768969643467899234589999899876578954329999875432124679945698756767
9989237999996989234567976431019888943498955989998545678989906987689965410199764321012989896799999879
8978956789997892146678986542239767832487996792987656789679215698896894321989875754123456797899989992
7867897899989921012349597953398756721276789891098767896598924599965789939878996543254597898998978991
5658998979876432124692398965986543210345996999239878965487895987654597898965987654765678949987959889
4234789767987543235789459896798765321267894878945989874356789998783456987954599875676989657995349778
2123679854987674347896569789999876543458943467956999995245894987632969876843456996787899969986234567
3012568966998989498987998677899987754567892458969899874348943986549898765652345987998999898942123679
6123456799879996579999899576789999869678943467899789965457921098798789854321234598949998677991014589
5434767959767987898998765435699987998789765598923679876767892349987698765210349899659986566789323899
8545679943854598986987654324589996689896986679013459989888999959876579894321235789898975345678946789
7676899892123999875698763215679965456965498793223598794999998799975467965452347999987654234599659899
8989986799019887654679974323467896568942349954334987653234987678894359879643458969876542123689898988
9798865678998765712578985454598987979321257895455798852109895467789234998754569653999892012567987877
7697654367897654323456798579689898989910969999579999743219654347689945679967679999549764123456896556
3598765456998768974567987689795679099899898997678987654498653201567896989898798878934965236587974449
2359987767999899765978998999964589298787656789989398765789765443489989899789897767949874347678953237
1491299879999999987889459329899999987654745894590249876899899865679876784699976456899985678789654126
0989901989789989998991399439777899898543435789931399987934999876898765633987895367899876799896543235
9877899995678978989532578998656998797632124567893989998923498989999874012346789246987989898987655345
8766798989789469878943789879546899654321012978999878999212997796799982178968992134976591997899796656
9954547878992399967899899865434678998732129899998769899929876565689875357899843239899432395698989768
7653235669991987856798999876215789987654239789987657789899765373499876567898765498798954986987878979
8762124456789996543467894989104589998768998678986545678789876212345987688959876569657995999876567999
9989012347899865432356993298913478999879876548995434345678968101356799799545987898745789865985456789
6598924456895996421245689987897567892989998756789621257989543212456893987634598999658999654986687899
7987899568934987840234567896789978921399899987898530968999964566567892396723679998767898953199789989
9876798979924987656495888934567899210198789898987649899999898788689910975435678979878997899019899975
7675356899899898767686789123679954391297698769999789799898789898799921296586789567989876798923989764
6543245698798789879899899019789995989987569543935998689765679909899892397697994345698765867894578953
8432136987657678999910998998998789778943468999899019789954234912998789998998943234989544556895678942
7543239876543457989422997867997643567892979679678929899892123893989689789989432109875432347989989431
8664345975442345678999876656789432456789895434569439998789234679876597678976543499964321235679894320
8798459864321256899987655346896563567898789212497598687679345798765326567897654989984310199998789491
9897568995438767898998643238987678689987679101789987543568996987654215458998775979996532987877578989
9987679986549878987976543129998989799986568932679876542356789099873101299439989868987543976966457577
8998790197678989756797643256899999899865457894569867421867992198764323489321098756597654965452323456
7679891998789691234598765345678923989954366789697654320378943579885654678999987643469869876321012345
4567939879896542456999975457789019878942134898789865621247894567986965699678996532398979876432123456
3459329765998653567895986568993139765899012979899876732456789678987876896599989421297989998673234568
5678909984329764678993497679954397654678923567943987654567997999799987897987678932986794569984545778
8799998965679889889989598989795986543567994578992399876799236789654398999896568943975523679995656789
9989767899789997993978999895689997562456789989989976987890145899876789998768456999854302368987789894
9879356789899876432767898764789775431634578899879765698991236799987896999654397789763213459998993912
8656244678998765321545987653459654320123456789767954019789445678998945898743235678954424668999542103
7542133569899878510126976432398797431835668892456892124689556889329236789655656789765634569987543765
6531012456789996431239954321239986545646799986587893776789678993210127898767787899879745678998955897
6542123568899987544398765510123497656656789987678954567898799654431338999978898910989656789209876789
""".split('\n') if x ]
print(data)

def minima_grid(data):
    """Return a grid with same dimensions as data filled with zeros and scored minimal grid points."""
    grid = [ [ 0 for c in range(len(data[r])) ] for r in range(len(data)) ]
    for r in range(len(data)):
        for c in range(len(data[r])):
            n = data[r][c]
            # Compare four compass points for being greater than n.
            if (r == 0 or n < data[r - 1][c]) \
                    and (c == 0 or n < data[r][c - 1]) \
                    and (c + 1 == len(data[r]) or n < data[r][c + 1]) \
                    and (r + 1 == len(data) or n < data[r + 1][c]):
                grid[r][c] = n + 1
    return grid

def part1(data):
    """Answer part 1 of https://adventofcode.com/2021/day/9"""
    grid = minima_grid(data)
    return sum([ grid[r][c] for r in range(len(grid)) for c in range(len(grid[r])) ])
print(part1(data))

# https://en.wikipedia.org/wiki/Flood_fill#Stack-based_recursive_implementation_(four-way)
def flood(data, r, c, nodes):
    """Return nodes from recursive flood fill in data from position (r, c) given nodes."""
    if (r, c, ) in nodes or r < 0 or r >= len(data) or c < 0 or c >= len(data[0]) or data[r][c] == 9:
        return nodes
    nodes.append((r, c, ))
    flood(data, r - 1, c, nodes)
    flood(data, r + 1, c, nodes)
    flood(data, r, c - 1, nodes)
    flood(data, r, c + 1, nodes)
    return nodes

import functools, operator
prod = lambda l: functools.reduce(operator.mul, l, 1)

def part2(data):
    """Answer part 2 of https://adventofcode.com/2021/day/9"""
    grid, fill  = minima_grid(data), set()
    for r in range(len(data)):
        for c in range(len(data[r])):
            if data[r][c] > 0:
                fill.add(tuple(sorted(flood(data, r, c, list()))))
    return prod(sorted([ len(f) for f in fill ])[-3: ])
print(part2(data))

# AOC 2021 9
[[8, 9, 6, 9, 7, 9, 9, 9, 8, 7, 6, 4, 6, 7, 9, 8, 9, 6, 5, 4, 3, 2, 9, 7, 5, 4, 3, 5, 3, 3, 4, 5, 6, 7, 9, 8, 7, 9, 7, 6, 9, 9, 9, 8, 6, 7, 9, 7, 6, 7, 9, 4, 4, 6, 8, 9, 9, 9, 9, 7, 9, 7, 5, 9, 8, 6, 5, 7, 6, 7, 8, 9, 6, 5, 4, 5, 6, 9, 9, 8, 6, 5, 6, 7, 8, 9, 5, 2, 1, 2, 3, 8, 9, 9, 3, 2, 5, 4, 5, 6], [7, 6, 5, 8, 6, 7, 8, 9, 9, 8, 4, 3, 4, 5, 9, 7, 6, 5, 4, 3, 2, 1, 9, 8, 4, 3, 2, 0, 1, 2, 3, 4, 5, 8, 9, 7, 6, 7, 6, 5, 7, 8, 9, 9, 9, 8, 9, 6, 5, 4, 3, 2, 3, 6, 7, 9, 9, 8, 9, 6, 8, 9, 9, 8, 7, 5, 4, 5, 5, 6, 7, 8, 9, 4, 3, 4, 9, 8, 7, 6, 5, 4, 4, 8, 9, 5, 4, 3, 5, 3, 5, 6, 9, 8, 9, 1, 2, 3, 4, 9], [6, 2, 4, 3, 4, 5, 7, 8, 9, 9, 3, 2, 5, 6, 7, 9, 9, 9, 7, 6, 2, 0, 1, 9, 5, 4, 3, 1, 9, 3, 4, 5, 6, 9, 7, 6, 5, 6, 5, 4, 6, 6, 7, 9, 9, 9, 9, 9, 3, 1, 0, 1, 2, 4, 6, 7, 9, 6, 8, 5, 6, 9, 9, 7, 6, 4, 3, 2, 4, 5, 6, 7, 9, 7, 5, 9, 8, 6, 5, 4, 4, 3, 3, 5, 6, 9, 5, 4, 6, 5, 6, 9, 8, 7, 8, 9, 4, 4, 9, 8], [4, 1, 0, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 9, 9, 8, 7, 8, 9, 5, 3, 1, 2, 9, 7, 6, 5

---
## https://adventofcode.com/2021/day/10 &mdash; Syntax Scoring

## Part 1

This part asks to find and score the *syntax errors* on the input data lines.

### Strategy

- parse the data into lines.
- use a `stack` list to add left delimiters and remove right delimiters for each line until a delimiter mismatch, then remember each mismatched delimiter.
- score the mismatches as follows: `score = { ')': 3, ']': 57, '}': 1197, '>': 25137, }`
- report the sum of the scores.

## Part 2

This part asks to find and score the *incomplete* input data lines.

### Strategy

- parse the data into lines.
- use a `stack` list to add left delimiters and remove right delimiters for each line until a mismatch-free line ends.
- score the leftover delimiters (in reverse order) as follows : `score = { '(': 1, '[': 2, '{': 3, '<': 4, }` &mdash; using the `accum` &lambda;-function below.
- report the median score.

I used the sample data to verify the `accum` &lambda;-function for scoring.

```python
accum = lambda l: functools.reduce(lambda s, n: 5 * s + n, l, 0)
```

In [10]:
#!/usr/bin/env python3
#
# https://adventofcode.com/2021/
#
# AOC 2021 10
#
# aoc202110.py
#

print('# AOC 2021 10')

# Sample data for AOC 2021 10
data = [ x for x in """
[({(<(())[]>[[{[]{<()<>>
[(()[<>])]({[<{<<[]>>(
{([(<{}[<>[]}>{[]{[(<()>
(((({<>}<{<{<>}{[]{[]{}
[[<[([]))<([[{}[[()]]]
[{[{({}]{}}([{[{{{}}([]
{<[[]]>}<{[{[{[]{()[[[]
[<(<(<(<{}))><([]([]()
<{([([[(<>()){}]>(<<{{
<{([{{}}[<[[[<>{}]]]>[]]
""".split('\n') if x ]

data = [ x for x in """
<[<<<<[{[<({{({}<>)<[]{}>}[<<>{}>{<>{}}]}{(({}<>){()<>}){{[]<>}{[]}}})>([{{(()[])[{}()]}}(<{{}<>}
<<[<<{[<<<{{<(()[])>[({}{})]}}({{({}())[<>{}]}}{{(<><>)[<>()]}<<<>{}><<>()>>})>{[[<(<>[])[[]{}]>{{[]<>}<[]
<[{<<(<([{<[<{()<>}<{}[]>>([<>()]{<>()})]{[([][])<{}<>>][<<><>>]}>}][[[<{{[]{}}[[][]]}([{}[]]<[]<>
<{[(<<[({([{<[{}[]]{<>{}}>}[(({}()){[]<>])]]{{<<[]>([]<>)><<{}()>{<>[]}>}{({<><>}<<>{}>){(()[])<()<>>}}})
[{<{[(({[[<<<<<>()>{(){}}>[{[]{}}(<><>)]>{[<[][]>(()<>)]<<[]()><()()>>}>])}(<{<[<<{}[]>>{[()[]]({}{})}]>{
[<{<[[[<{[<<[{<>{}}<(){}>]{<{}{}><{}{}>}>{<(()<>){<><>}>}><[<{{}()}>{{<>()}{()<>}}]({<{}<>>}[{()<>}[()()]])
(([(<({[<<({{<()()]{[]{}}}[{<>()}[[]()]]}({[<><>]}<[<>{}][()<>]>)){{[[[]<>]<<><>>](({}{}){{}()})}}>>]})>)<((
(<<({((<<(<{([()]<()[]>)}[{(()<>)(()())}{{()<>}<()()>}]>)({[<(<>())((){})><{<><>}[{}<>]>][[[<>
[(<([{[[[{{{([()()]([]()))[<[][]>[<><>]]}{(<[]>[(){}]){[<>{}]{{}()}}}>[<<[[][]][{}()]>[<<>{}>
{<{[[[{<<([({[<><>][(){}]}({(){}}[{}<>]))<{[(){}][<>{}]}{(()()){{}[]}}>]{[((()[])<()[]>)<<(){}>{{
[<[{{{({([({<<(){}>[{}<>]><{{}<>}[<><>]>}[[<(){}>([]{})]<{(){}}[{}[]]>])[<({<>{}}<{}<>>)({<><>})>]]){(<(({
<<{[[{[[(<[{[[{}()][()[]]](<[]{}>(<>))}(([{}()])<[{}()](<>())))]><(<[[<>{}](<>())][[<>()][()]]>{<<<><>>[()[
<<([<[{{[[({[{()}[{}<>]]({{}{}}{<><>})}<{{{}()}<()[]>}<<{}{}><[][]>>>)<{([[]<>]<{}()>)][([{}()
[(<<[[{<<{<[[<()[]>({}<>)]<{[]<>}<{}<>>>]{<<()<>>[[]{}]>([{}()]{()()})}>[<{((){})[{}()]}[([]{})<()[
[<<(<{[{{[<{(([])({}())){<<>>{()[]}}}{[(<><>)[[]()]]{<<><>><()<>>]}><((<<>()>{<>{}})){[{()()}][[()[]]([]{})
((<[({<[(({[{(()())<(){}>}<[[]<>]{()()}>]({<()<>>(<>())})}<(<[[][]]{<>[]}><<[]<>>[{}[]]>)<{([]{})[{}()]}([[]
[([{<[{(<<({[<{}()>([][])]{({}<>){{}[]}}}[<((){}){<>{}})[{(){}}]])({([{}<>]{<>{}})})>[<<{<{}<>><[
[{{{[<({({{{[<{}()><[][]>]({{}{}}([]))}{<[<>{}]{{}{}>><{{}<>}>}}}[[[([{}()](()()))][({<>{}}{<>{}}){
[<{[{{(<{[<[(<()()>{()[]}){{{}{}}(<><>)}]<<({}{}){{}()}>{([])(<><>)}>>[({{[]{}}})<{(<><>){(){}}}((()<
<[<<[<(([<[{(<[][]>(<>[]}){{{}<>}[{}()]}}]<[[<{}{}>{()()}][[<>()]]]([<()>(()[])])>>][{[((<[
[{({<[[{<<[<[(<>{})<[]{}>]<<[]{}>[<><>]>>{({()<>}[<><>])}]><{{{{[]()}{<>[]}}<((){})>}({<(){}>[
{[<([[<(((<{<{[]<>}<[][]>>}>)))[<<{[([[]<>]([][]))(({}<>)<<><>>)]<{{{}{}}<<><>>}([()<>](()()>)>}>>]>{({<{
{{{{(([<(<{({(()())([][])}{({}()){[]{}}})}({(((){})[{}[]])}{((<><>){<><>}>[<{}[]>{<>[]}]})><[{<(<>[
<[<[<(<<<{(([[(){}]({}<>)]){<[()<>]{()()}>[[{}{}](<>)]})((((()<>)({}<>])[[{}<>][<><>]])(<<{}{}>(()()
[[{(([<{<[[({{{}{}}<[]<>>}{([]){<>()}})[(<[]()>(<><>)){<<>()>{()[]}}]]]>(<[[{(()<>)[[]{}]}(([]())(()
{<<(<<([(<(<({[]{}}{[]<>})>({([]<>)<[]{}>})){{([(){}]([]<>)){[[]()]}}}>{<{((()](<>()))}[(<{}<>>((){})
[({{{{{(<{({[{<>())(()())][<[]<>><[][]>]}{<[<><>][()()]>[<()()>([]{})]})<[[([][])<[]()>]<([][])<()<>>>]
[[[<([<[<(<{(([]<>)<{}<>>)<[{}[]]<()[]>>}{{([]()){()[]}}([{}{}](()()))}><{{<()<>><()()>}{<{}<>}{<>()}}}{{[[
(<({({[[(<[{<{(){}}[{}{}]><{()()}>}[([<>()]({}<>)){<{}()>({}[])}]]>)[[(([(<>[])<()<>>]){[<
({<[<{<<{{{({[()[]]})({[()()]{{}()}}(([]<>)<<>[]>))}}}>>(([({<[{[]}[[]()]][[<>[]]([]<>)]>({[<>()]{
{{(<[{({<[{{[{{}()}(<>{})]{[()[]]([]{})}}{([[]()][[]])[[[]()][()[]]}}}[<[<{}()>[{}[]]]>({<[]()>([
<(([(([[[[(([({}{}){()<>}]<{()[]}([]<>)]))]][{[({{<>()}<{}<>>})([[<>()]])](<[<<>()>]({()<>}{[]{}})>{[(()
([<{[<<<(<[{(<{}<>>[<>()])[<(){}>]}[[[()[]][()<>]]<<[]{}><<>()>>]]<[<{{}<>}{()<>}>{{[]()}})(<<<><>>>{
[{({{<(((({(<{(){}}>((())(()<>)))((<{}{}>((){}))<[[]]((){})>)})(<(([[]{}]<<><>>)<{()[]>(<>())>)>))))>}{{{({
[{(<<{{(<[{({{{}{}}{<><>}})}(<{({}<>)[<>{}]}<[{}{}]{{}{}}>>)]>([[{(<[][])<[]<>>)<(()<>)[[][]]>}[({()<>
<[([[((([{<[{(<>{}){<>()}}(({}[]])]([([]())<<>[]>])>[{<[{}<>](<>[])>}<[[(){}][{}()]]{{{}<>}[{}[]]}>]}])))][{(
(<[[(({({{[<<[<>[]][<>{}]>[[<>{}]((){})]><<<{}<>>[<>{}]><{[]{}}[()<>]>>]([[[<>{}]{()()}]<<()<
[{{{{<<{{{{<({<>()}((){}))(<[][]>{[][]})>{<(()<>)[()<>]><<{}{}>{{}[]}>}}<[[<{}{}>]{[<>()]<<><>>}]{<(()())<{}
([(<<{[{(<{<(<{}{}><{}<>>)[(<>[]){(){}}]>({<[]()>(<>{})}<{[]{}}[(){}]>)}>([[<<[]()>(<>)>(<<>[
<(<<{<{[{[<[{<()<>>([][])}]>]}]}><<<[([{(({}{})(()()))({()()}<<>>)}([(<>{})(<>[])][({}<>)[[]<>
<([[((<[<[[((<{}<>><{}()>)<(<>{})<[]<>>>)[<{()}({}())>{[[]{}]{()[]}}]]<<[(()[])(<>())]{<[]<>>
<<{{{<<({{<[<[<>()]{{}<>}>{<()<>>{[]{}}}]>}}{({[<[()[]][<>{}]>((()[])<{}()>)]}([{[[]{}]<[]<>>}{([]
(({[(<({<{[[{<<><>>({}[])}(<<><>>[[]{}]))(<{<>{}}[[]{}]>[[<>{}]({}{})])][<[<()[]><()<>>]><[({}[])[<>()]]<([](
([([[([(<{[<([<>{}][(){}]){<<>()><()<>>}>{[{()<>}[[][]]][[{}{}]<(){}>]}]([<[[]()]{{}[]}>[{<>[]}[[](
({((<[(<(({{([{}[]](<>()))[({}())]}[{[<>{}]<<>()>}{[{}]}]}({{<[][])[{}[]]}}((<<>{}><<>{}>))))<[<{[(){}][{
{([<{{(({[(<<{<>{}}[<><>]>{(<>[])({}())}>{((()[])[{}]){([][])((){})}})][<[<<[]()>{(){}}>]((<{}()>[{}()])<<{
{{<<(<[<(((({{{}<>}{[]<>}}[(<><>){[]()}]))[<{([]<>)<[]()>}([[]{}]<()>)>{{[<>[]]({}<>)}{<<>[]>[<><>
[<({{[{{[(<[[<[][]>{<>{}}][{{}[]}[(){}]]]>{{(<{}[]>(<>()))<((){})>}[{([])}]}){[<[{()<>}<[][]>][[
({<{{{(({({<(<{}[]>[[]<>])>})}<{(([{<>{}}<<>()>](([]<>){()[]}))([({}{}]{{}{}}][{()[]}{()()}]
((((<({[[<(<{(()[])((){})}>(([{}()]<<><>>)[{()[]]{{}}]))[[{(<>()){<><>}}{<<>[]>[[]<>]}][[{
({<[<((<({<<((<><>)(<>[]))[{[]{}}{[]{}}]>{[[()()]{()()}]{[<>{}]}}><({[[][]][()<>]})>}([[[(
({<(<<<<<(<[<[<>()](()>>][<<<>()>[{}[]]><(<><>)>]><({<<>{}>}[<<><>>{(){}}])[{{<>{}}<[]<>>}]>)(<{{{()()}
[<<[{[<{([([{<()()>[{}[]]}<<()[]>{()()}>][<<{}>[[]<>]>{[()[]][[]()]}]){[((()<>)<{}[]>){[[]()][{
[{[<{<{(({{<(({}[]))[[{}[]]{[][]}]>}}<([{(()[])}<[[]()]>]{<<<>()>[<>[]>>[[[]()][[][]]]})>){<<[<<{}()>(()
<(({{<{{<[{(<[[]<>]><({}{}){[]{}}>){{[[]{}]({}<>)}<((){})<<><>>>}}{[(([]<>)[{}<>])({<><>})]<(<()<>>{(
[[{[(<(<<[(<[[<>[]]((){})]{[<><>]<{}[]>}>)<[{{()[]>(<>{})}(({}[]){{}[]})]<<[{}{}]>{[{}{}]}>>][{([<()<>>({}
[({<({[[<[{<<{{}[]}<(){}>><[[]()][{}{}]>><{([])([])}[({}<>){()()}]>}{[{<{}{}>[<>()]}]({({}[
{{<[<[(([<{[{{[]{}}[[]{}]}]}>[[(<{[]()}(()())><{(){}}(<>())>)[<([]()){{}<>}>[<[]<>>{{}[]}]]](((({}
{(<<[(({{[[{([[][]]{{}()})([()<>][{}{}])}]([[{[]<>}({}{}]][<{}[]>]](({{}[]}){<{}[]>((){})}))][<((
{{{{({{({[{{([{}[]]<(){}>)<<[]()>([]<>)>>{[{{}()}]<[{}]<()()>>}}[[{<[][]>{[]{}}}({()[]}<[]()>)][<[{
[{{[[({[[[[((<{}[]><{}[]>){[{}{}]{()[]}})({{(){}}([])}<<[]()>[{}{}]>)]}{{{({[]}({}))<((){}){{}<>}>}{{
[<{([{(<{(((([()<>]<()<>>)[[<>()]([]{})])[(({}()))<<<>()><[]>>])[<{{<>{}}[()()]}(<[][]>{()()}
({(({{<[{<{((<{}{}>{{}[]})<{{}()}{{}()}>)[[({}()){[]<>}]{<()>[{}<>]}]}><{[[(<>{})<[][]>]<{{}<>}{{
(({{(({(<[[{[<<>{}>{[]()}][{[]{}]{(){}}]}(((()[]){{}{}})<(()())>)]([<[{}[]]>])][<{{[{}[]]<<><>>}{[[
((<[[<<<[([<[<<><>>([][])](<[][]>{<><>})>((({}<>)((){})))>[[<[<><>]<{}<>>><({}[])([]{})>]])[{[{({}<>)[()[]
[<((({{({(({<(()())<{}[]>>(<[]{}>({}{}))}))[<<[({}[])[{}[]]]<{{}{}}{[]}>>>]}[(<({<{}()>[<>()]}[<[]()>((){
[[([(((<{[[[<[{}()}({}<>)>]]{<{{<><>}({}())}{{<><>}([]{})}>}]}[([{[{[][]}(()<>)]{{<>{}}[<>(
<<([<{{<{<<(<([]<>)><(<><>){{}{}}>)<(<()<>>([]<>)){(<>{}><<>>}>>{(((()[]){{}[]})[[[][]][{}[]]])({([
[<[{<[<<(([{({[]{}}([][]))<[()<>]{{}<>}>}]<<[<{}>[<>{}]][([]<>)(<>[])]>[{((){})(()())}<[{}()]{<>()}>]>){([
[[[{[(({<<{{{((){})({})}{[<>()]([]<>)}}{[<<>{}>[{}[]]][[{}<>][()<>]]}}>{<{{([]{}){{}[]}}<{<>{
{{{<{[[<[{[<[<<>()>{{}()}][[<>{}][[]<>]]>]<{<{(){}}({}{})><(<>())[{}()]>)<{[()()]}[<()<>>(<>)]>>}
(([[<{(([<[((<(){}>[{}()]){([]{})[<>{}]})[[[<><>](<>[])]((()()))]][{{<()[]><<>{}>}}]>])<({[[({()<>}[<>{}])]]
{{({[({[[<(((({}[])(()()))))(<<<{}()>[{}]>>(<[<>[]]{[]()}>{({}<>)([][])}))>]{({{<(<><>)>[{
<<((({[([[{<<{<>{}}[[][]]><{()()}<{}<>>>>}[[[<<>()>([]())]({<><>}{{}[]})]<{<{}<>>[[]()]}{{(){}
<[{(([<(<{{[[{{}()}([]<>)](<{}()>{[]{}})]}<[[<()[]>(()())]{([]{})[<>{}]}]<<{[][]}><<<>()>>>>
<([(([{([([(<[{}[]][[]()]>(<{}[]>[<><>]))<<{{}()}<<>[]>>>])[[<[{<>()}[()()]]<[{}()]((){})>>]{[{(()[])<(
((<([<[[{[{{[(<><>)<[]()>][(<><>)[<>{}]]}}<(([{}()]{<><>})<([])[()()]>)>]{(({[()[])[[]()]}[(<>)])[<{{}
{<{<<{{[{<(([{(){}}<<>[]>]<{{}{}}{()[]}>)[<[[]{}><<><>>><[<>()]>])>{(<({{}{}}{<>{}})[<<>[]>]>)((<{
[<<<(({{{[(<{([][])[{}<>]}<(()[])(()())>>[{{<>{}}({})}[<<>>[<>]]]){([{()()}[()[]]]{[()[]]<<>>
<{{{<(<<{([[(<{}()>(<>{}))]](({[[][]]}({[]<>}{[]<>}))<([{}{}][[]])[<[]()><{}<>>]>))[<<<<()><[][]>>{(()())<[]
{{[[{[[{{{[{([<>[]][<>[]>)[({}[]){{}{}}]}[(((){})[()])(({}[])[<>])]]}<[<{<[]{}>({}<>)}{[{}[]]((){}
{([<([([{(((([()[]][[]<>])[<[]()><()>])({({}{})<[][]>}[([]<>){[]<>}])))<<{[[{}{}]][{(){}}{[]()}
<<[(([{<((<[({<>{}})[(()){[][]}]]>))>}]<({((([{([][])({}<>)}<<()()>([]())>])){{{{[{}{}]<<>[]>}{(()[])
[[{<([[{<{((({<>{}}[{}{}])([[]()]{{}[]}))({<[][]><<>{}>})){<(<<><>>({}<>))<([]){<>{}}>>(<<<
([({<<{<(<((<(<>{})({})><[[][]](()())>)([[{}{}]([]())][<()[]>[{}[]]])){<[<{}{}]{<>()}][([]{}){<><>}]>}>)>{[[(
{<(([<([(([(({[]<>}[{}<>])[(()<>){()[]}])<<{[][]}>({<>[]}{[]<>})>]{{{<(){}><()()>}({[]{}}{{}[]}))([([]())
{[<([[{[({[<{{(){}}}{(()[])<()[]>}>]<<<{()[]}><{{}()}([]{})>>{{<<>()><<>[]>>{{<>[]}{<><>}}}>
(<(<{[{[([[[([<><>])][({[]{}}({}[]))]]])[<[{({{}<>}([]()))(<{}><()()>)}(<<{}<>><<>()>)<<{}
(<[(({{<[{({{<()[]>}{{<>}<<>[]]}}{[{<><>}[{}<>]]((<>))})([[[<>{}]]<([])>])}{<({<[]<>><<>()>}[({}())[<>
{[({([(<{[[[<<<>[]>(()<>)>]<(([]{})[[][]])(<[]()><{}<>>)>](({{<><>}<()<>>}{[{}{}]([]<>)})[<{<>}[[]{}]
""".split('\n') if x ]
print(data)

lefts, rights = '([{<', ')]}>'
match = lambda l, r: lefts.index(l) == rights.index(r)

def part1(data):
    """Answer part 1 of https://adventofcode.com/2021/day/10"""
    score = { ')': 3, ']': 57, '}': 1197, '>': 25137, }
    stack, errors = list(), list()
    for line in data:
        for c in line:
            if c in lefts:
                stack.append(c)
            if c in rights and not match(stack.pop(), c):
                errors.append(c)
                break
    return sum([ score[c] for c in errors ])
print(part1(data))

import functools, operator
accum = lambda l: functools.reduce(lambda s, n: 5 * s + n, l, 0)

def part2(data):
    """Answer part 2 of https://adventofcode.com/2021/day/10"""
    score = { '(': 1, '[': 2, '{': 3, '<': 4, }
    completion = list()
    for line in data:
        stack = list()
        for c in line:
            if c in lefts:
                stack.append(c)
            if c in rights and not match(stack.pop(), c):
                stack = None
                break
        if stack:
            completion.append(accum([ score[c] for c in reversed(stack) ]))
    return sorted(completion)[(len(completion) // 2)]
print(part2(data))

# AOC 2021 10
['<[<<<<[{[<({{({}<>)<[]{}>}[<<>{}>{<>{}}]}{(({}<>){()<>}){{[]<>}{[]}}})>([{{(()[])[{}()]}}(<{{}<>}', '<<[<<{[<<<{{<(()[])>[({}{})]}}({{({}())[<>{}]}}{{(<><>)[<>()]}<<<>{}><<>()>>})>{[[<(<>[])[[]{}]>{{[]<>}<[]', '<[{<<(<([{<[<{()<>}<{}[]>>([<>()]{<>()})]{[([][])<{}<>>][<<><>>]}>}][[[<{{[]{}}[[][]]}([{}[]]<[]<>', '<{[(<<[({([{<[{}[]]{<>{}}>}[(({}()){[]<>])]]{{<<[]>([]<>)><<{}()>{<>[]}>}{({<><>}<<>{}>){(()[])<()<>>}}})', '[{<{[(({[[<<<<<>()>{(){}}>[{[]{}}(<><>)]>{[<[][]>(()<>)]<<[]()><()()>>}>])}(<{<[<<{}[]>>{[()[]]({}{})}]>{', '[<{<[[[<{[<<[{<>{}}<(){}>]{<{}{}><{}{}>}>{<(()<>){<><>}>}><[<{{}()}>{{<>()}{()<>}}]({<{}<>>}[{()<>}[()()]])', '(([(<({[<<({{<()()]{[]{}}}[{<>()}[[]()]]}({[<><>]}<[<>{}][()<>]>)){{[[[]<>]<<><>>](({}{}){{}()})}}>>]})>)<((', '(<<({((<<(<{([()]<()[]>)}[{(()<>)(()())}{{()<>}<()()>}]>)({[<(<>())((){})><{<><>}[{}<>]>][[[<>', '[(<([{[[[{{{([()()]([]()))[<[][]>[<><>]]}{(<[]>[(){}]){[<>{}]{{}()}}}>[<<[[][]][{}()]>[<<>{}>', '{<{[[[{<<([({[<><>][(){}]}({(){}}[{

---
## https://adventofcode.com/2021/day/11 &mdash; Dumbo Octopus

This puzzle took **a lot** of experimentation with the sample data to get it right. The biggest *aha* was the need to remember which octopusses had flashed and (a) only flash them once and (b) only zero out the octopusses that had flashed after *all* had finished flashing. That required a `set` in addition to the 2D `data` values.

## Utilities

The solutions to both parts was facilitated by the `flash` function &mdash; that increments the 8 levels of octopusses around a specific octopus &mdash; and the `step` function that performs the 3 operations:

- Increment all octopusses.
- Flash any flashable but unflashed octopusses.
- Zero out flashed octopusses.

## Part 1

This part asks to keep track of the number of flashes after 100 steps.

### Strategy

- parse the data into a 2D list of lsts of integers.
- `step` 100 times, keeping track of the `flashes`.
- report the total number of the `flashes`.

## Part 2

This part asks to find the step at which all the octopusses have flashed simultaneously.

### Strategy

- parse the data into a 2D list of lsts of integers.
- `step` until all octopusses have flashed simultaneously, keeping track of `steps`.
- report the total number of the `steps`.

In [11]:
#!/usr/bin/env python3
#
# https://adventofcode.com/2021/
#
# AOC 2021 11
#
# aoc202111.py
#

print('# AOC 2021 11')

# Sample data for AOC 2021 11
data = [ [ int(n) for n in x ] for x in """
5483143223
2745854711
5264556173
6141336146
6357385478
4167524645
2176841721
6882881134
4846848554
5283751526
""".split('\n') if x ]

data = [ [ int(n) for n in x ] for x in """
4585612331
5863566433
6714418611
1746467322
6161775644
6581631662
1247161817
8312615113
6751466142
1161847732
""".split('\n') if x ]
print(data)

def flash(data, row, col):
    """Increase 8 levels of octopus around (row, col, )."""
    the8 = [
        (row - 1, col - 1, ), (row - 1, col, ), (row - 1, col + 1, ),
        (row, col - 1, ),                       (row, col + 1, ),
        (row + 1, col - 1, ), (row + 1, col, ), (row + 1, col + 1, ),
    ]
    for r, c in the8:
        if r >= 0 and r < len(data) and c >= 0 and c < len(data[r]):
            data[r][c] += 1

new_flashes = lambda d, f: any([ d[r][c] > 9 and (r, c, ) not in f
    for r in range(len(d)) for c in range(len(d[r])) ])

def step(data, flashes, steps):
    """Return data, flashes, and steps + 1 after a single step."""
    # Increment all octopusses.
    data, flashed = [ [ n + 1 for n in row ] for row in data ], set()
    while new_flashes(data, flashed):
        for r in range(len(data)):
            for c in range(len(data[r])):
                # Flash any flashable but unflashed octopusses.
                if data[r][c] > 9 and (r, c, ) not in flashed:
                    flash(data, r, c)       # flash this one
                    flashed.add((r, c, ))   # remember which one flashed
                    flashes += 1            # keep track of flashes
    # Zero out flashed octopusses.
    data = [ [ 0 if (r, c, ) in flashed else data[r][c]
        for c in range(len(data[r])) ]
            for r in range(len(data)) ]
    return data, flashes, steps + 1

def part1(data):
    """Answer part 1 of https://adventofcode.com/2021/day/11"""
    flashes, steps = 0, 0
    for i in range(100):
        data, flashes, steps = step(data, flashes, steps)
    return flashes
print(part1(data))

all_zero = lambda d: all([ d[r][c] == 0
    for r in range(len(d)) for c in range(len(d[r])) ])

def part2(data):
    """Answer part 2 of https://adventofcode.com/2021/day/11"""
    flashes, steps = 0, 0
    while not all_zero(data):
        data, flashes, steps = step(data, flashes, steps)
    return steps
print(part2(data))

# AOC 2021 11
[[4, 5, 8, 5, 6, 1, 2, 3, 3, 1], [5, 8, 6, 3, 5, 6, 6, 4, 3, 3], [6, 7, 1, 4, 4, 1, 8, 6, 1, 1], [1, 7, 4, 6, 4, 6, 7, 3, 2, 2], [6, 1, 6, 1, 7, 7, 5, 6, 4, 4], [6, 5, 8, 1, 6, 3, 1, 6, 6, 2], [1, 2, 4, 7, 1, 6, 1, 8, 1, 7], [8, 3, 1, 2, 6, 1, 5, 1, 1, 3], [6, 7, 5, 1, 4, 6, 6, 1, 4, 2], [1, 1, 6, 1, 8, 4, 7, 7, 3, 2]]
1571
387


---
## https://adventofcode.com/2021/day/12 &mdash; Passage Pathing

## Part 1

This part asks

### Strategy

- parse the data

## Part 2

This part asks to find

### Strategy

- parse the data

In [12]:
#!/usr/bin/env python3
#
# https://adventofcode.com/2021/
#
# AOC 2021 12
#
# aoc202112.py
#

print('# AOC 2021 12')

# Sample data for AOC 2021 12
data = [ x.split('-') for x in """
dc-end
HN-start
start-kj
dc-start
dc-HN
LN-dc
HN-end
kj-sa
kj-HN
kj-dc
""".split('\n') if x ]

# Sample data for AOC 2021 12
data = [ x.split('-') for x in """
fs-end
he-DX
fs-he
start-DX
pj-DX
end-zg
zg-sl
zg-pj
pj-he
RW-he
fs-DX
pj-RW
zg-RW
start-pj
he-WI
zg-he
pj-fs
start-RW
""".split('\n') if x ]

data = [ x.split('-') for x in """
bm-XY
ol-JS
bm-im
RD-ol
bm-QI
JS-ja
im-gq
end-im
ja-ol
JS-gq
bm-AF
RD-start
RD-ja
start-ol
cj-bm
start-JS
AF-ol
end-QI
QI-gq
ja-gq
end-AF
im-QI
bm-gq
ja-QI
gq-RD
""".split('\n') if x ]
print(data)

def nodes(data):
    """Return dict of nodes from pairs in data. Do not include 'end' as a key."""
    nodes = dict()
    for s, e in data:
        # Do not include a key for 'end'.
        if s != 'end': nodes[s] = nodes.get(s, list()) + [e]
        if e != 'end': nodes[e] = nodes.get(e, list()) + [s]
    return nodes

flat = lambda l2d: sorted([ l2d[i][j] for i in range(len(l2d)) for j in range(len(l2d[i])) ])

def path(paths, nodes, add=lambda n, p: False):
    """Return all paths that end with 'end' by following nodes.
    add is an additional criterion for adding nodes to the path."""
    update = list()
    for p in paths:
        update += [p] if p[-1] == 'end' else \
            [ p + [n] for n in nodes[p[-1]]
                if n == n.upper() or n not in p or add(n, p) ]
    return paths if flat(paths) == flat(update) else path(update, nodes, add)

def part1(data):
    """Answer part 1 of https://adventofcode.com/2021/day/12"""
    return len([ p for p in path([['start', ], ], nodes(data))
        if p[0] == 'start' and p[-1] == 'end' ])
print(part1(data))

# p has only 1 of each lowercase n and n is not 'start'.
only1 = lambda n, p: n != 'start' \
    and sorted([ n for n in p if n == n.lower() ]) \
    == sorted(set([ n for n in p if n == n.lower() ]))

def part2(data):
    """Answer part 2 of https://adventofcode.com/2021/day/12"""
    return len([ p for p in path([['start', ], ], nodes(data), only1)
        if p[0] == 'start' and p[-1] == 'end' ])
print(part2(data))

# AOC 2021 12
[['bm', 'XY'], ['ol', 'JS'], ['bm', 'im'], ['RD', 'ol'], ['bm', 'QI'], ['JS', 'ja'], ['im', 'gq'], ['end', 'im'], ['ja', 'ol'], ['JS', 'gq'], ['bm', 'AF'], ['RD', 'start'], ['RD', 'ja'], ['start', 'ol'], ['cj', 'bm'], ['start', 'JS'], ['AF', 'ol'], ['end', 'QI'], ['QI', 'gq'], ['ja', 'gq'], ['end', 'AF'], ['im', 'QI'], ['bm', 'gq'], ['ja', 'QI'], ['gq', 'RD']]
3887
104834


---
## https://adventofcode.com/2021/day/13 &mdash; Transparent Origami

## Part 1

This part asks

### Strategy

- parse the data

## Part 2

This part asks to find

### Strategy

- parse the data

In [13]:
#!/usr/bin/env python3
#
# https://adventofcode.com/2021/
#
# AOC 2021 13
#
# aoc202113.py
#

print('# AOC 2021 13')

data = [ (int(x), int(y), ) for x, y in [ x.split(',') for x in """
470,705
331,196
1241,728
1034,161
181,850
999,484
480,680
798,33
226,86
475,226
113,287
770,702
47,35
848,312
1129,402
179,326
766,404
1258,717
470,494
723,434
418,291
100,298
994,316
423,434
985,292
721,261
528,572
595,567
909,665
411,292
1056,291
1051,434
311,484
462,312
187,273
715,567
114,819
634,861
79,318
912,344
1144,845
152,745
201,464
840,185
291,100
1084,31
1255,434
909,229
895,827
557,29
441,159
661,193
826,215
535,70
974,767
254,739
512,189
868,75
1076,9
700,86
684,515
356,422
348,344
605,341
360,586
383,824
239,393
751,12
253,229
403,759
166,273
1196,819
406,301
343,102
1119,618
333,892
711,789
283,70
418,603
380,714
756,255
20,375
1145,794
642,180
1140,273
984,451
763,619
196,427
869,159
460,96
35,548
512,709
1231,318
1163,21
465,275
32,187
212,296
718,835
1036,42
1002,672
108,492
321,892
294,0
252,350
377,733
1196,822
316,344
254,519
1168,49
1158,745
142,49
130,504
397,56
718,186
463,170
482,463
1032,752
649,193
512,158
895,501
1150,122
537,833
915,434
790,262
1058,539
764,44
512,861
493,296
472,422
44,86
1101,592
671,276
977,2
822,621
179,668
415,46
1067,154
895,169
475,728
231,434
156,103
1176,72
113,607
301,851
927,824
346,870
892,603
610,86
1114,19
295,353
402,350
1118,145
201,318
681,732
338,792
855,733
202,364
125,430
1140,285
917,309
1309,542
10,540
246,499
1038,178
209,609
242,16
10,214
20,519
276,173
540,520
192,582
681,891
830,680
600,44
895,848
1009,219
425,442
1049,185
994,166
1034,733
453,240
605,833
154,71
141,607
840,494
131,87
1084,86
1193,592
1163,166
847,724
329,318
567,46
850,798
554,255
817,598
723,658
1027,70
1154,103
822,273
704,290
985,72
386,593
1015,353
907,435
867,847
711,835
415,718
903,343
252,539
574,310
295,801
156,733
1173,395
736,218
700,360
865,144
1044,240
708,628
354,262
1298,42
987,250
857,430
184,185
1066,14
130,894
917,585
882,596
156,791
868,296
1248,29
1300,354
1180,504
542,385
710,850
172,407
1064,310
962,166
458,504
992,295
517,667
95,12
484,299
523,390
865,733
326,82
1300,91
69,728
470,548
1015,541
141,735
278,756
1237,140
642,714
728,71
1064,666
1128,477
301,403
677,159
340,266
984,812
972,792
212,374
828,463
987,810
1109,318
212,178
1275,548
1016,894
962,128
840,548
10,149
933,833
80,411
1136,883
676,766
421,632
242,786
131,721
274,189
407,576
80,35
393,361
425,421
184,397
1101,196
1154,411
529,878
711,518
1223,270
579,459
343,838
428,415
933,733
930,628
55,294
1226,336
378,721
435,553
546,492
1019,100
763,684
1076,885
1150,772
276,876
574,51
25,610
117,644
410,563
311,838
192,817
626,696
1309,352
604,18
1036,705
782,124
338,464
502,774
1243,882
950,756
1232,593
25,284
853,173
1295,614
1144,534
44,534
1118,312
954,515
410,747
806,348
1193,644
1248,59
700,836
247,318
1121,739
681,715
1185,430
759,103
459,504
981,292
1131,668
798,64
728,39
251,435
688,187
326,451
828,351
654,869
723,712
1300,680
442,598
1310,645
688,222
994,344
277,833
309,318
26,184
711,387
418,515
1109,436
274,705
1131,813
618,614
229,298
388,128
411,366
125,464
3,362
131,173
1216,772
830,540
572,115
922,576
830,214
520,184
895,718
808,203
443,847
729,453
781,240
1078,794
1282,144
196,390
502,203
992,711
557,588
934,828
1010,632
212,520
174,11
976,630
1066,147
913,822
731,459
213,93
244,270
306,791
254,155
103,103
671,52
1128,271
1010,262
62,708
412,556
5,193
294,446
828,95
201,458
838,271
47,859
314,628
425,473
571,654
994,540
567,841
236,575
141,287
197,621
480,206
868,534
435,822
62,59
363,346
1056,739
201,10
994,680
907,135
974,743
1168,64
380,180
247,103
1225,747
841,287
79,352
295,161
393,306
864,646
1158,149
348,128
348,469
189,739
199,285
318,711
888,794
1109,458
1068,108
463,724
397,822
1255,294
917,185
272,716
706,466
979,644
887,460
1053,838
1131,226
1173,787
979,196
557,865
441,735
1290,519
1044,576
1222,854
989,165
107,723
1238,155
67,460
1238,71
1213,726
443,47
316,166
711,105
498,273
70,102
65,585
475,442
599,789
32,873
1012,379
623,609
10,91
569,147
1067,814
580,798
321,2
209,196
967,410
1230,411
1282,870
731,87
736,859
294,894
546,402
334,630
559,12
651,196
65,261
1149,598
473,492
393,452
629,491
480,763
1202,44
1261,61
1056,519
992,127
972,430
740,562
344,290
882,479
45,644
1193,302
1113,273
58,525
718,865
400,515
1084,479
1074,603
835,450
316,728
480,373
1154,733
892,575
1097,129
353,59
1136,688
1128,422
547,619
587,182
962,344
622,707
626,198
1154,483
75,135
277,161
894,406
278,534
951,609
711,152
70,550
738,432
907,759
882,534
923,327
933,229
383,294
25,3
1009,851
507,614
174,883
295,129
276,428
446,86
318,767
703,859
1094,710
480,688
1184,124
336,127
923,567
790,184
1285,284
152,579
599,742
1197,287
639,500
467,273
785,495
300,262
855,285
277,285
267,567
403,459
1179,56
1029,801
551,103
1289,159
415,515
97,596
1109,884
885,227
166,534
213,129
927,70
472,623
1113,49
480,354
166,397
1034,721
629,610
376,590
442,411
676,861
1230,859
1068,878
278,590
49,161
899,528
759,791
1071,169
1230,758
1032,380
271,387
974,711
0,197
70,400
806,856
987,698
1038,380
395,460
793,107
376,828
405,152
78,301
256,550
1113,497
892,274
853,721
783,865
397,166
579,87
243,154
454,280
999,500
898,502
55,600
621,161
786,894
1144,808
192,134
1126,285
196,245
1290,833
1223,501
847,276
835,452
1228,523
653,542
413,250
1200,490
278,304
813,365
582,855
633,735
520,710
398,344
1145,122
740,332
1131,529
544,180
1039,61
363,548
981,740
830,521
674,865
736,676
300,632
671,170
572,299
185,607
907,459
1196,72
687,285
196,19
55,434
999,813
288,754
446,646
981,154
587,460
323,810
1126,497
110,714
512,326
830,354
1232,301
266,240
172,487
1208,152
618,280
766,714
721,633
316,680
987,523
147,614
672,380
467,173
253,665
840,189
673,878
944,754
278,75
1163,813
927,294
1310,197
1183,865
47,488
152,315
472,477
770,371
388,766
108,44
863,294
629,715
1043,775
924,593
1179,838
703,655
1213,596
985,766
830,11
1031,721
623,285
130,448
380,628
72,739
84,749
977,729
318,183
229,227
687,733
179,564
415,270
606,138
1274,280
295,541
1054,550
610,836
239,583
524,894
383,600
1102,808
830,883
828,543
686,845
252,544
832,490
1109,10
1009,267
869,765
822,360
928,716
1118,817
1063,103
10,680
497,813
295,609
1230,310
1042,145
1144,397
70,494
226,31
378,466
401,441
592,29
257,838
366,754
174,540
1253,49
78,593
903,576
764,828
382,716
793,499
1063,576
316,878
1128,417
1298,266
520,262
10,354
388,576
403,435
393,451
626,750
610,58
279,721
358,574
239,400
1010,184
1253,845
415,67
867,47
1032,75
1156,519
254,827
582,603
360,696
1071,311
246,666
353,851
838,477
320,182
835,220
1282,24
200,280
57,845
504,856
741,182
242,430
291,794
""".split('\n') if x ] ]
print(data)

folds = [ (c, int(n), ) for c, n in [ x.split()[2].split('=') for x in """
fold along x=655
fold along y=447
fold along x=327
fold along y=223
fold along x=163
fold along y=111
fold along x=81
fold along y=55
fold along x=40
fold along y=27
fold along y=13
fold along y=6
""".split('\n') if x ] ]
print(folds)

def fold(data, folds, v=True):
    """Calcualte folds and return set of remaining points."""
    points, pointer = set(data), '--> '
    if v: print(len(points), points)
    for c, n in folds:
        if c == 'x':
            points = { (x, y,) if x < n else (n - (x - n), y, ) for x, y in points }
        if c == 'y':
            points = { (x, y,) if y < n else (x, n - (y - n), ) for x, y in points }
        if v: print(f"{pointer}{len(points)} {points}")
        pointer = ''
    return points

def part1(data, folds):
    """Answer part 1 of https://adventofcode.com/2021/day/13"""
    return fold(data, folds)
print(part1(data, folds))

def part2(data, folds):
    """Answer part 2 of https://adventofcode.com/2021/day/13"""
    points = fold(data, folds, False)
    xs, ys = [ x for x, y in points], [y for x, y in points]
    xmin, ymin, xmax, ymax = min(xs), min(ys), max(xs), max(ys)
    grid = [ [ '.' for c in range(xmin, xmax + 1) ] for r in range(ymin, ymax + 1) ]
    for c, r in points:
        grid[r - ymin][c - xmin] = '#'
    return '\n'.join([ ''.join(r) for r in grid ])

print(part2(data, folds))

# AOC 2021 13
[(470, 705), (331, 196), (1241, 728), (1034, 161), (181, 850), (999, 484), (480, 680), (798, 33), (226, 86), (475, 226), (113, 287), (770, 702), (47, 35), (848, 312), (1129, 402), (179, 326), (766, 404), (1258, 717), (470, 494), (723, 434), (418, 291), (100, 298), (994, 316), (423, 434), (985, 292), (721, 261), (528, 572), (595, 567), (909, 665), (411, 292), (1056, 291), (1051, 434), (311, 484), (462, 312), (187, 273), (715, 567), (114, 819), (634, 861), (79, 318), (912, 344), (1144, 845), (152, 745), (201, 464), (840, 185), (291, 100), (1084, 31), (1255, 434), (909, 229), (895, 827), (557, 29), (441, 159), (661, 193), (826, 215), (535, 70), (974, 767), (254, 739), (512, 189), (868, 75), (1076, 9), (700, 86), (684, 515), (356, 422), (348, 344), (605, 341), (360, 586), (383, 824), (239, 393), (751, 12), (253, 229), (403, 759), (166, 273), (1196, 819), (406, 301), (343, 102), (1119, 618), (333, 892), (711, 789), (283, 70), (418, 603), (380, 714), (756, 255), (20, 375), (114

---
## https://adventofcode.com/2021/day/14 &mdash; Extended Polymerization

## Part 1

This part asks

### Strategy

- parse the data

## Part 2

This part asks to find

### Strategy

- parse the data

In [14]:
#!/usr/bin/env python3
#
# https://adventofcode.com/2021/
#
# AOC 2021 14
#
# aoc202114.py
#

print('# AOC 2021 14')

# Sample data for AOC 2021 14
start = 'NNCB'
data = { tuple(k): v for k, v in [ x.split(' -> ') for x in """
CH -> B
HH -> N
CB -> H
NH -> C
HB -> C
HC -> B
HN -> C
NN -> C
BH -> H
NC -> B
NB -> B
BN -> B
BB -> N
BC -> B
CC -> N
CN -> C
""".split('\n') if x ] }

start = 'SHHNCOPHONHFBVNKCFFC'
data = { tuple(k): v for k, v in [ x.split(' -> ') for x in """
HH -> K
PS -> P
BV -> H
HB -> H
CK -> F
FN -> B
PV -> S
KK -> F
OF -> C
SF -> B
KB -> S
HO -> O
NH -> N
ON -> V
VF -> K
VP -> K
PH -> K
FF -> V
OV -> N
BO -> K
PO -> S
CH -> N
FO -> V
FB -> H
FV -> N
FK -> S
VC -> V
CP -> K
CO -> K
SV -> N
PP -> B
BS -> P
VS -> C
HV -> H
NN -> F
NK -> C
PC -> V
HS -> S
FS -> S
OB -> S
VV -> N
VO -> P
KV -> F
SK -> O
BC -> P
BP -> F
NS -> P
SN -> S
NC -> N
FC -> V
CN -> S
OK -> B
SC -> N
HN -> B
HP -> B
KP -> B
CB -> K
KF -> C
OS -> B
BH -> O
PN -> K
VN -> O
KH -> F
BF -> H
HF -> K
HC -> P
NP -> H
KO -> K
CF -> H
BK -> O
OH -> P
SO -> F
BB -> F
VB -> K
SP -> O
SH -> O
PK -> O
HK -> P
CC -> V
NB -> O
NV -> F
OO -> F
VK -> V
FH -> H
SS -> C
NO -> P
CS -> H
BN -> V
FP -> N
OP -> N
PB -> P
OC -> O
SB -> V
VH -> O
KS -> B
PF -> N
KN -> H
NF -> N
CV -> K
KC -> B
""".split('\n') if x ] }
print(start, data)

convert = lambda s, d: sum([ d[n] * 10 ** i for i, n in enumerate(s) ])
def transform(data):
    """Transform a data dict of pair insertion rules to numbers."""
    all = set([ l for k, v in data for l in k ]) | set(data.values())
    map = { l: i for i, l in enumerate(sorted(all)) }
    rules = { convert(k, map): convert(v, map) for k, v in data.items() }
    return map, rules
m, r = transform(data)
print(m, r)
print(convert(start, m))

import math
def polymer(data, start, steps):
    """Return polymer built starting from start using data pair-insertion rules."""
    map, rules = transform(data)
    poly = convert(start, map)
    print(poly // 10 ** (len(start) - 1))
    for i in range(steps):
        temp, length = 0, len(start) - 1 << i
        for j in range(length):
            p = 10 ** j
            temp += (poly // p % 10 + rules[poly // p % 100] * 10) * 10 ** (2 * j)
        poly = temp + poly // 10 ** length * 10 ** (length * 2)
        if i < 5: print(poly)
        print(f"{i} {round(math.log(poly))}")
    return poly

def part1(data, start):
    """Answer part 1 of https://adventofcode.com/2021/day/14"""
    poly = polymer(data, start, 10)
    dist = dict()
    for i in range((len(start) - 1 << 10) + 1):
    #while poly > 0:
        dist[poly % 10] = dist.get(poly % 10, 0) + 1
        poly //= 10
    print(dist, sum(dist.values()))
    return max(dist.values()) - min(dist.values())

print(part1(data, start))

def part2(data, start):
    """Answer part 2 of https://adventofcode.com/2021/day/14"""
    poly = polymer(data, start, 10)
    dist = dict.fromkeys(set(poly), 0)
    print(dist)
    for c in poly:
        dist[c] += 1
    return max(dist.values()) - min(dist.values())
#print(part2(data, start))

# AOC 2021 14
SHHNCOPHONHFBVNKCFFC {('H', 'H'): 'K', ('P', 'S'): 'P', ('B', 'V'): 'H', ('H', 'B'): 'H', ('C', 'K'): 'F', ('F', 'N'): 'B', ('P', 'V'): 'S', ('K', 'K'): 'F', ('O', 'F'): 'C', ('S', 'F'): 'B', ('K', 'B'): 'S', ('H', 'O'): 'O', ('N', 'H'): 'N', ('O', 'N'): 'V', ('V', 'F'): 'K', ('V', 'P'): 'K', ('P', 'H'): 'K', ('F', 'F'): 'V', ('O', 'V'): 'N', ('B', 'O'): 'K', ('P', 'O'): 'S', ('C', 'H'): 'N', ('F', 'O'): 'V', ('F', 'B'): 'H', ('F', 'V'): 'N', ('F', 'K'): 'S', ('V', 'C'): 'V', ('C', 'P'): 'K', ('C', 'O'): 'K', ('S', 'V'): 'N', ('P', 'P'): 'B', ('B', 'S'): 'P', ('V', 'S'): 'C', ('H', 'V'): 'H', ('N', 'N'): 'F', ('N', 'K'): 'C', ('P', 'C'): 'V', ('H', 'S'): 'S', ('F', 'S'): 'S', ('O', 'B'): 'S', ('V', 'V'): 'N', ('V', 'O'): 'P', ('K', 'V'): 'F', ('S', 'K'): 'O', ('B', 'C'): 'P', ('B', 'P'): 'F', ('N', 'S'): 'P', ('S', 'N'): 'S', ('N', 'C'): 'N', ('F', 'C'): 'V', ('C', 'N'): 'S', ('O', 'K'): 'B', ('S', 'C'): 'N', ('H', 'N'): 'B', ('H', 'P'): 'B', ('K', 'P'): 'B', ('C', 'B'): 

---
## https://adventofcode.com/2021/day/15 &mdash; Chiton

## Part 1

This part asks

### Strategy

- parse the data

## Part 2

This part asks to find

### Strategy

- parse the data

In [15]:
#!/usr/bin/env python3
#
# https://adventofcode.com/2021/
#
# AOC 2021 15
#
# aoc202115.py
#

print('# AOC 2021 15')

# Sample data for

data = [ [ int(n) for n in list(x) ] for x in """
1163751742
1381373672
2136511328
3694931569
7463417111
1319128137
1359912421
3125421639
1293138521
2311944581
""".split('\n') if x ]

data = [ [ int(n) for n in list(x) ] for x in """
7135912411912798932871391322889941544645211112288183969191588665579426181549613954113914616349281119
8818482819182139319112316373697999126211219541956811442497469891197212131227119531231231297911937841
1514575112959236914131559711156719336447259942553728322911271774241293394881913682176891871931225931
3911411211611179328267522115348239963876196416413136271519591723261183181259792938429689524986199662
7641142151561121642912253491632132312682391976219236246811321441614458168298442897517119286294427143
2121192132289162313728563181871122493359816197929334844219181379799666376121879896792359861963352341
7824634877975124922137296299957468954179392824124437392871314337752916614225212219614414683959191151
4697413917922193912419678321922133939613861216689158123571322738228138479426524278182172119312848883
8924576358796711856729358848547891622733114113537182199512138345191419912781799661213494977849752719
9132169172714432689989487585816291188372945729446982887385921614921294423815188486235978437499258722
9929612116117322929192611415689558648414234962111998328276736614756763995581743581596537519892142521
6859462858823445699961194293368522127111119151871541859481733312151116149914179449331819839353155113
8988116192491137816954351881298779248676485369639447862482485217115384714391817295351133512843746966
7571297119217394373851931827249232122997672148435518981284665125835621941441532141274393695122619314
3939863898771614631946691997721854917392211921111728141868588118885471347186178748851776892861438443
2155858821839528992349995595944111672471514987919211316318272884633628411528621318162698112862229923
2691764214377199693151237477259942269443921791894817178521112414184311435491289747591145199572891861
2183942132282912239178796993312121721766259916716468139198515826259948419825368918945525463932414235
9154869181176678119983249451922785744127441495675634793648176729934175835771217248334139962527974988
8316744932991141279996315662192146345781219556153198919381318996543312112711981728293841548111952196
1678649394142988654712416121184133779252711945121896991914229495253651999438942623918521884672772847
2188335827591362911271449532775346481117326676931792861349422858831552256823539837899371212511711813
1137111476222151188969945128797252113619562499638219193695753685119112178441254646513776815961119391
1311494299181429199922894135898194891799252689612799393219881531897359146294437998966817122264298246
7869971941425993845734716136911492866591595142713692655681732461441353982895789121752626869711378115
9239951784171297254939792866381495619396182347224976131529736151479936377316511523536618939221132899
7581784265611979969632696671661117125328674794912934429399563111498429917632932111221563912112515273
7367291592679814612371895444265262975496492458115911411475523864214631973161319915171412551791413376
6143589915761117133161228522845431711285983623123914475415191119611426132353137122133138131833612241
7315896136915814193423598722861235221151383267818971821574386831514941997259725791289186442371844418
2944988532619915833681566922831548513196692639711234911281599216462185722897881931171312789137243721
3415172717189389569477924294841849972631114691111623229683952159862188171818115133384485154497599559
1443919891944499961536175263268527116362122922287285719966998199199441931137574959919144151197817839
9774211468397683929442718999171788895916913394193919232141112487256919224143149441799394272131971871
3198272448962643191324588811488161219314122782581211597498382898541626779286175517151236427512269349
2641494257999752612311911198184769891171431782812383711226539636119129192822936482141279883592179266
2119972469619139184934989573412475621816182148681881122375284211995236284989831151661817931779422112
7295958272613111691177736161533154911323159856156237541831115325212648628989877768131262418812991296
9179734481249251841492271271519693142191924942413892511575142934295889198126293312336342918151758162
1918288372217685211881621182876373641278237319193188611518466628913951431547316142239282889861971168
6481288831198825137983699584119844171277298465968692235991695699839824893811316389191284779455458926
8396111649592147388769281297398198661114743131873363398675119721739926264694823462335131594481481373
2434215191197181483294466759973649632193194912131483571345665393945693919958491191412791223154934727
7871951292356181798923129711323861114141919495144297269813147499439323419895693812252459742998597441
1574717591196738322951111198251131842829721216144119624318859125151713218899752276339146481494861892
1819991568362993452123883231325566449151533275721919561992199831792982843649316477921121367147112896
7164846864939958375749731419384111621136661946642611971828921433914128176165123794829624567184522488
4785123474241882671572457297581589514786127561961119193971931191877171612248351111414768782178179192
6227491725442145283239476196991134314139115335311416974791813981549591345151138264431591871129924992
9525981188584231132225439982816211118263916789496251772415921912198419411784321547231797226171319518
5276492419192822328129329248691592169731892693238887119782761121281198881289143311556111145762141969
3128271331163834865261684351337989624523993845875478623191688489571627219561929218973142745155346265
4193551178487292216333184531282141936739498223496986982695779191177684516564996992993218533675828331
2178191346196125243262494112463518611452132231119193528129991178147134976927614139217336689471498249
6129713279458826397211359112797612571949711626579326212321673631424994612159994119946275596513947795
3513497921274818281264559359411281941591491117122122513632133498123984489432938585627194427716713591
3735691482998186339938618867117735735847168696112281481791121411985468672769129111298118716916287399
1871918977115917121139294513119138122212125991828911437898741676491287516364929242332123121247291921
2172938726152562311291781426375458965363121645283962593961676981631211918396931794147343949131142886
3563293612799972919112123214912219918111635798791497828431231792831311217641761129849469863965344918
1199166791334792849211686283551172171219541419495341213428632733677312221229433611169995941144111147
6394369495897282264742163299416336447831867811285891952214644819921138169319196919342859116381114162
1373926897138229918126319121589683666822323221358191793312332391875371695224911132182819762271622842
1395938837219999119653897313168437621521184698183523953888133528386521187834914545761589174121311297
9148392198938912815631892856379782259177441991512171923741241392634839192197699439238712971285121718
9617115534391147936286149747257196999197226833236193228161416125387152377324271993189142587565889216
1138362373562714886584858791749611811391259594249851471911421657411858414811911739328179589614345311
2123263137952269324948912289526328291197821918189951818829272897911921983618661121229352371999183526
5364542519321819925791596927167149711914374975527491381956921757465199133213416132899957474191996977
1929347192289551889583428247594612171742195719193841918882922816292422493651515188151411754731924869
1692134868984869947615245132531711235666968796975199664129196512199668151246836942177187915931113294
7118262375923241337938127228199296914375632221737416368412524122981911769239158321157253335191842293
3265737381753813995198616644314148942312543211211966982383799621211653591584222576569677423117196363
9111924341513711995134611113399813147951464737687954215191822862835181297749588181342888512621814237
3947613151114693862482811617516971318912913889228941136129781272113943413319524119274915826444984968
5124181549192167218912741168272953789192961976729911857199221329892492339197918893411144398169336194
1485129117199312786562116458324116828444543126133413128119541914771248211512152882987215871197292423
7422889855487415671335853281581333169614425918126836514342948114194791483915918432221121929323211132
1397784733219914119249936528322918311193215184294314164148919316331195897687294516359772213253697211
4717364471215123665331721971981229594119554941752216989211613831529573361213916861111893555851517418
4475292919699311784787119799878541261915191691592987284894722138693167937451131188958781235581483286
1714644391788411669199191897458772783119829374655796257128313876192611966566911569752913319295999161
5353589995929755657711912453381161722689758111263452119611629592723857772946211138911548213132414261
2323191817916231415963297418916213749962744352527498552191811131527176211561691378514642127964489253
8152739983512395662414199891116913122891128119944989152213551956193871323119712519943171227126393112
4277581221626287191599922889219313146698155917772441677491134651142134839446179968189181111117921264
1529718132292294511939933926184891864671981421194613891858891618413249116991111313819714816391282114
2736713356811187816216326169766914131244193378437739141121325532382168695918714583941211765269841845
6861393358329912377611366412273921772179929351971811612713977218371523129424314194646292115794965959
3679491485643668398349312922716981614177469361188111177278192895776778119176811991694871925591898988
7848791135845793449869357967261811862593411114238191934518272187499291243315361136315316349516559897
2411183429933422439362133562818449269911144591895315983271911239311885918348116127395818295417142197
1149999499271716641741695755112598414296811143775898536992648741825632691771283631891964299913386859
7697191119989531956155347154456132115329827725927411161313639157441831911577982311114748522118581583
1815888198921498665618218659132911455457193212697148817464169664117619551412423137492313588316296486
9485595239675134411169618995341912442884121821776319272924315115347989581919156755236917322517294195
9781159216631418625141321358419192261944897168929996578364222131392382311288714992416184543214582115
5163463131885451189428292988121225981319219157179263733192533612392419373399148619195391911225811356
2199395612171271152392819795216311991115818792511159521265359573629956281827812821311719715781738737
2126356321322111185843117549923315199213385946175489294117624711949445499157452371358923199949713123
""".split('\n') if x ]
print(data)

def branch(data, r, c):
    """Return minimum total from moving left and down."""
    if r == len(data) or c == len(data): return 0
    if r == len(data) - 1: return data[r][c] + branch(data, r, c + 1)
    if c == len(data) - 1: return data[r][c] + branch(data, r + 1, c)
    right = branch(data, r, c + 1)
    down = branch(data, r + 1, c)
    return data[r][c] + min(right, down)

def branch(data, r, c):
    """Return minimum total from moving left and down."""
    if r == 0 and c == 0: return 0
    if r == 0: return data[r][c] + branch(data, r, c + 1)
    if c == len(data) - 1: return data[r][c] + branch(data, r + 1, c)
    right = branch(data, r, c + 1)
    down = branch(data, r + 1, c)
    return data[r][c] + min(right, down)

str2d = lambda l: '[' + '\n '.join([ ','.join([ f"{i:03d}" for i in r ]) for r in l]) + ']'
def part1(data):
    """Answer part 1 of https://adventofcode.com/2021/day/15"""
    result = [ [ 0 for c in range(len(data[r])) ] for r in range(len(data)) ]
    # result[0][0] = data[0][0]
    # data = list(reversed([ list(reversed(l)) for l in data ]))
    print(str2d(data))
    for r in range(1, len(data)): result[r][0] = data[r][0] + result[r - 1][0]
    for c in range(1, len(data[0])): result[0][c] = data[0][c] + result[0][c - 1]
    for r in range(1, len(data)):
        for c in range(1, len(data[r])):
            top, left = result[r - 1][c], result[r][c - 1]
            result[r][c] = data[r][c] + min(top, left)
            # print(r, c); print(str2d(result))
    print(str2d(result))
    return result[-1][-1]
print(part1(data)) # 441
print(branch(data, 0, 0) - data[0][0])

def part2(data):
    """Answer part 2 of https://adventofcode.com/2021/day/15"""
print(part2(data))

# AOC 2021 15
[[7, 1, 3, 5, 9, 1, 2, 4, 1, 1, 9, 1, 2, 7, 9, 8, 9, 3, 2, 8, 7, 1, 3, 9, 1, 3, 2, 2, 8, 8, 9, 9, 4, 1, 5, 4, 4, 6, 4, 5, 2, 1, 1, 1, 1, 2, 2, 8, 8, 1, 8, 3, 9, 6, 9, 1, 9, 1, 5, 8, 8, 6, 6, 5, 5, 7, 9, 4, 2, 6, 1, 8, 1, 5, 4, 9, 6, 1, 3, 9, 5, 4, 1, 1, 3, 9, 1, 4, 6, 1, 6, 3, 4, 9, 2, 8, 1, 1, 1, 9], [8, 8, 1, 8, 4, 8, 2, 8, 1, 9, 1, 8, 2, 1, 3, 9, 3, 1, 9, 1, 1, 2, 3, 1, 6, 3, 7, 3, 6, 9, 7, 9, 9, 9, 1, 2, 6, 2, 1, 1, 2, 1, 9, 5, 4, 1, 9, 5, 6, 8, 1, 1, 4, 4, 2, 4, 9, 7, 4, 6, 9, 8, 9, 1, 1, 9, 7, 2, 1, 2, 1, 3, 1, 2, 2, 7, 1, 1, 9, 5, 3, 1, 2, 3, 1, 2, 3, 1, 2, 9, 7, 9, 1, 1, 9, 3, 7, 8, 4, 1], [1, 5, 1, 4, 5, 7, 5, 1, 1, 2, 9, 5, 9, 2, 3, 6, 9, 1, 4, 1, 3, 1, 5, 5, 9, 7, 1, 1, 1, 5, 6, 7, 1, 9, 3, 3, 6, 4, 4, 7, 2, 5, 9, 9, 4, 2, 5, 5, 3, 7, 2, 8, 3, 2, 2, 9, 1, 1, 2, 7, 1, 7, 7, 4, 2, 4, 1, 2, 9, 3, 3, 9, 4, 8, 8, 1, 9, 1, 3, 6, 8, 2, 1, 7, 6, 8, 9, 1, 8, 7, 1, 9, 3, 1, 2, 2, 5, 9, 3, 1], [3, 9, 1, 1, 4, 1, 1, 2, 1, 1, 6, 1, 1, 1, 7, 9, 3, 2, 8, 2, 6, 7, 5, 2, 2, 1, 

---
## https://adventofcode.com/2021/day/16 &mdash; Packet Decoder

## Part 1

This part asks

### Strategy

- parse the data

## Part 2

This part asks to find

### Strategy

- parse the data

In [16]:
#!/usr/bin/env python3
#
# https://adventofcode.com/2021/
#
# AOC 2021 16
#
# aoc202116.py
#

print('# AOC 2021 16')

data = [ x for x in """
""".split('\n') if x ]
print(data)

def part1(data):
    """Answer part 1 of https://adventofcode.com/2021/day/16"""
print(part1(data))

def part2(data):
    """Answer part 2 of https://adventofcode.com/2021/day/16"""
print(part2(data))

# AOC 2021 16
[]
None
None


---
## https://adventofcode.com/2021/day/17 &mdash; Trick Shot

## Part 1

This part asks

### Strategy

- parse the data

## Part 2

This part asks to find

### Strategy

- parse the data

In [17]:
#!/usr/bin/env python3
#
# https://adventofcode.com/2021/
#
# AOC 2021 17
#
# aoc202117.py
#

print('# AOC 2021 17')

data = [ x for x in """
""".split('\n') if x ]
print(data)

def part1(data):
    """Answer part 1 of https://adventofcode.com/2021/day/17"""
print(part1(data))

def part2(data):
    """Answer part 2 of https://adventofcode.com/2021/day/17"""
print(part2(data))

# AOC 2021 17
[]
None
None


---
## https://adventofcode.com/2021/day/18 &mdash; Snailfish

## Part 1

This part asks

### Strategy

- parse the data

## Part 2

This part asks to find

### Strategy

- parse the data

In [18]:
#!/usr/bin/env python3
#
# https://adventofcode.com/2021/
#
# AOC 2021 18
#
# aoc202118.py
#

print('# AOC 2021 18')

data = [ x for x in """
""".split('\n') if x ]
print(data)

def part1(data):
    """Answer part 1 of https://adventofcode.com/2021/day/18"""
print(part1(data))

def part2(data):
    """Answer part 2 of https://adventofcode.com/2021/day/18"""
print(part2(data))

# AOC 2021 18
[]
None
None


---
## https://adventofcode.com/2021/day/19 &mdash; Beacon Scanner

## Part 1

This part asks

### Strategy

- parse the data

## Part 2

This part asks to find

### Strategy

- parse the data

In [19]:
#!/usr/bin/env python3
#
# https://adventofcode.com/2021/
#
# AOC 2021 19
#
# aoc202115.py
#

print('# AOC 2021 19')

data = [ x for x in """
""".split('\n') if x ]
print(data)

def part1(data):
    """Answer part 1 of https://adventofcode.com/2021/day/19"""
print(part1(data))

def part2(data):
    """Answer part 2 of https://adventofcode.com/2021/day/19"""
print(part2(data))

# AOC 2021 19
[]
None
None


---
## https://adventofcode.com/2021/day/20 &mdash; Trench Map

## Part 1

This part asks

### Strategy

- parse the data

## Part 2

This part asks to find

### Strategy

- parse the data

In [20]:
#!/usr/bin/env python3
#
# https://adventofcode.com/2021/
#
# AOC 2021 20
#
# aoc202120.py
#

print('# AOC 2021 20')

data = [ x for x in """
""".split('\n') if x ]
print(data)

def part1(data):
    """Answer part 1 of https://adventofcode.com/2021/day/20"""
print(part1(data))

def part2(data):
    """Answer part 2 of https://adventofcode.com/2021/day/20"""
print(part2(data))

# AOC 2021 20
[]
None
None


---
## https://adventofcode.com/2021/day/21 &mdash; Dirac Dice

## Part 1

This part asks

### Strategy

- parse the data

## Part 2

This part asks to find

### Strategy

- parse the data

In [21]:
#!/usr/bin/env python3
#
# https://adventofcode.com/2021/
#
# AOC 2021 21
#
# aoc202121.py
#

print('# AOC 2021 21')

data = [ x for x in """
""".split('\n') if x ]
print(data)

def part1(data):
    """Answer part 1 of https://adventofcode.com/2021/day/21"""
print(part1(data))

def part2(data):
    """Answer part 2 of https://adventofcode.com/2021/day/21"""
print(part2(data))

# AOC 2021 21
[]
None
None


---
## https://adventofcode.com/2021/day/22 &mdash; Reactor Reboot

## Part 1

This part asks

### Strategy

- parse the data

## Part 2

This part asks to find

### Strategy

- parse the data

In [22]:
#!/usr/bin/env python3
#
# https://adventofcode.com/2021/
#
# AOC 2021 22
#
# aoc202115.py
#

print('# AOC 2021 22')

data = [ x for x in """
""".split('\n') if x ]
print(data)

def part1(data):
    """Answer part 1 of https://adventofcode.com/2021/day/22"""
print(part1(data))

def part2(data):
    """Answer part 2 of https://adventofcode.com/2021/day/22"""
print(part2(data))

# AOC 2021 22
[]
None
None


---
## https://adventofcode.com/2021/day/23 &mdash; Amphipod

## Part 1

This part asks

### Strategy

- parse the data

## Part 2

This part asks to find

### Strategy

- parse the data

In [23]:
#!/usr/bin/env python3
#
# https://adventofcode.com/2021/
#
# AOC 2021 23
#
# aoc202123.py
#

print('# AOC 2021 23')

data = [ x for x in """
""".split('\n') if x ]
print(data)

def part1(data):
    """Answer part 1 of https://adventofcode.com/2021/day/23"""
print(part1(data))

def part2(data):
    """Answer part 2 of https://adventofcode.com/2021/day/23"""
print(part2(data))

# AOC 2021 23
[]
None
None


---
## https://adventofcode.com/2021/day/24 &mdash;

## Part 1

This part asks

### Strategy

- parse the data

## Part 2

This part asks to find

### Strategy

- parse the data

In [24]:
#!/usr/bin/env python3
#
# https://adventofcode.com/2021/
#
# AOC 2021 24
#
# aoc202124.py
#

print('# AOC 2021 24')

data = [ x for x in """
""".split('\n') if x ]
print(data)

def part1(data):
    """Answer part 1 of https://adventofcode.com/2021/day/24"""
print(part1(data))

def part2(data):
    """Answer part 2 of https://adventofcode.com/2021/day/24"""
print(part2(data))

# AOC 2021 24
[]
None
None
